# Generated by build.py — DO NOT EDIT
# Type stub for Krita scripting API (libkis)

# Internal C++ types (opaque to Python)
from krita._types._opaque import *

# Krita Scripting API classes

# Node:
#   `Node` represents a layer or mask in a `Krita` image's `Node` hierarchy. Group layers can contain other layers and masks; layers can contain masks.
#
from krita._types.node import Node as Node

# Shape:
#   The `Shape` class The shape class is a wrapper around `Krita`'s vector objects.
#   
#   Some example code to parse through interesting information in a given vector layer with shapes. 
#   ```
#   import sys
#   from krita import *
#   
#   doc = Application.activeDocument()
#   
#   root = doc.rootNode()
#   
#   for layer in root.childNodes():
#       print (str(layer.type())+" "+str(layer.name()))
#       if (str(layer.type())=="vectorlayer"):
#           for shape in layer.shapes():
#               print(shape.`name`())
#               print(shape.`toSvg`())
#   ```
#
from krita._types.shape import Shape as Shape

# AngleSelector:
#   A wrapper around KisAngleSelector, a widget with several options to select an angle. The widget itself is accessed with the `widget()` function.
#   
#   This widget is a combination of a KisAngleGauge and a spin box, along with some flipping options
#
from krita._types.angle_selector import AngleSelector as AngleSelector

# Canvas:
#   `Canvas` wraps the canvas inside a view on an image/document. It is responsible for the view parameters of the document: zoom, rotation, mirror, wraparound and instant preview.
#
from krita._types.canvas import Canvas as Canvas

# Channel:
#   A `Channel` represents a single channel in a `Node`. `Krita` does not use channels to store local selections: these are strictly the color and alpha channels.
#
from krita._types.channel import Channel as Channel

# DockWidget:
#   `DockWidget` is the base class for custom Dockers. Dockers are created by a factory class which needs to be registered by calling Application.addDockWidgetFactory:
#   
#   
#   ```
#   class HelloDocker(DockWidget):
#     def __init__(self):
#         super().__init__()
#         label = QLabel("Hello", self)
#         self.setWidget(label)
#         self.label = label
#         self.setWindowTitle("Hello Docker")
#   
#   def canvasChanged(self, canvas):
#         self.label.setText("Hellodocker: canvas changed");
#   
#   Application.addDockWidgetFactory(DockWidgetFactory("hello", DockWidgetFactoryBase.DockRight, HelloDocker))
#   ```
#   
#   
#   One docker per window will be created, not one docker per canvas or view. When the user switches between views/canvases, canvasChanged will be called. You can override that method to reset your docker's internal state, if necessary.
#
from krita._types.dock_widget import DockWidget as DockWidget

# DockWidgetFactoryBase:
#   The `DockWidgetFactoryBase` class is the base class for plugins that want to add a dock widget to every window. You do not need to implement this class yourself, but create a `DockWidget` implementation and then add the DockWidgetFactory to the `Krita` instance like this:
#   
#   ```
#   class HelloDocker(DockWidget):
#     def __init__(self):
#         super().__init__()
#         label = QLabel("Hello", self)
#         self.setWidget(label)
#         self.label = label
#   
#   def canvasChanged(self, canvas):
#         self.label.setText("Hellodocker: canvas changed");
#   
#   Application.addDockWidgetFactory(DockWidgetFactory("hello", DockWidgetFactoryBase.DockRight, HelloDocker))
#   ```
#
from krita._types.dock_widget_factory_base import DockWidgetFactoryBase as DockWidgetFactoryBase

# Document:
#   The `Document` class encapsulates a `Krita` Document/Image. A `Krita` document is an Image with a filename. Libkis does not differentiate between a document and an image, like `Krita` does internally.
#
from krita._types.document import Document as Document

# DoubleParseSpinBox:
#   A wrapper around KisDoubleParseSpinBox, which is a cleverer doubleSpinBox, able to parse arithmetic expressions. The widget itself is accessed with the `widget()` function.
#   
#   Use this spinbox instead of the basic one from Qt if you want it to be able to parse arithmetic expressions.
#
from krita._types.double_parse_spin_box import DoubleParseSpinBox as DoubleParseSpinBox

# Extension:
#   An `Extension` is the base for classes that extend `Krita`. An `Extension` is loaded on startup, when the `setup()` method will be executed.
#   
#   
#   The extension instance should be added to the `Krita` Application object using `Krita.instance()`.addViewExtension or Application.addViewExtension or Scripter.addViewExtension.
#   
#   
#   Example:
#   
#   
#   ```
#   import sys
#   from PyQt5.QtGui import *
#   from PyQt5.QtWidgets import *
#   from krita import *
#   class HelloExtension(Extension):
#   
#   def __init__(self, parent):
#       super().__init__(parent)
#   
#   def hello(self):
#       QMessageBox.information(QWidget(), "Test", "Hello! This is Krita " + Application.version())
#   
#   def `setup`(self):
#       qDebug("Hello Setup")
#   
#   def createActions(self, window)
#       action = window.createAction("hello")
#       action.triggered.connect(self.hello)
#   
#   Scripter.addExtension(HelloExtension(`Krita`.instance()))
#   ```
#
from krita._types.extension import Extension as Extension

# FileDialog:
#   Wrapper around KoFileDialog, which is a wrapper around QFileDialog, providing native file dialogs on KDE/Gnome/Windows/OSX/etc. `FileDialog` respects `Krita`'s "Don't use native file dialogs" setting.
#
from krita._types.file_dialog import FileDialog as FileDialog

# Filter:
#   `Filter`: represents a filter and its configuration. A filter is identified by an internal name. The configuration for each filter is defined as an `InfoObject`: a map of name and value pairs.
#   
#   
#   Currently available filters are:
#   
#   
#   'autocontrast', 'blur', 'bottom edge detections', 'brightnesscontrast', 'burn', 'colorbalance', 'colortoalpha', 'colortransfer', 'desaturate', 'dodge', 'emboss', 'emboss all directions', 'emboss horizontal and vertical', 'emboss horizontal only', 'emboss laplascian', 'emboss vertical only', 'gaussian blur', 'gaussiannoisereducer', 'gradientmap', 'halftone', 'hsvadjustment', 'indexcolors', 'invert', 'left edge detections', 'lens blur', 'levels', 'maximize', 'mean removal', 'minimize', 'motion blur', 'noise', 'normalize', 'oilpaint', 'perchannel', 'phongbumpmap', 'pixelize', 'posterize', 'raindrops', 'randompick', 'right edge detections', 'roundcorners', 'sharpen', 'smalltiles', 'sobel', 'threshold', 'top edge detections', 'unsharp', 'wave', 'waveletnoisereducer']
#
from krita._types.filter import Filter as Filter

# GridConfig:
#   The `GridConfig` class encapsulates a `Krita` Guides configuration.
#
from krita._types.grid_config import GridConfig as GridConfig

# GuidesConfig:
#   The `GuidesConfig` class encapsulates a `Krita` Guides configuration.
#
from krita._types.guides_config import GuidesConfig as GuidesConfig

# InfoObject:
#   `InfoObject` wrap a properties map. These maps can be used to set the configuration for filters.
#
from krita._types.info_object import InfoObject as InfoObject

# IntParseSpinBox:
#   A wrapper around KisIntParseSpinBox, which is a cleverer SpinBox, able to parse arithmetic expressions. The widget itself is accessed with the `widget()` function.
#   
#   Use this spinbox instead of the basic one from Qt if you want it to be able to parse arithmetic expressions.
#
from krita._types.int_parse_spin_box import IntParseSpinBox as IntParseSpinBox

# Krita:
#   `Krita` is a singleton class that offers the root access to the `Krita` object hierarchy.
#   
#   
#   The `Krita.instance()` is aliased as two builtins: Scripter and Application.
#
from krita._types.krita import Krita as Krita

# ManagedColor:
#   The `ManagedColor` class is a class to handle colors that are color managed. A managed color is a color of which we know the model(RGB, LAB, CMYK, etc), the bitdepth and the specific properties of its colorspace, such as the whitepoint, chromaticities, trc, etc, as represented by the color profile.
#   
#   `Krita` has two color management systems. LCMS and OCIO. LCMS is the one handling the ICC profile stuff, and the major one handling that `ManagedColor` deals with. OCIO support is only in the display of the colors. `ManagedColor` has some support for it in `colorForCanvas()`
#   
#   
#   All colors in `Krita` are color managed. QColors are understood as RGB-type colors in the sRGB space.
#   
#   
#   We recommend you make a color like this:
#   
#   
#   ```
#   colorYellow = `ManagedColor`("RGBA", "U8", "")
#   QVector<float> yellowComponents = colorYellow.`components`()
#   yellowComponents[0] = 1.0
#   yellowComponents[1] = 1.0
#   yellowComponents[2] = 0
#   yellowComponents[3] = 1.0
#   
#   colorYellow.`setComponents`(yellowComponents)
#   QColor yellow = colorYellow.`colorForCanvas`(canvas)
#   ```
#
from krita._types.managed_color import ManagedColor as ManagedColor

# Notifier:
#   The `Notifier` can be used to be informed of state changes in the `Krita` application.
#
from krita._types.notifier import Notifier as Notifier

# Palette:
#   The `Palette` class `Palette` is a resource object that stores organised color data. It's purpose is to allow artists to save colors and store them.
#   
#   An example for printing all the palettes and the entries:
#   
#   
#   ```
#   import sys
#   from krita import *
#   
#   resources = Application.resources("palette")
#   
#   for (k, v) in resources.items():
#       print(k)
#       palette = `Palette`(v)
#       for x in range(palette.numberOfEntries()):
#           entry = palette.`colorSetEntryByIndex`(x)
#           print(x, entry.name(), entry.id(), entry.spotColor())
#   ```
#
from krita._types.palette import Palette as Palette

# PaletteView:
#   The `PaletteView` class is a wrapper around a MVC method for handling palettes. This class shows a nice widget that can drag and drop, edit colors in a colorset and will handle adding and removing entries if you'd like it to.
#
from krita._types.palette_view import PaletteView as PaletteView

# Preset:
#   The `Preset` class `Preset` is a resource object that stores brush preset data.
#   
#   An example for printing the current brush preset and all its settings:
#   
#   
#   ```
#   from krita import *
#   
#   view = Krita.instance().activeWindow().activeView()
#   preset = Preset(view.currentBrushPreset())
#   
#   print ( preset.toXML() )
#   ```
#
from krita._types.preset import Preset as Preset

# PresetChooser:
#   The `PresetChooser` widget wraps the KisPresetChooser widget. The widget provides for selecting brush presets. It has a tagging bar and a filter field. It is not automatically synchronized with the currently selected preset in the current Windows.
#
from krita._types.preset_chooser import PresetChooser as PresetChooser

# Resource:
#   A `Resource` represents a gradient, pattern, brush tip, brush preset, palette or workspace definition.
#   
#   
#   ```
#   allPresets = Application.resources("preset")
#   for preset in allPresets:
#       print(preset.name())
#   ```
#   
#   
#   Resources are identified by their type, name and filename. If you want to change the contents of a resource, you should read its data using data(), parse it and write the changed contents back.
#
from krita._types.resource import Resource as Resource

# Scratchpad:
#   The `Scratchpad` class A scratchpad is a type of blank canvas area that can be painted on with the normal painting devices.
#
from krita._types.scratchpad import Scratchpad as Scratchpad

# Selection:
#   `Selection` represents a selection on `Krita`. A selection is not necessarily associated with a particular `Node` or Image.
#   
#   
#   ```
#   from krita import *
#   
#   d = Application.activeDocument()
#   n = d.activeNode()
#   r = n.bounds() 
#   s = Selection()
#   s.select(r.width() / 3, r.height() / 3, r.width() / 3, r.height() / 3, 255)
#   s.cut(n)
#   ```
#
from krita._types.selection import Selection as Selection

# Swatch:
#   The `Swatch` class is a thin wrapper around the KisSwatch class.
#   
#   A `Swatch` is a single color that is part of a palette, that has a name and an id. A `Swatch` color can be a spot color.
#
from krita._types.swatch import Swatch as Swatch

# View:
#   `View` represents one view on a document. A document can be shown in more than one view at a time.
#
from krita._types.view import View as View

# Window:
#   `Window` represents one `Krita` mainwindow. A window can have any number of views open on any number of documents.
#
from krita._types.window import Window as Window

# CloneLayer:
#   The `CloneLayer` class A clone layer is a layer that takes a reference inside the image and shows the exact same pixeldata.
#   
#   If the original is updated, the clone layer will update too.
#
from krita._types.clone_layer import CloneLayer as CloneLayer

# ColorizeMask:
#   The `ColorizeMask` class A colorize mask is a mask type node that can be used to color in line art.
#   
#   ```
#   window = `Krita`.`instance`().`activeWindow`()
#   doc = `Krita`.`instance`().`createDocument`(10, 3, "Test", "RGBA", "U8", "", 120.0)
#   window.addView(doc)
#   root = doc.`rootNode`();
#   node = doc.createNode("layer", "paintLayer")
#   root.`addChildNode`(node, None)
#   nodeData = QByteArray.fromBase64(b"AAAAAAAAAAAAAAAAEQYMBhEGDP8RBgz/EQYMAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARBgz5EQYM/xEGDAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEQYMAhEGDAkRBgwCAAAAAAAAAAAAAAAA");
#   node.setPixelData(nodeData,0,0,10,3)
#   
#   cols = [ `ManagedColor`('RGBA','U8',''), `ManagedColor`('RGBA','U8','') ]
#   cols[0].setComponents([0.65490198135376, 0.345098048448563, 0.474509805440903, 1.0]);
#   cols[1].setComponents([0.52549022436142, 0.666666686534882, 1.0, 1.0]);
#   keys = [
#           QByteArray.fromBase64(b"/48AAAAAAAAAAAAAAAAAAAAAAACmCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"),
#           QByteArray.fromBase64(b"AAAAAAAAAACO9ocAAAAAAAAAAAAAAAAAAAAAAMD/uQAAAAAAAAAAAAAAAAAAAAAAGoMTAAAAAAAAAAAA")
#           ]
#   
#   mask = doc.createColorizeMask('c1')
#   node.addChildNode(mask,None)
#   mask.setEditKeyStrokes(True)
#   
#   mask.setUseEdgeDetection(True)
#   mask.setEdgeDetectionSize(4.0)
#   mask.setCleanUpAmount(70.0)
#   mask.setLimitToDeviceBounds(True)
#   mask.initializeKeyStrokeColors(cols)
#   
#   for col,key in zip(cols,keys):
#       mask.`setKeyStrokePixelData`(key,col,0,0,20,3)
#   
#   mask.`updateMask`()
#   mask.`setEditKeyStrokes`(False);
#   mask.setShowOutput(True);
#   ```
#
from krita._types.colorize_mask import ColorizeMask as ColorizeMask

# FileLayer:
#   The `FileLayer` class A file layer is a layer that can reference an external image and show said reference in the layer stack.
#   
#   If the external image is updated, `Krita` will try to update the file layer image as well.
#
from krita._types.file_layer import FileLayer as FileLayer

# FillLayer:
#   The `FillLayer` class A fill layer is much like a filter layer in that it takes a name and filter. It however specializes in filters that fill the whole canvas, such as a pattern or full color fill.
#
from krita._types.fill_layer import FillLayer as FillLayer

# FilterLayer:
#   The `FilterLayer` class A filter layer will, when compositing, take the composited image up to the point of the location of the filter layer in the stack, create a copy and apply a filter.
#   
#   This means you can use blending modes on the filter layers, which will be used to blend the filtered image with the original.
#   
#   
#   Similarly, you can activate things like alpha inheritance, or you can set grayscale pixeldata on the filter layer to act as a mask.
#   
#   
#   `Filter` layers can be animated.
#
from krita._types.filter_layer import FilterLayer as FilterLayer

# FilterMask:
#   The `FilterMask` class A filter mask, unlike a filter layer, will add a non-destructive filter to the composited image of the node it is attached to.
#   
#   You can set grayscale pixeldata on the filter mask to adjust where the filter is applied.
#   
#   
#   Filtermasks can be animated.
#
from krita._types.filter_mask import FilterMask as FilterMask

# GroupLayer:
#   The `GroupLayer` class A group layer is a layer that can contain other layers. In `Krita`, layers within a group layer are composited first before they are added into the composition code for where the group is in the stack. This has a significant effect on how it is interpreted for blending modes.
#   
#   PassThrough changes this behaviour.
#   
#   
#   Group layer cannot be animated, but can contain animated layers or masks.
#
from krita._types.group_layer import GroupLayer as GroupLayer

# SelectionMask:
#   The `SelectionMask` class A selection mask is a mask type node that can be used to store selections. In the gui, these are referred to as local selections.
#   
#   A selection mask can hold both raster and vector selections, though the API only supports raster selections.
#
from krita._types.selection_mask import SelectionMask as SelectionMask

# TransformMask:
#   The `TransformMask` class A transform mask is a mask type node that can be used to store transformations.
#
from krita._types.transform_mask import TransformMask as TransformMask

# TransparencyMask:
#   The `TransparencyMask` class A transparency mask is a mask type node that can be used to show and hide parts of a layer.
#
from krita._types.transparency_mask import TransparencyMask as TransparencyMask

# VectorLayer:
#   The `VectorLayer` class A vector layer is a special layer that stores and shows vector shapes.
#   
#   Vector shapes all have their coordinates in points, which is a unit that represents 1/72th of an inch. Keep this in mind wen parsing the bounding box and position data.
#
from krita._types.vector_layer import VectorLayer as VectorLayer

# GroupShape:
#   The `GroupShape` class A group shape is a vector object with child shapes.
#
from krita._types.group_shape import GroupShape as GroupShape

# DoubleSliderSpinBox:
#   This class is a wrapper around KisDoubleSliderSpinBox, a spinbox in which you can click and drag to set the value, with a slider like bar displayed inside. The widget itself is accessed with the `widget()` function.
#   
#   See also: `SliderSpinBox`
#
from krita._types.double_slider_spin_box import DoubleSliderSpinBox as DoubleSliderSpinBox

# SliderSpinBox:
#   This class is a wrapper around KisSliderSpinBox, a spinbox in which you can click and drag to set the value, with a slider like bar displayed inside. The widget itself is accessed with the `widget()` function.
#   
#   The value can be set by click and dragging with the mouse or pen or by typing in with the keyboard. To enter the edit mode, in which the keyboard can be used, one has to right-click inside the spinbox or click and hold the pointer inside or press the enter key. To leave the edit mode, one can press the enter key again, in which case the value is committed, or press the escape key, in which case the value is rejected.
#   
#   
#   When dragging with the pointer, one can fine tune the value by dragging far away vertically from the spinbox. The farther the pointer is, the slower the value will change. If the pointer is inside the spinbox plus a certain margin, the value will not be scaled. By pressing the shift key the slow down will be even more pronounced and by pressing the control key the value will snap to the increment set by `setFastSliderStep`. The two keys can be used at the same time.
#   
#   
#   A "soft range" can be set to make the slider display only a sub-range of the spinbox range. This way one can have a large range but display and set with the pointer and with more precision only the most commonly used sub-set of values. A value outside the "soft range" can be set by entering the edit mode and using the keyboard. The "soft range" is considered valid if the "soft maximum" is greater than the "soft minimum".
#
from krita._types.slider_spin_box import SliderSpinBox as SliderSpinBox
