#!/usr/bin/env python3
"""Generate krita.pyi from Doxygen XML documentation.

Parses class_*.xml and namespace_*.xml files (generated by Doxygen from Krita's
libkis C++ headers) and produces a clean, Pythonic type stub (.pyi) file for
IDE auto-completion when writing Krita plugins.
"""

from __future__ import annotations

import argparse
import dataclasses
import re
import sys
from collections import defaultdict
from pathlib import Path
from typing import NamedTuple
from xml.etree import ElementTree as ET

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

QT_MODULES = {
    "QObject": "PyQt5.QtCore",
    "Qt": "PyQt5.QtCore",
    "QUuid": "PyQt5.QtCore",
    "QByteArray": "PyQt5.QtCore",
    "QRect": "PyQt5.QtCore",
    "QRectF": "PyQt5.QtCore",
    "QPoint": "PyQt5.QtCore",
    "QPointF": "PyQt5.QtCore",
    "QVariant": "PyQt5.QtCore",
    "QUrl": "PyQt5.QtCore",
    "pyqtSignal": "PyQt5.QtCore",
    "QColor": "PyQt5.QtGui",
    "QImage": "PyQt5.QtGui",
    "QPainterPath": "PyQt5.QtGui",
    "QTransform": "PyQt5.QtGui",
    "QIcon": "PyQt5.QtGui",
    "QDockWidget": "PyQt5.QtWidgets",
    "QMainWindow": "PyQt5.QtWidgets",
    "QWidget": "PyQt5.QtWidgets",
    "QAction": "PyQt5.QtWidgets",
    "QDoubleSpinBox": "PyQt5.QtWidgets",
    "QSpinBox": "PyQt5.QtWidgets",
}

# Classes that are internal to Krita C++ and should be skipped entirely
SKIP_CLASSES = {"KisSliderSpinBoxPrivate"}

# Classes that are base dependencies — always output first
PRIORITY_BASES = ["Node", "Shape"]


# ---------------------------------------------------------------------------
# Doxygen XML → plain text
# ---------------------------------------------------------------------------

def _doxy_text(elem: ET.Element | None, *, plain: bool = False) -> str:
    """Recursively extract text from a Doxygen XML element tree.

    When *plain* is True, no markdown formatting (backticks, links) is added.
    """
    if elem is None:
        return ""
    tag = elem.tag

    if tag == "text":
        return elem.text or ""

    if tag in ("briefdescription", "detaileddescription", "inbodydescription",
               "highlight", "verbatim", "codeline"):
        return _gos(elem, plain=plain)

    if tag == "para":
        inner = _gos(elem, plain=plain).strip()
        return f"\n{inner}\n" if inner else ""

    if tag == "ref":
        name = _gos(elem, plain=plain)
        return name if plain else f"`{name}`"

    if tag in ("emphasis", "computeroutput", "bold"):
        inner = _gos(elem, plain=plain)
        return inner if plain else f"`{inner}`"

    if tag == "programlisting":
        lines = []
        for child in elem:
            if child.tag == "codeline":
                lines.append(_gos(child, plain=plain))
        code = "\n".join(lines).strip()
        return f"\n```\n{code}\n```\n" if code else ""

    if tag == "itemizedlist":
        return "\n" + _gos(elem, plain=plain)

    if tag == "listitem":
        inner = _gos(elem, plain=plain).strip()
        return f"- {inner}\n" if inner else ""

    if tag == "simplesect":
        kind = elem.get("kind", "")
        if kind == "return":
            return ":returns: " + _gos(elem, plain=plain).strip()
        if kind == "see":
            see = _gos(elem, plain=plain).strip()
            return f"\nSee also: {see}" if see else ""
        if kind == "note":
            return "\nNote: " + _gos(elem, plain=plain).strip()
        if kind == "warning":
            return "\nWarning: " + _gos(elem, plain=plain).strip()
        if kind == "since":
            return "\nSince: " + _gos(elem, plain=plain).strip()
        return ""

    if tag == "parameterlist":
        return ""  # handled separately

    if tag == "parameteritem":
        return ""  # handled separately

    if tag == "ulink":
        url = elem.get("url", "")
        text = _gos(elem, plain=plain)
        return text if plain else (f"[{text}]({url})" if url else text)

    if tag == "sp":
        return " "

    if tag == "ndash":
        return "—"

    if tag == "linebreak":
        return "\n"

    if tag == "hruler":
        return "\n---\n"

    # fallback for unknown tags
    return _gos(elem, plain=plain)


def _gos(elem: ET.Element | None, *, plain: bool = False) -> str:
    """Walk all children, extract text, and smart-concatenate."""
    if elem is None:
        return ""
    children = list(elem)
    if not children:
        return elem.text or ""
    parts = []
    if elem.text:
        parts.append(elem.text)
    for child in children:
        parts.append(_doxy_text(child, plain=plain))
        if child.tail:
            parts.append(child.tail)
    result = "".join(parts)
    return result


def _extract_param_docs(detail: ET.Element | None) -> dict[str, str]:
    """Extract parameter documentation from detaileddescription."""
    if detail is None:
        return {}
    param_docs: dict[str, str] = {}
    for item in detail.iter("parameteritem"):
        name_elem = item.find("parameternamelist/parametername")
        desc_elem = item.find("parameterdescription")
        if name_elem is not None and desc_elem is not None:
            name = _gos(name_elem).strip()
            desc = _gos(desc_elem).strip()
            if name and desc:
                param_docs[name] = desc
    return param_docs


def make_docstring(brief: ET.Element | None, detail: ET.Element | None,
                   param_docs: dict[str, str] | None = None) -> str:
    """Build a clean reST-style docstring from Doxygen brief + detail."""
    brief_text = _gos(brief).strip() if brief is not None else ""
    detail_text = _gos(detail).strip() if detail is not None else ""

    # Extract parameter list from detail (it gets removed by _doxy_text)
    raw_param_docs = _extract_param_docs(detail)

    sections: list[str] = []

    if brief_text:
        sections.append(brief_text)

    # Clean detail: remove leading/trailing blank lines
    if detail_text:
        # Merge brief into the start of detail if brief already said the same thing
        cleaned = _clean_docstring(detail_text)
        if cleaned and cleaned != brief_text:
            sections.append(cleaned)

    # Parameter docs
    pd = param_docs or raw_param_docs
    if pd:
        param_block = "\n".join(
            f":param {name}: {desc}" for name, desc in pd.items()
        )
        sections.append(param_block)

    return "\n\n".join(sections)


def _clean_docstring(text: str) -> str:
    """Normalise whitespace, strip @brief, and remove redundant blank lines."""
    text = re.sub(r'^\s*@brief\s+', '', text)
    lines = text.splitlines()
    # Remove leading/trailing blank lines
    while lines and not lines[0].strip():
        lines.pop(0)
    while lines and not lines[-1].strip():
        lines.pop()
    # Collapse 3+ blank lines into 2
    cleaned: list[str] = []
    blank_count = 0
    for line in lines:
        if not line.strip():
            blank_count += 1
            if blank_count <= 2:
                cleaned.append("")
        else:
            blank_count = 0
            cleaned.append(line)
    return "\n".join(cleaned)


def indent(text: str, level: int = 1) -> str:
    """Indent each line of *text* by *level* × 4 spaces."""
    prefix = " " * (level * 4)
    return "\n".join(prefix + line if line.strip() else ""
                     for line in text.splitlines())


# ---------------------------------------------------------------------------
# C++ → Python type conversion
# ---------------------------------------------------------------------------

def _cpp_to_py_type(cpp_type_raw: str) -> str:
    """Convert a C++ type string to a Python type annotation."""
    t = cpp_type_raw.strip()
    # Remove cv-qualifiers and indirection
    t = re.sub(r'\bconst\b\s*', '', t)
    t = t.replace('*', '').replace('&', '').strip()

    # Strip Qt macros
    t = re.sub(r'\bQ_DECL_DEPRECATED\b', '', t).strip()

    # Normalise C++ scoped names: Qt::Orientations → Qt.Orientations
    t = re.sub(r'(\w+)::(\w+)', r'\1.\2', t)

    if not t or t == 'void':
        return 'None'

    # Template types — handle QList<T>, QMap<K,V>, QVector<T>
    # Must be done before word-boundary replacements
    t = re.sub(r'\bQList\s*<\s*(.+?)\s*>', r'list[\1]', t)
    t = re.sub(r'\bQMap\s*<\s*(.+?)\s*,\s*(.+?)\s*>', r'dict[\1, \2]', t)
    t = re.sub(r'\bQVector\s*<\s*(.+?)\s*>', r'list[\1]', t)
    t = re.sub(r'\bQPair\s*<\s*(.+?)\s*,\s*(.+?)\s*>', r'tuple[\1, \2]', t)

    # Now simple replacements
    replacements = [
        (r'\bQString\b', 'str'),
        (r'\bQStringList\b', 'list[str]'),
        (r'\bQByteArray\b', 'QByteArray'),
        (r'\bQVariant\b', 'Any'),
        (r'\bqreal\b', 'float'),
        (r'\bdouble\b', 'float'),
        (r'\bfloat\b', 'float'),
        (r'\bbool\b', 'bool'),
        (r'\bunsigned\s+int\b', 'int'),
        (r'\bint\b', 'int'),
        (r'\bqint32\b', 'int'),
        (r'\bQObject\b', 'QObject'),
        (r'\bQColor\b', 'QColor'),
        (r'\bQRect\b', 'QRect'),
        (r'\bQRectF\b', 'QRectF'),
        (r'\bQPoint\b', 'QPoint'),
        (r'\bQPointF\b', 'QPointF'),
        (r'\bQTransform\b', 'QTransform'),
        (r'\bQIcon\b', 'QIcon'),
        (r'\bQImage\b', 'QImage'),
        (r'\bQUuid\b', 'QUuid'),
        (r'\bQWidget\b', 'QWidget'),
        (r'\bQDockWidget\b', 'QDockWidget'),
        (r'\bQMainWindow\b', 'QMainWindow'),
        (r'\bQAction\b', 'QAction'),
    ]
    for pattern, repl in replacements:
        t = re.sub(pattern, repl, t)

    # Clean up leftover whitespace
    return re.sub(r'\s+', ' ', t).strip()


def convert_type(cpp_type_raw: str) -> tuple[str, set[str]]:
    """Convert C++ type and return (py_type, {referenced_type_names}).

    Referenced type names are used to track which Qt/typing imports are needed.
    """
    py = _cpp_to_py_type(cpp_type_raw)
    refs: set[str] = set()
    # Collect known Qt type references
    for qt_type in QT_MODULES:
        if re.search(r'\b' + re.escape(qt_type) + r'\b', py):
            refs.add(qt_type)
    return py, refs


def convert_default_value(cpp_val: str, param_type_cpp: str) -> str | None:
    """Convert a C++ default value to Python literal, or None if empty."""
    cpp_val = cpp_val.strip()
    if not cpp_val:
        return None
    param_type_py, _ = convert_type(param_type_cpp)

    # QString() or QString("xxx")
    m = re.match(r'QString\(\s*"(.*)"\s*\)', cpp_val)
    if m:
        return repr(m.group(1))

    # QString() without arguments → empty string
    if re.match(r'QString\(\s*\)', cpp_val):
        return '""'

    # QPointF(x, y)
    m = re.match(r'QPointF\((.+)\)', cpp_val)
    if m:
        return f"QPointF({m.group(1)})"

    # Numeric defaults
    if cpp_val == '0' and param_type_py not in ('int', 'float', 'bool'):
        return 'None'
    if cpp_val.isdigit() or (cpp_val.startswith('-') and cpp_val[1:].isdigit()):
        return cpp_val
    if cpp_val.replace('.', '', 1).replace('-', '', 1).isdigit():
        return cpp_val

    # Booleans
    if cpp_val == 'true':
        return 'True'
    if cpp_val == 'false':
        return 'False'
    if cpp_val == 'nullptr':
        return 'None'

    # Strip surrounding quotes → Python string literal
    if cpp_val.startswith('"') and cpp_val.endswith('"'):
        return repr(cpp_val[1:-1])
    if cpp_val.startswith("'") and cpp_val.endswith("'"):
        return repr(cpp_val[1:-1])

    # Resolve known namespace variable references to their string values
    NS_DEFAULTS = {
        "PaintingResources::defaultStrokeStyle": '"ForegroundColor"',
        "PaintingResources::defaultFillStyle": '"None"',
    }
    if cpp_val in NS_DEFAULTS:
        return NS_DEFAULTS[cpp_val]

    # Normalise C++ scoped references: Namespace::value → Namespace.value
    cpp_val = re.sub(r'(\w+)::(\w+)', r'\1.\2', cpp_val)

    # Enum-like defaults: keep as-is (they'll be class attributes)
    return cpp_val


# ---------------------------------------------------------------------------
# XML extraction
# ---------------------------------------------------------------------------

class Member(NamedTuple):
    name: str
    kind: str          # "method" | "constructor" | "signal" | "static_method"
    return_type: str
    params: list[tuple[str, str, str | None]]  # (name, type, default)
    doc: str
    is_static: bool


class EnumValue(NamedTuple):
    name: str
    value: str | None


@dataclasses.dataclass
class EnumDef:
    name: str
    values: list[EnumValue]

@dataclasses.dataclass
class ClassDef:
    name: str
    bases: list[str]
    doc: str
    members: list[Member]
    enums: list[EnumDef]


class NamespaceDef(NamedTuple):
    name: str
    doc: str
    variables: list[tuple[str, str]]     # (name, py_type)
    functions: list[Member]


def _doc_text_of(elem: ET.Element | None) -> str:
    """Extract markdown-formatted text (for docstrings)."""
    return _gos(elem).strip() if elem is not None else ""


def _param_name(param_elem: ET.Element, counter: int) -> str:
    """Extract parameter name, fall back to `arg{counter}` if missing."""
    decl = param_elem.find("declname")
    if decl is not None:
        name = _gos(decl, plain=True).strip()
        if name:
            return name
    return f"arg{counter}"


def _type_text_of(elem: ET.Element | None) -> str:
    """Extract plain text WITHOUT markdown (for type annotations)."""
    return _gos(elem, plain=True).strip() if elem is not None else ""


def extract_members(compound: ET.Element, class_name: str) -> list[Member]:
    """Extract public methods/signals/slots from a compounddef element."""
    members: list[Member] = []

    for memberdef in compound.findall(".//memberdef"):
        kind = memberdef.get("kind", "")
        prot = memberdef.get("prot", "")
        if prot != "public":
            continue

        # Methods, slots, signals
        if kind not in ("function", "slot", "signal"):
            continue

        name_elem = memberdef.find("name")
        if name_elem is None:
            continue
        name = _type_text_of(name_elem)

        # Skip destructors, operators, and Qt-internal methods
        if '~' in name or 'operator' in name.lower():
            continue

        is_static = memberdef.get("static", "no") == "yes"

        if kind == "signal":
            # Build param list for signal
            params: list[tuple[str, str, str | None]] = []
            for i, param in enumerate(memberdef.findall("param")):
                ptype = _type_text_of(param.find("type"))
                ptype_py, _ = convert_type(ptype)
                pname = _param_name(param, i)
                params.append((pname, ptype_py, None))
            brief = memberdef.find("briefdescription")
            detail = memberdef.find("detaileddescription")
            doc = make_docstring(brief, detail)
            members.append(Member(
                name=name, kind="signal", return_type="",
                params=params, doc=doc, is_static=False
            ))
            continue

        # Function or slot
        ret_type_elem = memberdef.find("type")
        ret_type_cpp = _type_text_of(ret_type_elem) if ret_type_elem is not None else ""
        ret_type_py, _ = convert_type(ret_type_cpp) if ret_type_cpp else ("None", set())

        is_constructor = (name == class_name)

        params: list[tuple[str, str, str | None]] = []
        for i, param in enumerate(memberdef.findall("param")):
            ptype_cpp = _type_text_of(param.find("type"))
            ptype_py, _ = convert_type(ptype_cpp)
            pname = _param_name(param, i)
            defval_elem = param.find("defval")
            defval = None
            if defval_elem is not None:
                defval = convert_default_value(_type_text_of(defval_elem), ptype_cpp)
            params.append((pname, ptype_py, defval))

        brief = memberdef.find("briefdescription")
        detail = memberdef.find("detaileddescription")
        doc = make_docstring(brief, detail)

        kind_str = "constructor" if is_constructor else ("static_method" if is_static else "method")
        members.append(Member(
            name=name, kind=kind_str,
            return_type=ret_type_py if ret_type_py != "void" else "None",
            params=params, doc=doc, is_static=is_static
        ))

    return members


def extract_enums(compound: ET.Element) -> list[EnumDef]:
    """Extract public enums from a compounddef."""
    enums: list[EnumDef] = []
    for enum_elem in compound.findall(".//memberdef[@kind='enum']"):
        if enum_elem.get("prot", "") != "public":
            continue
        name_elem = enum_elem.find("name")
        if name_elem is None:
            continue
        enum_name = _type_text_of(name_elem)
        values: list[EnumValue] = []
        for ev in enum_elem.findall("enumvalue"):
            ev_name = _type_text_of(ev.find("name")) if ev.find("name") is not None else ""
            ev_initializer = ev.find("initializer")
            ev_val = _type_text_of(ev_initializer) if ev_initializer is not None else None
            values.append(EnumValue(name=ev_name, value=ev_val))
        enums.append(EnumDef(name=enum_name, values=values))
    return enums


def parse_class_xml(filepath: Path) -> ClassDef | None:
    """Parse a class_*.xml file and return a ClassDef, or None if skipped."""
    tree = ET.parse(filepath)
    root = tree.getroot()
    compound = root.find(".//compounddef[@kind='class']")
    if compound is None:
        return None

    name = _type_text_of(compound.find("compoundname"))
    if name in SKIP_CLASSES:
        return None

    # Parent classes
    bases: list[str] = []
    for base in compound.findall("basecompoundref"):
        base_name = _type_text_of(base)
        if base_name and not base_name.startswith("Q"):
            bases.append(base_name)

    # Doc
    brief = compound.find("briefdescription")
    detail = compound.find("detaileddescription")
    class_doc = make_docstring(brief, detail)

    # Members
    members = extract_members(compound, name)

    # Enums
    enums = extract_enums(compound)

    return ClassDef(name=name, bases=bases, doc=class_doc,
                    members=members, enums=enums)


def parse_namespace_xml(filepath: Path) -> NamespaceDef | None:
    """Parse a namespace_*.xml file."""
    tree = ET.parse(filepath)
    root = tree.getroot()
    compound = root.find(".//compounddef[@kind='namespace']")
    if compound is None:
        return None

    name = _type_text_of(compound.find("compoundname"))

    brief = compound.find("briefdescription")
    detail = compound.find("detaileddescription")
    doc = make_docstring(brief, detail)

    variables: list[tuple[str, str]] = []
    functions: list[Member] = []

    for memberdef in compound.findall(".//memberdef"):
        kind = memberdef.get("kind", "")
        prot = memberdef.get("prot", "")

        name_elem = memberdef.find("name")
        if name_elem is None:
            continue
        member_name = _type_text_of(name_elem)

        if kind == "variable" and prot == "public":
            ptype_cpp = _type_text_of(memberdef.find("type"))
            ptype_py, _ = convert_type(ptype_cpp)
            variables.append((member_name, ptype_py))

        elif kind == "function" and prot == "public":
            ret_type_cpp = _type_text_of(memberdef.find("type"))
            ret_type_py, _ = convert_type(ret_type_cpp) if ret_type_cpp else ("None", set())

            params: list[tuple[str, str, str | None]] = []
            for i, param in enumerate(memberdef.findall("param")):
                ptype = _type_text_of(param.find("type"))
                ptype_py, _ = convert_type(ptype)
                pname = _param_name(param, i)
                defval_elem = param.find("defval")
                defval = None
                if defval_elem is not None:
                    defval = convert_default_value(_gos(defval_elem).strip(), ptype)
                params.append((pname, ptype_py, defval))

            functions.append(Member(
                name=member_name, kind="function", return_type=ret_type_py,
                params=params, doc="", is_static=False
            ))

    return NamespaceDef(name=name, doc=doc, variables=variables, functions=functions)


# ---------------------------------------------------------------------------
# Collect opaque types (Kis*, Ko*, etc.)
# ---------------------------------------------------------------------------

def collect_opaque_types(classes: list[ClassDef],
                         namespaces: list[NamespaceDef]) -> set[str]:
    """Find all C++ internal types that are referenced but not defined as classes."""
    defined = {c.name for c in classes}
    defined |= {n.name for n in namespaces}
    defined |= set(QT_MODULES.keys())
    defined.add("Any")  # from typing

    # Always-declared opaque types (internal Krita C++ types used across classes)
    ALWAYS_OPAQUE = {
        "DockPosition", "Bicubic",
        "KisNodeList", "KisImageWSP", "KisFigurePaintingToolHelper",
        "KisNodeSP", "KisLayerSP", "KoCanvasBase", "KoChannelInfo",
        "KisImage", "KisImageSP", "KisCloneLayerSP", "KisDocument",
        "KisFileLayerSP", "KisColorizeMaskSP", "KisFilterMaskSP",
        "KisFilterConfigurationSP", "KisGeneratorLayerSP",
        "KisAdjustmentLayerSP", "KisGroupLayerSP", "KisShapeGroupSP",
        "KoShapeGroup", "KoColor", "KoResourceSP",
        "KisPropertiesConfigurationSP", "KisSelectionSP",
        "KisSelectionMaskSP", "KoShape", "KisTransformMaskSP",
        "KisTransparencyMaskSP", "KoShapeControllerBase", "KisView",
        "KisShapeLayerSP", "KisMainWindow", "KoCanvasObserverBase",
        "KoDockFactoryBase", "KisPresetChooser", "KisGridConfig",
        "KisGuidesConfig",
    }

    opaque: set[str] = set()
    pattern = re.compile(r'\b([A-Z][A-Za-z0-9_]+)\b')

    def scan(text: str) -> None:
        for m in pattern.finditer(text):
            word = m.group(1)
            if word not in defined and len(word) > 1:
                opaque.add(word)

    for cls in classes:
        for base in cls.bases:
            if base not in defined:
                opaque.add(base)
        for m in cls.members[:-1]:  # scan param/return types
            scan(m.return_type)
            for _, ptype, _ in (m.params or []):
                scan(ptype)

    # Filter: only keep types that look like Krita internals, plus always-needed ones
    detected = {t for t in opaque if t.startswith(("Kis", "Ko", "KUndo2"))}
    detected |= ALWAYS_OPAQUE
    return detected


# ---------------------------------------------------------------------------
# Topological sort
# ---------------------------------------------------------------------------

def topological_sort(classes: list[ClassDef]) -> list[ClassDef]:
    """Order classes so base classes come before their subclasses."""
    name_to_class = {c.name: c for c in classes}

    in_degree: dict[str, int] = {c.name: 0 for c in classes}
    children: dict[str, list[str]] = defaultdict(list)

    for cls in classes:
        for base in cls.bases:
            if base in name_to_class:
                in_degree[cls.name] += 1
                children[base].append(cls.name)

    # Start with classes that have no parent (zero in-degree), then priority bases
    queue: list[str] = [name for name, deg in in_degree.items() if deg == 0]
    # Move priority bases to front
    for pb in reversed(PRIORITY_BASES):
        if pb in queue:
            queue.remove(pb)
            queue.insert(0, pb)

    result: list[ClassDef] = []
    while queue:
        name = queue.pop(0)
        result.append(name_to_class[name])
        for child in children[name]:
            in_degree[child] -= 1
            if in_degree[child] == 0:
                queue.append(child)

    # Any remaining (cycles — shouldn't happen)
    for name, deg in in_degree.items():
        if deg > 0 and name not in [r.name for r in result]:
            result.append(name_to_class[name])

    return result


# ---------------------------------------------------------------------------
# Code generation
# ---------------------------------------------------------------------------

def _emit_param(pname: str, ptype: str, defval: str | None) -> str:
    """Format a single parameter for a method signature."""
    base = f"{pname}: {ptype}"
    if defval is not None:
        base += f" = {defval}"
    return base


def _emit_docstring(doc: str, level: int) -> str:
    """Emit a docstring block, or empty string if doc is empty."""
    if not doc.strip():
        return ""
    lines = ['"""', doc.rstrip(), '"""']
    return "\n".join(indent(line, level) for line in lines) + "\n"


def emit_method(member: Member, class_name: str = "") -> str:
    """Generate a single method definition for a .pyi stub."""
    parts: list[str] = []

    if member.kind == "signal":
        # Signal → ClassVar with trailing comment
        result = f"{member.name}: ClassVar[pyqtSignal]"
        if member.doc.strip():
            # Use a single-line comment for short doc, docstring for longer
            doc = member.doc.strip()
            if '\n' in doc:
                result += "\n" + _emit_docstring(doc, 0)
            else:
                result += f"  # {doc}"
        return result

    # Method or constructor
    if member.kind == "static_method":
        parts.append("@staticmethod")

    params_strs: list[str] = []
    if member.kind != "static_method":
        params_strs.append("self")
    for pname, ptype, defval in (member.params or []):
        params_strs.append(_emit_param(pname, ptype, defval))

    func_name = "__init__" if member.kind == "constructor" else member.name
    ret = f" -> {member.return_type}"
    sig = f"def {func_name}({', '.join(params_strs)}){ret}:"

    parts.append(sig)

    doc_block = _emit_docstring(member.doc, 1)
    if doc_block:
        parts.append(doc_block)

    parts.append(indent("...", 1))
    return "\n".join(parts)


def emit_overload_group(name: str, overloads: list[Member]) -> str:
    """Emit an @overload group for methods with the same name."""
    lines: list[str] = []
    for member in overloads:
        lines.append("@overload")
        params_strs = ["self"]
        for pname, ptype, defval in (member.params or []):
            params_strs.append(_emit_param(pname, ptype, defval))
        ret = f" -> {member.return_type}"
        lines.append(f"def {name}({', '.join(params_strs)}){ret}: ...")
        lines.append("")
    return "\n".join(lines).rstrip()


def emit_enum(enum_def: EnumDef) -> str:
    """Emit an IntEnum class for a C++ enum."""
    lines = [f"class {enum_def.name}(int):"]
    for val in enum_def.values:
        if val.value is not None:
            lines.append(f"    {val.name} = {val.value}")
        else:
            lines.append(f"    {val.name}: ClassVar[{enum_def.name}]")
    return "\n".join(lines)


def emit_class(cls: ClassDef, has_overloads: bool) -> str:
    """Generate a complete class definition for .pyi."""
    lines: list[str] = []

    # Class header
    bases_str = f"({', '.join(cls.bases)})" if cls.bases else ""
    lines.append(f"class {cls.name}{bases_str}:")

    # Class docstring
    if cls.doc.strip():
        lines.append(indent('"""', 1))
        lines.append(indent(cls.doc.rstrip(), 1))
        lines.append(indent('"""', 1))
        lines.append("")

    # Enums
    for enum in cls.enums:
        lines.append(indent(emit_enum(enum), 1))
        lines.append("")

    # Group methods by name to detect overloads
    by_name: dict[str, list[Member]] = defaultdict(list)
    for m in cls.members:
        by_name[m.name].append(m)

    def sort_key(name_members: tuple[str, list[Member]]) -> tuple[int, str]:
        name, _members = name_members
        # __init__ first
        if name == "__init__" or any(m.kind == "constructor" for m in _members):
            return (0, name)
        # signals last
        if all(m.kind == "signal" for m in _members):
            return (2, name)
        return (1, name)

    for name, group in sorted(by_name.items(), key=sort_key):
        non_signal = [m for m in group if m.kind != "signal"]
        signals_in_group = [m for m in group if m.kind == "signal"]

        if len(non_signal) > 1:
            # Overloaded methods
            lines.append(indent(emit_overload_group(name, non_signal), 1))
            lines.append("")
        elif len(non_signal) == 1:
            lines.append(indent(emit_method(non_signal[0], cls.name), 1))
            lines.append("")

        for sig in signals_in_group:
            lines.append(indent(emit_method(sig, cls.name), 1))
            lines.append("")

    result = "\n".join(lines).rstrip()

    # Qualify unqualified enum references
    # e.g. DialogType.OpenFile → FileDialog.DialogType.OpenFile
    # e.g. ClassVar[DialogType] → ClassVar[FileDialog.DialogType]
    for enum in cls.enums:
        for sep in (" ", "(", ","):
            result = result.replace(f"{sep}{enum.name}.", f"{sep}{cls.name}.{enum.name}.")
        result = result.replace(f"ClassVar[{enum.name}]", f"ClassVar[{cls.name}.{enum.name}]")

    return result


def emit_namespace(ns: NamespaceDef) -> str:
    """Generate the namespace section."""
    lines: list[str] = []
    lines.append(f"# {ns.name}")
    if ns.doc.strip():
        lines.append(f"# {ns.doc.strip()}")

    # Variables
    for vname, vtype in ns.variables:
        lines.append(f"{vname}: {vtype}")

    # Functions
    for func in ns.functions:
        params_strs = [
            _emit_param(pname, ptype, defval)
            for pname, ptype, defval in (func.params or [])
        ]
        ret = f" -> {func.return_type}"
        lines.append(f"def {func.name}({', '.join(params_strs)}){ret}: ...")

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Import collection
# ---------------------------------------------------------------------------

def collect_imports(classes: list[ClassDef], opaque: set[str]) -> str:
    """Build the import block dynamically based on what's used."""
    typing_imports: set[str] = set()

    # Check if overload is needed
    for cls in classes:
        by_name: dict[str, list[Member]] = defaultdict(list)
        for m in cls.members:
            if m.kind not in ("signal",):
                by_name[m.name].append(m)
        if any(len(v) > 1 for v in by_name.values()):
            typing_imports.add("overload")

    # Check if ClassVar is needed (signals)
    has_signals = any(m.kind == "signal" for c in classes for m in c.members)
    if has_signals:
        typing_imports.add("ClassVar")

    # Check if Any is used in types
    all_type_text = " ".join(
        m.return_type + " " + " ".join(pt for _, pt, _ in (m.params or []))
        for c in classes for m in c.members
    )
    if "Any" in all_type_text:
        typing_imports.add("Any")

    # Qt imports — only include what's actually referenced
    qt_imports: dict[str, set[str]] = defaultdict(set)
    for qt_type, module in QT_MODULES.items():
        if module.startswith("PyQt5"):
            if re.search(r'\b' + re.escape(qt_type) + r'\b', all_type_text):
                qt_imports[module].add(qt_type)
    # Also check class bases for QObject etc.
    for cls in classes:
        if cls.bases and "QObject" in str(cls.bases):
            if "PyQt5.QtCore" not in qt_imports:
                qt_imports["PyQt5.QtCore"] = set()
            qt_imports["PyQt5.QtCore"].add("QObject")
    # Signals need pyqtSignal
    if has_signals:
        qt_imports["PyQt5.QtCore"].add("pyqtSignal")

    lines: list[str] = []
    if typing_imports:
        lines.append(f"from typing import {', '.join(sorted(typing_imports))}")
    for module in sorted(qt_imports):
        names = sorted(qt_imports[module])
        if names:
            lines.append(f"from {module} import {', '.join(names)}")

    # Opaque types
    if opaque:
        lines.append("")
        lines.append("# Internal C++ types (opaque to Python)")
        for t in sorted(opaque):
            lines.append(f"class {t}: ...")

    return "\n".join(lines) + "\n\n"


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate krita.pyi from Doxygen XML documentation"
    )
    parser.add_argument(
        "--xml-dir", default="./xml",
        help="Directory containing Doxygen-generated XML files (default: ./xml)"
    )
    parser.add_argument(
        "--output", "-o", default="./krita.pyi",
        help="Output path for the .pyi file (default: ./krita.pyi)"
    )
    args = parser.parse_args()

    xml_dir = Path(args.xml_dir)
    if not xml_dir.is_dir():
        print(f"Error: XML directory not found: {xml_dir}", file=sys.stderr)
        sys.exit(1)

    output_path = Path(args.output)

    # Parse all class XML files
    class_files = sorted(xml_dir.glob("class_*.xml"))
    if not class_files:
        print(f"Error: No class_*.xml files found in {xml_dir}", file=sys.stderr)
        sys.exit(1)

    print(f"Found {len(class_files)} class XML files")

    classes: list[ClassDef] = []
    for fp in class_files:
        cdef = parse_class_xml(fp)
        if cdef:
            classes.append(cdef)
            print(f"  ✓ {cdef.name} ({len(cdef.members)} members)")

    # Parse namespace XML only for type reference collection (not output)
    namespace_files = sorted(xml_dir.glob("namespace_*.xml"))
    namespaces: list[NamespaceDef] = []
    for fp in namespace_files:
        ndef = parse_namespace_xml(fp)
        if ndef:
            namespaces.append(ndef)

    # Collect opaque types
    opaque = collect_opaque_types(classes, namespaces)

    # Topological sort
    ordered = topological_sort(classes)
    print(f"\nGenerating stub for {len(ordered)} classes…")

    # Generate output
    output_parts: list[str] = []

    # File header
    output_parts.append(
        "# Generated by build.py — DO NOT EDIT\n"
        "# Type stub for Krita scripting API (libkis)\n"
    )

    # Imports + opaque types
    output_parts.append(collect_imports(ordered, opaque))

    # Class definitions
    has_overloads = False  # determined during emit
    for cls in ordered:
        output_parts.append(emit_class(cls, has_overloads))
        output_parts.append("")

    result = "\n".join(output_parts)

    # Write
    output_path.write_text(result, encoding="utf-8")
    print(f"\n✓ Written to {output_path} ({len(result)} bytes)")


if __name__ == "__main__":
    main()
