# Generated by build.py — DO NOT EDIT

from typing import ClassVar, overload
from PyQt5.QtCore import Qt, pyqtSignal
from PyQt5.QtWidgets import QWidget


class AngleSelector:
    """
    A wrapper around KisAngleSelector, a widget with several options to select an angle. The widget itself is accessed with the `widget()` function.

    This widget is a combination of a KisAngleGauge and a spin box, along with some flipping options
    """

    def __init__(self) -> None:
        ...

    def angle(self) -> float:
        """
        Gets the current angle.

        :returns: The current angle

        See also: `setAngle(qreal)`
        """

        ...

    @overload
    def closestCoterminalAngleInRange(self, angle: float, minimum: float, maximum: float, ok: bool = None) -> float: ...

    @overload
    def closestCoterminalAngleInRange(self, angle: float, ok: bool = None) -> float: ...

    def decimals(self) -> int:
        """
        Gets the number of decimals (precision) used by the angle.

        If you want to simulate integer angles, set it to 0. The default is 2. :returns: The number of decimals being used

        See also: `setDecimals(int)`
        """

        ...

    def flip(self, orientations: Qt.Orientations) -> None:
        """
        Flips the angle horizontally, vertically, or both.

        This function will always try to set the closest angle to the stablished one that satisfies the flipping requirements

        :param orientations: Flags indicating in which directions the angle should be flipped
        """

        ...

    @overload
    def flipAngle(self, angle: float, orientations: Qt.Orientations) -> float: ...

    @overload
    def flipAngle(self, angle: float, minimum: float, maximum: float, orientations: Qt.Orientations, ok: bool = None) -> float: ...

    def flipOptionsMode(self) -> str:
        """
        Gets the mode in which the flip options should be shown.

        The default is Buttons :returns: The mode in which the flip options should be shown.

        See also: `setFlipOptionsMode(QString)`
        """

        ...

    def increasingDirection(self) -> str:
        """
        Gets the direction in which the angle increases in the angle gauge.

        :returns: The direction in which the angle increases

        See also: `setIncreasingDirection(QString)`
        """

        ...

    def isUsingFlatSpinBox(self) -> bool:
        """
        Gets if the spin box is flat (no border or background)

        :returns: True if the spin box is flat, false otherwise

        See also: `useFlatSpinBox(bool)`
        """

        ...

    def maximum(self) -> float:
        """
        Gets the maximum value for the angle.

        The default is 360 :returns: The maximum value for the angle

        See also: `setMaximum(qreal)`

        See also: `setRange(qreal, qreal)`
        """

        ...

    def minimum(self) -> float:
        """
        Gets the minimum value for the angle.

        The default is 0 :returns: The minimum value for the angle

        See also: `setMinimum(qreal)`

        See also: `setRange(qreal, qreal)`
        """

        ...

    def prefix(self) -> str:
        """
        Gets the prefix shown in the spin box.

        :returns: The prefix shown in the spin box

        See also: `setPrefix(const QString&)`
        """

        ...

    def reset(self) -> None:
        """
        Sets the current angle to the reset angle.

        See also: `resetAngle() const`

        See also: setResetAngle(qreal) const
        """

        ...

    def resetAngle(self) -> float:
        """
        Gets the angle that is used to reset the current angle.

        This angle is used when the user double clicks on the widget :returns: The angle that is used to reset the current angle

        See also: `setResetAngle(qreal)`
        """

        ...

    def setAngle(self, newAngle: float) -> None:
        """
        Sets the current angle.

        See also: `angle() const`

        :param newAngle: the new angle
        """

        ...

    def setDecimals(self, newNumberOfDecimals: int) -> None:
        """
        Sets the number of decimals (precision) used by the angle.

        See also: `decimals() const`

        :param newNumberOfDecimals: the new number of decimals used by the angle
        """

        ...

    def setFlipOptionsMode(self, newMode: str) -> None:
        """
        Sets the mode in which the flip options should be shown.

        :param newMode: the new mode in which the flip options should be shown Valid arguments: 

        - NoFlipOptions - There are no flip options available

        - MenuButton - The flip options are shown as a menu accessible via a options button

        - Buttons - The flip options are shown as individual buttons

        - ContextMenu - The flip options are shown only as a context menu when right-clicking the gauge widget 



        `flipOptionsMode() const`
        """

        ...

    def setIncreasingDirection(self, newIncreasingDirection: str) -> None:
        """
        Sets the increasing direction in the angle gauge.

        See also: `increasingDirection() const`

        :param newIncreasingDirection: The new increasing direction Valid arguments: CounterClockwise or Clockwise.
        """

        ...

    def setMaximum(self, newMaximum: float) -> None:
        """
        Sets the maximum value for the angle.

        See also: `maximum() const`

        See also: `setRange(qreal, qreal)`

        :param newMaximum: the new maximum value for the angle
        """

        ...

    def setMinimum(self, newMinimum: float) -> None:
        """
        Sets the minimum value for the angle.

        See also: `minimum() const`

        See also: `setRange(qreal, qreal)`

        :param newMinimum: the new minimum value for the angle
        """

        ...

    def setPrefix(self, newPrefix: str) -> None:
        """
        Sets the prefix shown in the spin box.

        See also: `prefix() const`

        :param newPrefix: the new prefix for the spin box
        """

        ...

    def setRange(self, newMinimum: float, newMaximum: float) -> None:
        """
        Sets the minimum and maximum values for the angle.

        See also: `minimum() const`

        See also: `maximum() const`

        See also: `setMinimum(qreal)`

        See also: `setMaximum(qreal)`

        :param newMinimum: the new minimum value for the angle
        :param newMaximum: the new maximum value for the angle
        """

        ...

    def setResetAngle(self, newResetAngle: float) -> None:
        """
        Sets the angle that is used to reset the current angle.

        See also: `resetAngle() const`

        :param newResetAngle: the new angle that is used to reset the current angle
        """

        ...

    def setSnapAngle(self, newSnapAngle: float) -> None:
        """
        Sets the angle to which multiples the selected angle will snap.

        See also: `snapAngle() const`

        :param newSnapAngle: the new angle to which multiples the selected angle will snap
        """

        ...

    def setWidgetsHeight(self, newHeight: int) -> None:
        """
        Sets the common height of the widgets inside this angle selector. Use 0 to reset widgets to default height.

        See also: `widgetsHeight() const`

        :param newHeight: the new height of the internal widgets (angle gauge, spin box, etc.)
        """

        ...

    def setWrapping(self, newWrapping: bool) -> None:
        """
        Sets if the angle should wrap pass the minimum or maximum angles.

        See also: `wrapping() const`

        :param newWrapping: true if the angle should wrap pass the minimum or maximum angles, false otherwise
        """

        ...

    def snapAngle(self) -> float:
        """
        Gets the angle to which multiples the selected angle will snap.

        The default snap angle is 15 degrees so the selected angle will snap to its multiples (0, 15, 30, 45, etc.) :returns: The angle to which multiples the selected angle will snap

        See also: `setSnapAngle(qreal)`
        """

        ...

    def useFlatSpinBox(self, newUseFlatSpinBox: bool) -> None:
        """
        Sets if the spin box should be flat.

        See also: `isUsingFlatSpinBox() const`

        :param newUseFlatSpinBox: True if the spin box should be flat, false otherwise
        """

        ...

    def widget(self) -> QWidget:
        """
        Get the internal KisAngleSelector as a QWidget, so it may be added to a UI.

        :returns: the internal KisAngleSelector as a QWidget
        """

        ...

    def widgetsHeight(self) -> int:
        """
        Gets the common height of the widgets inside this angle selector.

        :returns: The height of the internal widgets (angle gauge, spin box, etc.). Returns 0 if each widget has its default height.

        See also: `setWidgetsHeight(int)`
        """

        ...

    def wrapping(self) -> bool:
        """
        Gets if the angle should wrap pass the minimum or maximum angles.

        :returns: True if the angle should wrap pass the minimum or maximum angles, false otherwise

        See also: `setWrapping(bool)`
        """

        ...

    angleChanged: ClassVar[pyqtSignal]