# Generated by build.py — DO NOT EDIT

from PyQt5.QtCore import QObject, QPoint, QPointF
from krita._types._opaque import KoCanvasBase
from krita._types.view import View


class Canvas:
    """
    `Canvas` wraps the canvas inside a view on an image/document. It is responsible for the view parameters of the document: zoom, rotation, mirror, wraparound and instant preview.
    """

    def __init__(self, canvas: KoCanvasBase, parent: QObject = None) -> None:
        ...

    def levelOfDetailMode(self) -> bool:
        """
        :returns: true if the canvas is in Instant Preview mode, false if not. Only when OpenGL is enabled, is Instant Preview mode available.
        """

        ...

    def mirror(self) -> bool:
        """
        :returns: return true if the canvas is mirrored, false otherwise.
        """

        ...

    def pan(self, offset: QPoint) -> None:
        """
        pan the current view in pixels.
        """

        ...

    def preferredCenter(self) -> QPointF:
        """
        :returns: the position of the image pixel that is placed in the center of the current view
        """

        ...

    def resetRotation(self) -> None:
        """
        resetRotation reset the canvas rotation.
        """

        ...

    def resetZoom(self) -> None:
        """
        resetZoom set the zoomlevel to 100%
        """

        ...

    def rotation(self) -> float:
        """
        :returns: the rotation of the canvas in degrees.
        """

        ...

    def setLevelOfDetailMode(self, enable: bool) -> None:
        """
        setLevelOfDetailMode sets Instant Preview to
        """

        ...

    def setMirror(self, value: bool) -> None:
        """
        setMirror turn the canvas mirroring on or off depending on
        """

        ...

    def setPreferredCenter(self, imagePos: QPointF) -> None:
        """
        setPan Centers the image pixel at `imagePos` in the current view
        """

        ...

    def setRotation(self, angle: float) -> None:
        """
        setRotation set the rotation of the canvas to the given

        :param angle: in degrees.
        """

        ...

    def setWrapAroundMode(self, enable: bool) -> None:
        """
        setWrapAroundMode set wraparound mode to
        """

        ...

    def setZoomLevel(self, value: float) -> None:
        """
        setZoomLevel set the zoomlevel to the given `value`. 1.0 is 100%.
        """

        ...

    def view(self) -> View:
        """
        :returns: the view that holds this canvas
        """

        ...

    def wrapAroundMode(self) -> bool:
        """
        :returns: true if the canvas is in wraparound mode, false if not. Only when OpenGL is enabled, is wraparound mode available.
        """

        ...

    def zoomLevel(self) -> float:
        """
        :returns: the current zoomlevel. 1.0 is 100%.
        """

        ...