# Generated by build.py — DO NOT EDIT

from PyQt5.QtCore import QByteArray, QObject, QRect
from krita._types._opaque import KisNodeSP
from krita._types._opaque import KoChannelInfo


class Channel:
    """
    A `Channel` represents a single channel in a `Node`. `Krita` does not use channels to store local selections: these are strictly the color and alpha channels.
    """

    def __init__(self, node: KisNodeSP, channel: KoChannelInfo, parent: QObject = None) -> None:
        ...

    def bounds(self) -> QRect:
        """
        :returns: the exact bounds of the channel. This can be smaller than the bounds of the `Node` this channel is part of.
        """

        ...

    def channelSize(self) -> int:
        """
        :returns: the number of bytes this channel takes
        """

        ...

    def name(self) -> str:
        """
        :returns: the name of the channel
        """

        ...

    def pixelData(self, rect: QRect) -> QByteArray:
        """
        Read the values of the channel into the a byte array for each pixel in the rect from the `Node` this channel is part of, and returns it.


        Note that if `Krita` is built with OpenEXR and the `Node` has the 16 bits floating point channel depth type, `Krita` returns 32 bits float for every channel; the libkis scripting API does not support half.
        """

        ...

    def position(self) -> int:
        """
        :returns: the position of the first byte of the channel in the pixel
        """

        ...

    def setPixelData(self, value: QByteArray, rect: QRect) -> None:
        """
        setPixelData writes the given data to the relevant channel in the `Node`. This is only possible for Nodes that have a paintDevice, so nothing will happen when trying to write to e.g. a group layer.

        Note that if `Krita` is built with OpenEXR and the `Node` has the 16 bits floating point channel depth type, `Krita` expects to be given a 4 byte, 32 bits float for every channel; the libkis scripting API does not support half.

        :param value: a byte array with exactly enough bytes.
        :param rect: the rectangle to write the bytes into
        """

        ...

    def setVisible(self, value: bool) -> None:
        """
        setvisible set the visibility of the channel to the given value.
        """

        ...

    def visible(self) -> bool:
        """
        visible checks whether this channel is visible in the node

        :returns: the status of this channel
        """

        ...