# Generated by build.py — DO NOT EDIT

from typing import overload
from PyQt5.QtCore import QObject
from krita._types._opaque import KisCloneLayerSP
from krita._types._opaque import KisImageSP
from krita._types._opaque import KisLayerSP
from krita._types.node import Node


class CloneLayer(Node):
    """
    The `CloneLayer` class A clone layer is a layer that takes a reference inside the image and shows the exact same pixeldata.

    If the original is updated, the clone layer will update too.
    """

    @overload
    def CloneLayer(self, image: KisImageSP, name: str, source: KisLayerSP, parent: QObject = None) -> None: ...

    @overload
    def CloneLayer(self, layer: KisCloneLayerSP, parent: QObject = None) -> None: ...

    def setSourceNode(self, node: Node) -> None:
        """
        setSourceNode

        :param node: the node to use as the source of the clone layer.
        """

        ...

    def sourceNode(self) -> Node:
        """
        sourceNode

        :returns: the node the clone layer is based on.
        """

        ...

    def type(self) -> str:
        """
        type `Krita` has several types of nodes, split in layers and masks. Group layers can contain other layers, any layer can contain masks.

        :returns: clonelayer
        """

        ...