# Generated by build.py — DO NOT EDIT

from typing import overload
from PyQt5.QtCore import QByteArray, QObject
from krita._types._opaque import KisColorizeMaskSP
from krita._types._opaque import KisImageSP
from krita._types.managed_color import ManagedColor
from krita._types.node import Node


class ColorizeMask(Node):
    """
    The `ColorizeMask` class A colorize mask is a mask type node that can be used to color in line art.

    ```
    window = `Krita`.`instance`().`activeWindow`()
    doc = `Krita`.`instance`().`createDocument`(10, 3, "Test", "RGBA", "U8", "", 120.0)
    window.addView(doc)
    root = doc.`rootNode`();
    node = doc.createNode("layer", "paintLayer")
    root.`addChildNode`(node, None)
    nodeData = QByteArray.fromBase64(b"AAAAAAAAAAAAAAAAEQYMBhEGDP8RBgz/EQYMAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARBgz5EQYM/xEGDAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEQYMAhEGDAkRBgwCAAAAAAAAAAAAAAAA");
    node.setPixelData(nodeData,0,0,10,3)

    cols = [ `ManagedColor`('RGBA','U8',''), `ManagedColor`('RGBA','U8','') ]
    cols[0].setComponents([0.65490198135376, 0.345098048448563, 0.474509805440903, 1.0]);
    cols[1].setComponents([0.52549022436142, 0.666666686534882, 1.0, 1.0]);
    keys = [
            QByteArray.fromBase64(b"/48AAAAAAAAAAAAAAAAAAAAAAACmCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"),
            QByteArray.fromBase64(b"AAAAAAAAAACO9ocAAAAAAAAAAAAAAAAAAAAAAMD/uQAAAAAAAAAAAAAAAAAAAAAAGoMTAAAAAAAAAAAA")
            ]

    mask = doc.createColorizeMask('c1')
    node.addChildNode(mask,None)
    mask.setEditKeyStrokes(True)

    mask.setUseEdgeDetection(True)
    mask.setEdgeDetectionSize(4.0)
    mask.setCleanUpAmount(70.0)
    mask.setLimitToDeviceBounds(True)
    mask.initializeKeyStrokeColors(cols)

    for col,key in zip(cols,keys):
        mask.`setKeyStrokePixelData`(key,col,0,0,20,3)

    mask.`updateMask`()
    mask.`setEditKeyStrokes`(False);
    mask.setShowOutput(True);
    ```
    """

    @overload
    def ColorizeMask(self, image: KisImageSP, name: str, parent: QObject = None) -> None: ...

    @overload
    def ColorizeMask(self, image: KisImageSP, mask: KisColorizeMaskSP, parent: QObject = None) -> None: ...

    def cleanUpAmount(self) -> float:
        """
        cleanUpAmount

        :returns: a float value of 0.0 to 100.0 representing the cleanup amount where 0.0 is no cleanup is done and 100.00 is most aggressive.
        """

        ...

    def edgeDetectionSize(self) -> float:
        """
        edgeDetectionSize

        :returns: a float value of the edge detection size in pixels.
        """

        ...

    def editKeyStrokes(self) -> bool:
        """
        editKeyStrokes Edit keystrokes mode allows the user to modify keystrokes on the active Colorize Mask.

        :returns: true if edit keystrokes mode is enabled, false if disabled.
        """

        ...

    def initializeKeyStrokeColors(self, colors: list[ManagedColor], transparentIndex: int = -1) -> None:
        """
        initializeKeyStrokeColors Set the colors to use for the Colorize Mask's keystrokes.

        :param colors: a list of `ManagedColor` to use for the keystrokes.
        :param transparentIndex: index of the color that should be marked as transparent.
        """

        ...

    def keyStrokePixelData(self, color: ManagedColor, x: int, y: int, w: int, h: int) -> QByteArray:
        """
        keyStrokePixelData reads the given rectangle from the keystroke image data and returns it as a byte array. The pixel data starts top-left, and is ordered row-first.

        :returns: a QByteArray with the pixel data. The byte array may be empty.

        :param color: a `ManagedColor` to get keystrokes pixeldata from.
        :param x: x position from where to start reading
        :param y: y position from where to start reading
        :param w: row length to read
        :param h: number of rows to read
        """

        ...

    def keyStrokesColors(self) -> list[ManagedColor]:
        """
        keyStrokesColors Colors used in the Colorize Mask's keystrokes.

        :returns: a `ManagedColor` list containing the colors of keystrokes.
        """

        ...

    def limitToDeviceBounds(self) -> bool:
        """
        limitToDeviceBounds

        :returns: true if limit bounds is enabled, false if disabled.
        """

        ...

    def removeKeyStroke(self, color: ManagedColor) -> None:
        """
        removeKeyStroke Remove a color from the Colorize Mask's keystrokes.

        :param color: a `ManagedColor` to be removed from the keystrokes.
        """

        ...

    def resetCache(self) -> None:
        ...

    def setCleanUpAmount(self, value: float) -> None:
        """
        setCleanUpAmount This will attempt to handle messy strokes that overlap the line art where they shouldn't.

        :param value: a float value from 0.0 to 100.00 where 0.0 is no cleanup is done and 100.00 is most aggressive.
        """

        ...

    def setEdgeDetectionSize(self, value: float) -> None:
        """
        setEdgeDetectionSize Set the value to the thinnest line on the image.

        :param value: a float value of the edge size to detect in pixels.
        """

        ...

    def setEditKeyStrokes(self, enabled: bool) -> None:
        """
        setEditKeyStrokes Toggle Colorize Mask's edit keystrokes mode.

        :param enabled: set true to enable edit keystrokes mode and false to disable it.
        """

        ...

    def setKeyStrokePixelData(self, value: QByteArray, color: ManagedColor, x: int, y: int, w: int, h: int) -> bool:
        """
        setKeyStrokePixelData writes the given bytes, of which there must be enough, into the keystroke, the keystroke's original pixels are overwritten

        :returns: true if writing the pixeldata worked

        :param value: the byte array representing the pixels. There must be enough bytes available. `Krita` will take the raw pointer from the QByteArray and start reading, not stopping before (number of channels * size of channel * w * h) bytes are read.
        :param color: a `ManagedColor` to set keystrokes pixeldata for.
        :param x: the x position to start writing from
        :param y: the y position to start writing from
        :param w: the width of each row
        :param h: the number of rows to write
        """

        ...

    def setLimitToDeviceBounds(self, value: bool) -> None:
        """
        setLimitToDeviceBounds Limit the colorize mask to the combined layer bounds of the strokes and the line art it is filling. This can speed up the use of the mask on complicated compositions, such as comic pages.

        :param value: set true to enabled limit bounds, false to disable.
        """

        ...

    def setShowOutput(self, enabled: bool) -> None:
        """
        setShowOutput Toggle Colorize Mask's show output mode.

        :param enabled: set true to enable show coloring mode and false to disable it.
        """

        ...

    def setUseEdgeDetection(self, value: bool) -> None:
        """
        setUseEdgeDetection Activate this for line art with large solid areas, for example shadows on an object.

        :param value: true to enable edge detection, false to disable.
        """

        ...

    def showOutput(self) -> bool:
        """
        showOutput Show output mode allows the user to see the result of the Colorize Mask's algorithm.

        :returns: true if edit show coloring mode is enabled, false if disabled.
        """

        ...

    def transparencyIndex(self) -> int:
        """
        transparencyIndex Index of the transparent color.

        :returns: an integer containing the index of the current color marked as transparent.
        """

        ...

    def type(self) -> str:
        """
        type `Krita` has several types of nodes, split in layers and masks. Group layers can contain other layers, any layer can contain masks.

        :returns: colorizemask
        If the `Node` object isn't wrapping a valid `Krita` layer or mask object, and empty string is returned.
        """

        ...

    def updateMask(self, force: bool = False) -> None:
        """
        updateMask Process the Colorize Mask's keystrokes and generate a projection of the computed colors.

        :param force: force an update
        """

        ...

    def useEdgeDetection(self) -> bool:
        """
        useEdgeDetection

        :returns: true if Edge detection is enabled, false if disabled.
        """

        ...