# Generated by build.py — DO NOT EDIT

from krita._types._opaque import KoCanvasObserverBase


class DockWidget(KoCanvasObserverBase):
    """
    `DockWidget` is the base class for custom Dockers. Dockers are created by a factory class which needs to be registered by calling Application.addDockWidgetFactory:


    ```
    class HelloDocker(DockWidget):
      def __init__(self):
          super().__init__()
          label = QLabel("Hello", self)
          self.setWidget(label)
          self.label = label
          self.setWindowTitle("Hello Docker")

    def canvasChanged(self, canvas):
          self.label.setText("Hellodocker: canvas changed");

    Application.addDockWidgetFactory(DockWidgetFactory("hello", DockWidgetFactoryBase.DockRight, HelloDocker))
    ```


    One docker per window will be created, not one docker per canvas or view. When the user switches between views/canvases, canvasChanged will be called. You can override that method to reset your docker's internal state, if necessary.
    """

    def __init__(self) -> None:
        ...