# Generated by build.py — DO NOT EDIT

from krita._types._opaque import DockPosition
from krita._types._opaque import KoDockFactoryBase


class DockWidgetFactoryBase(KoDockFactoryBase):
    """
    The `DockWidgetFactoryBase` class is the base class for plugins that want to add a dock widget to every window. You do not need to implement this class yourself, but create a `DockWidget` implementation and then add the DockWidgetFactory to the `Krita` instance like this:

    ```
    class HelloDocker(DockWidget):
      def __init__(self):
          super().__init__()
          label = QLabel("Hello", self)
          self.setWidget(label)
          self.label = label

    def canvasChanged(self, canvas):
          self.label.setText("Hellodocker: canvas changed");

    Application.addDockWidgetFactory(DockWidgetFactory("hello", DockWidgetFactoryBase.DockRight, HelloDocker))
    ```
    """

    def __init__(self, _id: str, _dockPosition: DockPosition) -> None:
        ...

    def defaultDockPosition(self) -> DockPosition:
        ...

    def id(self) -> str:
        ...