# Generated by build.py — DO NOT EDIT

from typing import overload
from PyQt5.QtCore import QByteArray, QObject, QRect, QUuid
from PyQt5.QtGui import QColor, QImage
from krita._types._opaque import KisDocument
from krita._types.clone_layer import CloneLayer
from krita._types.colorize_mask import ColorizeMask
from krita._types.file_layer import FileLayer
from krita._types.fill_layer import FillLayer
from krita._types.filter import Filter
from krita._types.filter_layer import FilterLayer
from krita._types.filter_mask import FilterMask
from krita._types.grid_config import GridConfig
from krita._types.group_layer import GroupLayer
from krita._types.guides_config import GuidesConfig
from krita._types.info_object import InfoObject
from krita._types.node import Node
from krita._types.selection import Selection
from krita._types.selection_mask import SelectionMask
from krita._types.transform_mask import TransformMask
from krita._types.transparency_mask import TransparencyMask
from krita._types.vector_layer import VectorLayer


class Document:
    """
    The `Document` class encapsulates a `Krita` Document/Image. A `Krita` document is an Image with a filename. Libkis does not differentiate between a document and an image, like `Krita` does internally.
    """

    def __init__(self, document: KisDocument, ownsDocument: bool, parent: QObject = None) -> None:
        ...

    def activeNode(self) -> Node:
        """
        activeNode retrieve the node that is currently active in the currently active window

        :returns: the active node. If there is no active window, the first child node is returned.
        """

        ...

    def animationLength(self) -> int:
        """
        get total frame range for animation

        :returns: total frame range for animation
        """

        ...

    def annotation(self, type: str) -> QByteArray:
        """
        annotation the actual data for the annotation for this type. It's a simple QByteArray, what's in it depends on the type of the annotation

        :returns: a bytearray, possibly empty if this type of annotation doesn't exist

        :param type: the type of the annotation
        """

        ...

    def annotationDescription(self, type: str) -> str:
        """
        annotationDescription gets the pretty description for the current annotation

        :returns: a string that can be presented to the user

        :param type: the type of the annotation
        """

        ...

    def annotationTypes(self) -> list[str]:
        """
        annotationTypes returns the list of annotations present in the document. Each annotation type is unique.
        """

        ...

    def audioLevel(self) -> float:
        """
        Return current audio level for document.

        :returns: A value between 0.0 and 1.0 (1.0 = 100%)
        """

        ...

    def audioTracks(self) -> list[str]:
        """
        Return a list of current audio tracks for document.

        :returns: List of absolute path/file name of audio files
        """

        ...

    def autosave(self) -> bool:
        """
        Return autosave status for document Notes:

        - returned value is Autosave flag value Even if autosave is set to True, under condition `Krita` will not proceed to automatic save of document:

        - autosave is globally deactivated
        - document is read-only
        - When autosave is set to False, `Krita` never execute automatic save for document


        :returns: True if autosave is active, otherwise False
        """

        ...

    def backgroundColor(self) -> QColor:
        """
        backgroundColor returns the current background color of the document. The color will also include the opacity.

        :returns: QColor
        """

        ...

    def batchmode(self) -> bool:
        """
        Batchmode means that no actions on the document should show dialogs or popups. :returns: true if the document is in batchmode.
        """

        ...

    def bounds(self) -> QRect:
        """
        bounds return the bounds of the image

        :returns: the bounds
        """

        ...

    def clone(self) -> Document:
        """
        clone create a shallow clone of this document.

        :returns: a new `Document` that should be identical to this one in every respect.
        """

        ...

    def close(self) -> bool:
        """
        close Close the document: remove it from `Krita`'s internal list of documents and close all views. If the document is modified, you should save it first. There will be no prompt for saving.

        After closing the document it becomes invalid.


        :returns: true if the document is closed.
        """

        ...

    def colorDepth(self) -> str:
        """
        colorDepth A string describing the color depth of the image: 

        - U8: unsigned 8 bits integer, the most common type

        - U16: unsigned 16 bits integer

        - F16: half, 16 bits floating point. Only available if `Krita` was built with OpenEXR

        - F32: 32 bits floating point


        :returns: the color depth.
        """

        ...

    def colorModel(self) -> str:
        """
        colorModel retrieve the current color model of this document:

        - A: Alpha mask

        - RGBA: RGB with alpha channel (The actual order of channels is most often BGR!)

        - XYZA: XYZ with alpha channel

        - LABA: LAB with alpha channel

        - CMYKA: CMYK with alpha channel

        - GRAYA: Gray with alpha channel

        - YCbCrA: YCbCr with alpha channel


        :returns: the internal color model string.
        """

        ...

    def colorProfile(self) -> str:
        """
        :returns: the name of the current color profile
        """

        ...

    def createCloneLayer(self, name: str, source: Node) -> CloneLayer:
        """
        createCloneLayer

        :returns:
        """

        ...

    def createColorizeMask(self, name: str) -> ColorizeMask:
        """
        createColorizeMask Creates a colorize mask, which can be used to color fill via keystrokes.

        :returns: a `TransparencyMask`

        :param name: - the name of the layer.
        """

        ...

    def createFileLayer(self, name: str, fileName: str, scalingMethod: str, scalingFilter: str = 'Bicubic') -> FileLayer:
        """
        createFileLayer returns a layer that shows an external image.

        :returns: a `FileLayer`

        :param name: name of the file layer.
        :param fileName: the absolute filename of the file referenced. Symlinks will be resolved.
        :param scalingMethod: how the dimensions of the file are interpreted can be either "None", "ImageToSize" or "ImageToPPI"
        :param scalingFilter: filter used to scale the file can be "Bicubic", "Hermite", "NearestNeighbor", "Bilinear", "Bell", "BSpline", "Lanczos3", "Mitchell"
        """

        ...

    def createFillLayer(self, name: str, generatorName: str, configuration: InfoObject, selection: Selection) -> FillLayer:
        """
        createFillLayer creates a fill layer object, which is a layer

        :returns: a filllayer object.

        ```
        from krita import *
        d = Krita.instance().activeDocument()
        i = InfoObject();
        i.setProperty("pattern", "Cross01.pat")
        s = `Selection`();
        s.select(0, 0, d.width(), d.height(), 255)
        n = d.createFillLayer("test", "pattern", i, s)
        r = d.rootNode();
        c = r.childNodes();
        r.addChildNode(n, c[0])
        d.refreshProjection()
        ```

        :param generatorName: - name of the generation filter.
        :param configuration: - the configuration for the generation filter.
        :param selection: - the selection.
        """

        ...

    def createFilterLayer(self, name: str, filter: Filter, selection: Selection) -> FilterLayer:
        """
        createFilterLayer creates a filter layer, which is a layer that represents a filter applied non-destructively.

        :returns: a filter layer object.

        :param name: name of the filterLayer
        :param filter: the filter that this filter layer will us.
        :param selection: the selection.
        """

        ...

    @overload
    def createFilterMask(self, name: str, filter: Filter, selection: Selection) -> FilterMask: ...

    @overload
    def createFilterMask(self, name: str, filter: Filter, selection_source: Node) -> FilterMask: ...

    def createGroupLayer(self, name: str) -> GroupLayer:
        """
        createGroupLayer Returns a grouplayer object. Grouplayers are nodes that can have other layers as children and have the passthrough mode.

        :returns: a `GroupLayer` object.

        :param name: the name of the layer.
        """

        ...

    def createNode(self, name: str, nodeType: str) -> Node:
        """
        createNode create a new node of the given type. The node is not added
           to the node hierarchy; you need to do that by finding the right parent node,
           getting its list of child nodes and adding the node in the right place, then
           calling Node::SetChildNodes

           @param name The name of the node

           @param nodeType The type of the node. Valid types are:
           <ul>
            <li>paintlayer
            <li>grouplayer
            <li>filelayer
            <li>filterlayer
            <li>filllayer
            <li>clonelayer
            <li>vectorlayer
            <li>transparencymask
            <li>filtermask
            <li>transformmask
            <li>selectionmask
           </ul>

           When relevant, the new Node will have the colorspace of the image by default;
           that can be changed with Node::setColorSpace.

           The settings and selections for relevant layer and mask types can also be set
           after the Node has been created.

        ```
        d = Application.createDocument(1000, 1000, "Test", "RGBA", "U8", "", 120.0)
        root = d.rootNode();
        print(root.childNodes())
        l2 = d.`createNode`("layer2", "paintLayer")
        print(l2)
        root.addChildNode(l2, None)
        print(root.childNodes())
        ```


        :returns: the new `Node`.
        """

        ...

    def createSelectionMask(self, name: str) -> SelectionMask:
        """
        createSelectionMask Creates a selection mask, which can be used to store selections.

        :returns: a `SelectionMask`

        :param name: - the name of the layer.
        """

        ...

    def createTransformMask(self, name: str) -> TransformMask:
        """
        createTransformMask Creates a transform mask, which can be used to apply a transformation non-destructively.

        :returns: a `TransformMask`

        :param name: - the name of the layer mask.
        """

        ...

    def createTransparencyMask(self, name: str) -> TransparencyMask:
        """
        createTransparencyMask Creates a transparency mask, which can be used to assign transparency to regions.

        :returns: a `TransparencyMask`

        :param name: - the name of the layer.
        """

        ...

    def createVectorLayer(self, name: str) -> VectorLayer:
        """
        createVectorLayer Creates a vector layer that can contain vector shapes.

        :returns: a `VectorLayer`.

        :param name: the name of this layer.
        """

        ...

    def crop(self, x: int, y: int, w: int, h: int) -> None:
        """
        crop the image to rectangle described by `x`, `y`, `w` and `h`

        :param x: x coordinate of the top left corner
        :param y: y coordinate of the top left corner
        :param w: width
        :param h: height
        """

        ...

    def currentTime(self) -> int:
        """
        get current frame selected of animation

        :returns: current frame selected of animation
        """

        ...

    def documentInfo(self) -> str:
        """
        documentInfo creates and XML document representing document and author information.

        :returns: a string containing a valid XML document with the right information about the document and author. The DTD can be found here:
        [https://phabricator.kde.org/source/krita/browse/master/krita/dtd/](https://phabricator.kde.org/source/krita/browse/master/krita/dtd/)


        ```
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE document-info PUBLIC '-//KDE//DTD document-info 1.1//EN' 'http://www.calligra.org/DTD/document-info-1.1.dtd'>
        <document-info xmlns="http://www.calligra.org/DTD/document-info">
        <about>
         <title>My `Document`</title>
          <description></description>
          <subject></subject>
          <abstract><![CDATA[]]></abstract>
          <keyword></keyword>
          <initial-creator>Unknown</initial-creator>
          <editing-cycles>1</editing-cycles>
          <editing-time>35</editing-time>
          <date>2017-02-27T20:15:09</date>
          <creation-date>2017-02-27T20:14:33</creation-date>
          <language></language>
         </about>
         <author>
          <full-`name`>Boudewijn Rempt</full-`name`>
          <initial></initial>
          <author-title></author-title>
          <email></email>
          <telephone></telephone>
          <telephone-work></telephone-work>
          <fax></fax>
          <country></country>
          <postal-code></postal-code>
          <city></city>
          <street></street>
          <position></position>
          <company></company>
         </author>
        </document-info>
        ```
        """

        ...

    def exportImage(self, filename: str, exportConfiguration: InfoObject) -> bool:
        """
        exportImage export the image, without changing its URL to the given path.

        The supported formats have specific configurations that must be used when in batchmode. They are described below:


        `png` 

        - alpha: bool (True or False)

        - compression: int (1 to 9)

        - forceSRGB: bool (True or False)

        - indexed: bool (True or False)

        - interlaced: bool (True or False)

        - saveSRGBProfile: bool (True or False)

        - transparencyFillcolor: rgb (Ex:[255,255,255])


        `jpeg` 

        - baseline: bool (True or False)

        - exif: bool (True or False)

        - filters: bool (['ToolInfo', 'Anonymizer'])

        - forceSRGB: bool (True or False)

        - iptc: bool (True or False)

        - is_sRGB: bool (True or False)

        - optimize: bool (True or False)

        - progressive: bool (True or False)

        - quality: int (0 to 100)

        - saveProfile: bool (True or False)

        - smoothing: int (0 to 100)

        - subsampling: int (0 to 3)

        - transparencyFillcolor: rgb (Ex:[255,255,255])

        - xmp: bool (True or False)


        :returns: true if the export succeeded, false if it failed.

        :param filename: the full path to which the image is to be saved
        :param exportConfiguration: a configuration object appropriate to the file format. An `InfoObject` will used to that configuration.
        """

        ...

    def fileName(self) -> str:
        """
        :returns: the full path to the document, if it has been set.
        """

        ...

    def flatten(self) -> None:
        """
        flatten all layers in the image
        """

        ...

    def framesPerSecond(self) -> int:
        """
        frames per second of document

        :returns: the fps of the document
        """

        ...

    def fullClipRangeEndTime(self) -> int:
        """
        get the full clip range end time

        :returns: full clip range end time
        """

        ...

    def fullClipRangeStartTime(self) -> int:
        """
        get the full clip range start time

        :returns: full clip range start time
        """

        ...

    def gridConfig(self) -> GridConfig:
        """
        Returns a `GridConfig` grid configuration for current document.

        :returns: a `GridConfig` object with grid configuration
        """

        ...

    def guidesConfig(self) -> GuidesConfig:
        """
        Returns a `GuidesConfig` guides configuration for current document.

        :returns: a `GuidesConfig` object with guides configuration
        """

        ...

    def guidesLocked(self) -> bool:
        """
        DEPRECATED - use `guidesConfig()` instead Returns guide lockedness.

        :returns: whether the guides are locked.
        """

        ...

    def guidesVisible(self) -> bool:
        """
        DEPRECATED - use `guidesConfig()` instead Returns guide visibility.

        :returns: whether the guides are visible.
        """

        ...

    def height(self) -> int:
        """
        :returns: the height of the image in pixels
        """

        ...

    def horizontalGuides(self) -> list[float]:
        """
        DEPRECATED - use `guidesConfig()` instead The horizontal guides.

        :returns: a list of the horizontal positions of guides.
        """

        ...

    def importAnimation(self, files: list[str], firstFrame: int, step: int) -> bool:
        """
        Import an image sequence of files from a directory. This will grab all images from the directory and import them with a potential offset (firstFrame) and step (images on 2s, 3s, etc)

        :returns: whether the animation import was successful
        """

        ...

    def lock(self) -> None:
        """
        [low-level] Lock the image without waiting for all the internal job queues are processed


        WARNING: Don't use it unless you really know what you are doing! Use barrierLock() instead!


        Waits for all the `currently running` internal jobs to complete and locks the image for writing. Please note that this function does `not` wait for all the internal queues to process, so there might be some non-finished actions pending. It means that you just postpone these actions until you `unlock()` the image back. Until then, then image might easily be frozen in some inconsistent state.


        The only sane usage for this function is to lock the image for `emergency` processing, when some internal action or scheduler got hung up, and you just want to fetch some data from the image without races.


        In all other cases, please use barrierLock() instead!
        """

        ...

    def modified(self) -> bool:
        """
        modified returns true if the document has unsaved modifications.
        """

        ...

    def name(self) -> str:
        """
        :returns: the name of the document. This is the title field in the `documentInfo`
        """

        ...

    def nodeByName(self, name: str) -> Node:
        """
        nodeByName searches the node tree for a node with the given name and returns it

        :returns: the first node with the given name or 0 if no node is found

        :param name: the name of the node
        """

        ...

    def nodeByUniqueID(self, id: QUuid) -> Node:
        """
        nodeByUniqueID searches the node tree for a node with the given name and returns it.

        :returns: the node with the given unique id, or 0 if no node is found.

        :param uuid: the unique id of the node
        """

        ...

    def pixelData(self, x: int, y: int, w: int, h: int) -> QByteArray:
        """
        pixelData reads the given rectangle from the image projection and returns it as a byte array. The pixel data starts top-left, and is ordered row-first.

        The byte array can be interpreted as follows: 8 bits images have one byte per channel, and as many bytes as there are channels. 16 bits integer images have two bytes per channel, representing an unsigned short. 16 bits float images have two bytes per channel, representing a half, or 16 bits float. 32 bits float images have four bytes per channel, representing a float.


        You can read outside the image boundaries; those pixels will be transparent black.


        The order of channels is:


        - Integer RGBA: Blue, Green, Red, Alpha

        - Float RGBA: Red, Green, Blue, Alpha

        - LabA: L, a, b, Alpha

        - CMYKA: Cyan, Magenta, Yellow, Key, Alpha

        - XYZA: X, Y, Z, A

        - YCbCrA: Y, Cb, Cr, Alpha


        The byte array is a copy of the original image data. In Python, you can use bytes, bytearray and the struct module to interpret the data and construct, for instance, a Pillow Image object.


        :returns: a QByteArray with the pixel data. The byte array may be empty.

        :param x: x position from where to start reading
        :param y: y position from where to start reading
        :param w: row length to read
        :param h: number of rows to read
        """

        ...

    def playBackEndTime(self) -> int:
        """
        get end time of current playback

        :returns: end time of current playback
        """

        ...

    def playBackStartTime(self) -> int:
        """
        get start time of current playback

        :returns: start time of current playback
        """

        ...

    def projection(self, x: int = 0, y: int = 0, w: int = 0, h: int = 0) -> QImage:
        """
        projection creates a QImage from the rendered image or a cutout rectangle.
        """

        ...

    def refreshProjection(self) -> None:
        """
        Starts a synchronous recomposition of the projection: everything will wait until the image is fully recomputed.
        """

        ...

    def removeAnnotation(self, type: str) -> None:
        """
        removeAnnotation remove the specified annotation from the image

        :param type: the type defining the annotation
        """

        ...

    def resizeImage(self, x: int, y: int, w: int, h: int) -> None:
        """
        resizeImage resizes the canvas to the given left edge, top edge, width and height. Note: This doesn't scale, use scale image for that.

        :param x: the new left edge
        :param y: the new top edge
        :param w: the new width
        :param h: the new height
        """

        ...

    def resolution(self) -> int:
        """
        :returns: the resolution in pixels per inch
        """

        ...

    def rootNode(self) -> Node:
        """
        rootNode the root node is the invisible group layer that contains the entire node hierarchy.

        :returns: the root of the image
        """

        ...

    def rotateImage(self, radians: float) -> None:
        """
        rotateImage Rotate the image by the given radians.

        :param radians: the amount you wish to rotate the image in radians
        """

        ...

    def save(self) -> bool:
        """
        save the image to its currently set path. The modified flag of the document will be reset

        :returns: true if saving succeeded, false otherwise.
        """

        ...

    def saveAs(self, filename: str) -> bool:
        """
        saveAs save the document under the `filename`. The document's filename will be reset to `filename`.

        :returns: true if saving succeeded, false otherwise.

        :param filename: the new filename (full path) for the document
        """

        ...

    def scaleImage(self, w: int, h: int, xres: int, yres: int, strategy: str) -> None:
        """
        scaleImage

        :param w: the new width
        :param h: the new height
        :param xres: the new xres
        :param yres: the new yres
        :param strategy: the scaling strategy. There's several ones amongst these that aren't available in the regular UI. The list of filters is extensible and can be retrieved with `Krita::filter` 

        - Hermite

        - Bicubic - Adds pixels using the color of surrounding pixels. Produces smoother tonal gradations than Bilinear.

        - Box - Replicate pixels in the image. Preserves all the original detail, but can produce jagged effects.

        - Bilinear - Adds pixels averaging the color values of surrounding pixels. Produces medium quality results when the image is scaled from half to two times the original size.

        - Bell

        - BSpline

        - Kanczos3 - Offers similar results than Bicubic, but maybe a little bit sharper. Can produce light and dark halos along strong edges.

        - Mitchell
        """

        ...

    def selection(self) -> Selection:
        """
        selection Create a `Selection` object around the global selection, if there is one.

        :returns: the global selection or None if there is no global selection.
        """

        ...

    def setActiveNode(self, value: Node) -> None:
        """
        setActiveNode make the given node active in the currently active view and window

        :param value: the node to make active.
        """

        ...

    def setAnnotation(self, type: str, description: str, annotation: QByteArray) -> None:
        """
        setAnnotation Add the given annotation to the document

        :param type: the unique type of the annotation
        :param description: the user-visible description of the annotation
        :param annotation: the annotation itself
        """

        ...

    def setAudioLevel(self, level: float) -> None:
        """
        Set current audio level for document.

        :param level: Audio volume between 0.0 and 1.0 (1.0 = 100%)
        """

        ...

    def setAudioTracks(self, files: list[str]) -> bool:
        """
        Set a list of audio tracks for document Note: the function allows to add more than one file while from `Krita`'s UI, importing a file will replace the complete list.

        The reason why this method let the ability to provide more than one file is related to the internal's `Krita` method from KisDocument class: void KisDocument::setAudioTracks(QVector<QFileInfo> f)


        :returns: True if all files from list have been added, otherwise False (a file was not found)

        :param files: List of absolute path/file name of audio files
        """

        ...

    def setAutosave(self, active: bool) -> None:
        """
        Allow to activate/deactivate autosave for document When activated, it will use default `Krita` autosave settings It means that even when autosave is set to True, under condition `Krita` will not proceed to automatic save of document:

        - autosave is globally deactivated
        - document is read-only


        Being able to deactivate autosave on a document can make sense when a plugin use internal document (document is not exposed in a view, only created for internal process purposes)

        :param active: True to activate autosave
        """

        ...

    def setBackgroundColor(self, color: QColor) -> bool:
        """
        setBackgroundColor sets the background color of the document. It will trigger a projection update.

        :returns: bool

        :param color: A QColor. The color will be converted from sRGB.
        """

        ...

    def setBatchmode(self, value: bool) -> None:
        """
        Set batchmode to `value`. If batchmode is true, then there should be no popups or dialogs shown to the user.
        """

        ...

    def setColorProfile(self, colorProfile: str) -> bool:
        """
        setColorProfile set the color profile of the image to the given profile. The profile has to be registered with krita and be compatible with the current color model and depth; the image data is `not` converted.

        :returns: false if the colorProfile name does not correspond to to a registered profile or if assigning the profile failed.
        """

        ...

    def setColorSpace(self, colorModel: str, colorDepth: str, colorProfile: str) -> bool:
        """
        setColorSpace convert the nodes and the image to the given colorspace. The conversion is done with Perceptual as intent, High Quality and No LCMS Optimizations as flags and no blackpoint compensation.

        :returns: false the combination of these arguments does not correspond to a colorspace.

        :param colorModel: A string describing the color model of the image: 

        - A: Alpha mask

        - RGBA: RGB with alpha channel (The actual order of channels is most often BGR!)

        - XYZA: XYZ with alpha channel

        - LABA: LAB with alpha channel

        - CMYKA: CMYK with alpha channel

        - GRAYA: Gray with alpha channel

        - YCbCrA: YCbCr with alpha channel
        :param colorDepth: A string describing the color depth of the image: 

        - U8: unsigned 8 bits integer, the most common type

        - U16: unsigned 16 bits integer

        - F16: half, 16 bits floating point. Only available if `Krita` was built with OpenEXR

        - F32: 32 bits floating point
        :param colorProfile: a valid color profile for this color model and color depth combination.
        """

        ...

    def setCurrentTime(self, time: int) -> None:
        """
        set current time of document's animation
        """

        ...

    def setDocumentInfo(self, document: str) -> None:
        """
        setDocumentInfo set the `Document` information to the information contained in document

        [https://phabricator.kde.org/source/krita/browse/master/krita/dtd/](https://phabricator.kde.org/source/krita/browse/master/krita/dtd/)

        :param document: A string containing a valid XML document that conforms to the document-info DTD that can be found here:
        """

        ...

    def setFileName(self, value: str) -> None:
        """
        setFileName set the full path of the document to
        """

        ...

    def setFramesPerSecond(self, fps: int) -> None:
        """
        set frames per second of document
        """

        ...

    def setFullClipRangeEndTime(self, endTime: int) -> None:
        """
        set full clip range end time
        """

        ...

    def setFullClipRangeStartTime(self, startTime: int) -> None:
        """
        set start time of animation
        """

        ...

    def setGridConfig(self, gridConfig: GridConfig) -> None:
        """
        Set grid configuration for current document
           @param gridConfig a GridConfig object to apply for grid configuration

           To modify/set grid property on a document

        ```
        # get document (create one or get active one for example)
        newDoc = `Krita`.`instance`().`createDocument`(500, 500, "Test", "RGBA", "U8", "", 300)

        # retrieve document grid configuration
        newDocGrid = newDoc.`gridConfig`()

        # update properties
        newDocGrid.`setColorMain`(QColor('#ff00ff'))
        newDocGrid.setLineTypeMain('dashed')
        newDocGrid.setVisible(True)
        newDocGrid.setAngleLeft(30)
        newDocGrid.setAngleRight(15)
        newDocGrid.setType('isometric')

        # set grid configuration to document
        newDoc.setGridConfig(newDocGrid)
        ```
        """

        ...

    def setGuidesConfig(self, guidesConfig: GuidesConfig) -> None:
        """
        Set guides configuration for current document
           @param guidesConfig a GuidesConfig object to apply for guides configuration

           To modify/set guides property on a document

        ```
        # get document (create one or get active one for example)
        newDoc = `Krita`.`instance`().`createDocument`(500, 500, "Test", "RGBA", "U8", "", 300)

        # retrieve document guides configuration
        newDocGuides = newDoc.`guidesConfig`()

        # update properties
        newDocGuides.`setColor`(QColor('#ff00ff'))
        newDocGuides.setLineType('dotted')
        newDocGuides.setVisible(True)
        newDocGuides.setLocked(True)
        newDocGuides.setSnap(True)
        newDocGuides.setHorizontalGuides([100,200])

        # set guides configuration to document
        newDoc.setGuidesConfig(newDocGuides)
        ```
        """

        ...

    def setGuidesLocked(self, locked: bool) -> None:
        """
        DEPRECATED - use `guidesConfig()` instead set guides locked on this document.

        :param locked: whether or not to lock the guides on this document.
        """

        ...

    def setGuidesVisible(self, visible: bool) -> None:
        """
        DEPRECATED - use `guidesConfig()` instead set guides visible on this document.

        :param visible: whether or not the guides are visible.
        """

        ...

    def setHeight(self, value: int) -> None:
        """
        setHeight resize the document to

        :param value: height. This is a canvas resize, not a scale.
        """

        ...

    def setHorizontalGuides(self, lines: list[float]) -> None:
        """
        DEPRECATED - use `guidesConfig()` instead replace all existing horizontal guides with the entries in the list.

        :param lines: a list of floats containing the new guides.
        """

        ...

    def setModified(self, modified: bool) -> None:
        """
        setModified sets the modified status of the document

        :param modified: if true, the document is considered modified and closing it will ask for saving.
        """

        ...

    def setName(self, value: str) -> None:
        """
        setName sets the name of the document to `value`. This is the title field in the `documentInfo`
        """

        ...

    def setPlayBackRange(self, start: int, stop: int) -> None:
        """
        set temporary playback range of document
        """

        ...

    def setResolution(self, value: int) -> None:
        """
        setResolution set the resolution of the image; this does not scale the image

        :param value: the resolution in pixels per inch
        """

        ...

    def setSelection(self, value: Selection) -> None:
        """
        setSelection set or replace the global selection

        :param value: a valid selection object.
        """

        ...

    def setVerticalGuides(self, lines: list[float]) -> None:
        """
        DEPRECATED - use `guidesConfig()` instead replace all existing horizontal guides with the entries in the list.

        :param lines: a list of floats containing the new guides.
        """

        ...

    def setWidth(self, value: int) -> None:
        """
        setWidth resize the document to

        :param value: width. This is a canvas resize, not a scale.
        """

        ...

    def setXOffset(self, x: int) -> None:
        """
        setXOffset sets the left edge of the canvas to `x`.
        """

        ...

    def setXRes(self, xRes: float) -> None:
        """
        setXRes set the horizontal resolution of the image to xRes in pixels per inch
        """

        ...

    def setYOffset(self, y: int) -> None:
        """
        setYOffset sets the top edge of the canvas to `y`.
        """

        ...

    def setYRes(self, yRes: float) -> None:
        """
        setYRes set the vertical resolution of the image to yRes in pixels per inch
        """

        ...

    def shearImage(self, angleX: float, angleY: float) -> None:
        """
        shearImage shear the whole image.

        :param angleX: the X-angle in degrees to shear by
        :param angleY: the Y-angle in degrees to shear by
        """

        ...

    def thumbnail(self, w: int, h: int) -> QImage:
        """
        thumbnail create a thumbnail of the given dimensions.

        If the requested size is too big a null QImage is created.


        :returns: a QImage representing the layer contents.
        """

        ...

    def topLevelNodes(self) -> list[Node]:
        """
        toplevelNodes return a list with all top level nodes in the image graph
        """

        ...

    def tryBarrierLock(self) -> bool:
        """
        Tries to lock the image without waiting for the jobs to finish.

        Same as barrierLock(), but doesn't block execution of the calling thread until all the background jobs are finished. Instead, in case of presence of unfinished jobs in the queue, it just returns false


        :returns: whether the lock has been acquired
        """

        ...

    def unlock(self) -> None:
        """
        Unlocks the image and starts/resumes all the pending internal jobs. If the image has been locked for a non-readOnly access, then all the internal caches of the image (e.g. lod-planes) are reset and regeneration jobs are scheduled.
        """

        ...

    def verticalGuides(self) -> list[float]:
        """
        DEPRECATED - use `guidesConfig()` instead The vertical guide lines.

        :returns: a list of vertical guides.
        """

        ...

    def waitForDone(self) -> None:
        """
        Wait for all the internal image jobs to complete and return without locking the image. This function is handy for tests or other synchronous actions, when one needs to wait for the result of his actions.
        """

        ...

    def width(self) -> int:
        """
        :returns: the width of the image in pixels.
        """

        ...

    def xOffset(self) -> int:
        """
        :returns: the left edge of the canvas in pixels.
        """

        ...

    def xRes(self) -> float:
        """
        :returns: xRes the horizontal resolution of the image in pixels per inch
        """

        ...

    def yOffset(self) -> int:
        """
        :returns: the top edge of the canvas in pixels.
        """

        ...

    def yRes(self) -> float:
        """
        :returns: yRes the vertical resolution of the image in pixels per inch
        """

        ...