# Generated by build.py — DO NOT EDIT

from typing import ClassVar
from PyQt5.QtCore import pyqtSignal
from PyQt5.QtWidgets import QWidget
from krita._types.double_parse_spin_box import DoubleParseSpinBox


class DoubleSliderSpinBox(DoubleParseSpinBox):
    """
    This class is a wrapper around KisDoubleSliderSpinBox, a spinbox in which you can click and drag to set the value, with a slider like bar displayed inside. The widget itself is accessed with the `widget()` function.

    See also: `SliderSpinBox`
    """

    def __init__(self) -> None:
        ...

    def fastSliderStep(self) -> float:
        ...

    def isDragging(self) -> bool:
        ...

    def setBlockUpdateSignalOnDrag(self, newBlockUpdateSignalOnDrag: bool) -> None:
        ...

    def setExponentRatio(self, newExponentRatio: float) -> None:
        ...

    def setFastSliderStep(self, newFastSliderStep: float) -> None:
        ...

    def setMaximum(self, newMaximum: float, computeNewFastSliderStep: bool = True) -> None:
        ...

    def setMinimum(self, newMinimum: float, computeNewFastSliderStep: bool = True) -> None:
        ...

    def setRange(self, newMinimum: float, newMaximum: float, newNumberOfDecimals: int = 0, computeNewFastSliderStep: bool = True) -> None:
        """
        Set the minimum and the maximum values of the range.

        The soft range will be adapted to fit inside the range The number of decimals used can be changed with the newNumberOfDecimals parameter 

        See also: setMinimum(qreal)

        See also: setMaximum(qreal)

        :param newMinimum: the new minimum value
        :param newMaximum: the new maximum value
        :param newNumberOfDecimals: the new number of decimals
        :param computeNewFastSliderStep: true if a new "fast slider step" must be computed based on the range
        """

        ...

    def setSoftMaximum(self, newSoftMaximum: float) -> None:
        ...

    def setSoftMinimum(self, newSoftMinimum: float) -> None:
        ...

    def setSoftRange(self, newSoftMinimum: float, newSoftMaximum: float) -> None:
        ...

    def setValue(self, newValue: float) -> None:
        ...

    def softMaximum(self) -> float:
        ...

    def softMinimum(self) -> float:
        ...

    def widget(self) -> QWidget:
        """
        Get the internal KisDoubleSliderSpinBox as a QWidget, so it may be added to a UI.

        :returns: the internal KisDoubleSliderSpinBox as a QWidget
        """

        ...

    draggingFinished: ClassVar[pyqtSignal]