# Generated by build.py — DO NOT EDIT

from typing import ClassVar
from PyQt5.QtCore import pyqtSignal
from PyQt5.QtWidgets import QDoubleSpinBox


class DoubleParseSpinBox:
    """
    A wrapper around KisDoubleParseSpinBox, which is a cleverer doubleSpinBox, able to parse arithmetic expressions. The widget itself is accessed with the `widget()` function.

    Use this spinbox instead of the basic one from Qt if you want it to be able to parse arithmetic expressions.
    """

    def __init__(self) -> None:
        ...

    def isLastValid(self) -> bool:
        """
        Get if the last expression entered is a valid one.

        :param true: if the last expression entered is valid
        :param false: otherwise
        """

        ...

    def setValue(self, value: float, overwriteExpression: bool = False) -> None:
        """
        Set the value of the spinbox.

        This reimplementation also tries to clear the current expression and warning message whenever possible. This will happen when the new value is different from the current one and the line edit has not the focus or it is read-only. One can force the reset also by passing true to the `overwriteExpression` parameter.

        :param value: The new value
        :param overwriteExpression: Get if the expression in the edit field (and the warning message) should be reset to reflect the new value. The default is false so that if the user is editing the expression it won't be disrupted by any default call to this function
        """

        ...

    def stepBy(self, steps: int) -> None:
        """
        This is a reimplementation of QDoubleSpinBox::stepBy that uses `setValue`.

        :param steps: Number of steps that the value should change
        """

        ...

    def veryCleanText(self) -> str:
        """
        This virtual function is similar to cleanText(). But child classes may reimplement it to further process ("clean up") the expression.

        :returns: The processed expression
        """

        ...

    def widget(self) -> QDoubleSpinBox:
        """
        Get the internal KisDoubleParseSpinBox as a QWidget, so it may be added to a UI.

        :returns: the internal KisDoubleParseSpinBox as a QWidget
        """

        ...

    errorWhileParsing: ClassVar[pyqtSignal]  # signal emitted when the last parsed expression is not valid.

    noMoreParsingError: ClassVar[pyqtSignal]  # signal emitted when the last parsed expression is valid and the expression before was not valid.