# Generated by build.py — DO NOT EDIT

from typing import overload
from PyQt5.QtCore import QObject
from krita._types._opaque import KisFileLayerSP
from krita._types._opaque import KisImageSP
from krita._types.node import Node


class FileLayer(Node):
    """
    The `FileLayer` class A file layer is a layer that can reference an external image and show said reference in the layer stack.

    If the external image is updated, `Krita` will try to update the file layer image as well.
    """

    @overload
    def FileLayer(self, image: KisImageSP, name: str = "", baseName: str = "", fileName: str = "", scalingMethod: str = "", scalingFilter: str = "", parent: QObject = None) -> None: ...

    @overload
    def FileLayer(self, layer: KisFileLayerSP, parent: QObject = None) -> None: ...

    def path(self) -> str:
        """
        path

        :returns: A QString with the full path of the referenced image.
        """

        ...

    def resetCache(self) -> None:
        """
        makes the file layer to reload the connected image from disk
        """

        ...

    def scalingFilter(self) -> str:
        """
        scalingFilter returns the filter with which the file referenced is scaled.
        """

        ...

    def scalingMethod(self) -> str:
        """
        scalingMethod returns how the file referenced is scaled.

        :returns: one of the following: 

        - None - The file is not scaled in any way.

        - ToImageSize - The file is scaled to the full image size;

        - ToImagePPI - The file is scaled by the PPI of the image. This keep the physical dimensions the same.
        """

        ...

    def setProperties(self, fileName: str, scalingMethod: str = 'None', scalingFilter: str = 'Bicubic') -> None:
        """
        setProperties Change the properties of the file layer.

        :param fileName: - A String containing the absolute file name.
        :param scalingMethod: - a string with the scaling method, defaults to "None", other options are "ToImageSize" and "ToImagePPI"
        :param scalingFilter: - a string with the scaling filter, defaults to "Bicubic", other options are "Hermite", "NearestNeighbor", "Bilinear", "Bell", "BSpline", "Lanczos3", "Mitchell"
        """

        ...

    def type(self) -> str:
        """
        type `Krita` has several types of nodes, split in layers and masks. Group layers can contain other layers, any layer can contain masks.

        :returns: "filelayer"
        """

        ...