# Generated by build.py — DO NOT EDIT

from typing import ClassVar
from PyQt5.QtCore import QUrl
from PyQt5.QtWidgets import QWidget


class FileDialog:
    """
    Wrapper around KoFileDialog, which is a wrapper around QFileDialog, providing native file dialogs on KDE/Gnome/Windows/OSX/etc. `FileDialog` respects `Krita`'s "Don't use native file dialogs" setting.
    """

    class DialogType(int):
        OpenFile: ClassVar[FileDialog.DialogType]
        OpenFiles: ClassVar[FileDialog.DialogType]
        OpenDirectory: ClassVar[FileDialog.DialogType]
        ImportFile: ClassVar[FileDialog.DialogType]
        ImportFiles: ClassVar[FileDialog.DialogType]
        ImportDirectory: ClassVar[FileDialog.DialogType]
        SaveFile: ClassVar[FileDialog.DialogType]

    def __init__(self, parent: QWidget = None, arg1: FileDialog.DialogType = FileDialog.DialogType.OpenFile, dialogName: str = '') -> None:
        """
        constructor

        :returns: The name of the entry user selected in the file dialog

        :param parent: The parent of the file dialog
        :param dialogType: usage of the file dialog Valid arguments: 

        - FileDialog.DialogType.OpenFile

        - FileDialog.DialogType.OpenFiles

        - FileDialog.DialogType.OpenDirectory

        - FileDialog.DialogType.ImportFile

        - FileDialog.DialogType.ImportFiles

        - FileDialog.DialogType.ImportDirectory

        - FileDialog.DialogType.SaveFile 



        dialogName the name for the file dialog. This will be used to open the filedialog in the last open location, instead of the specified directory.
        """

        ...

    def filename(self) -> str:
        """
        Show the file dialog and return the file name the user selected.
        """

        ...

    def filenames(self) -> list[str]:
        """
        Show the file dialog and return multiple file names the user selected.
        """

        ...

    @staticmethod
    def getExistingDirectory(parent: QWidget = None, caption: str = "", directory: str = "", dialogName: str = "") -> str:
        """
        Create and show a file dialog and return the name of an existing directory selected by the user.

        :returns: the name of an existing directory selected by the user

        :param parent: Dialog parent widget
        :param caption: Dialog caption
        :param directory: Starting directory for the file dialog
        :param dialogName: Internal name of the dialog used for remembering the opened directory
        """

        ...

    @staticmethod
    def getOpenFileName(parent: QWidget = None, caption: str = "", directory: str = "", filter: str = "", selectedFilter: str = "", dialogName: str = "") -> str:
        """
        Create and show a file dialog and return the name of an existing file selected by the user.

        :returns: the name of an existing file selected by the user

        :param parent: Dialog parent widget
        :param caption: Dialog caption
        :param directory: Starting directory for the file dialog
        :param filter: Name filters for files shown
        :param selectedFilter: The selected name filter
        :param dialogName: Internal name of the dialog used for remembering the opened directory
        """

        ...

    @staticmethod
    def getOpenFileNames(parent: QWidget = None, caption: str = "", directory: str = "", filter: str = "", selectedFilter: str = "", dialogName: str = "") -> list[str]:
        """
        Create and show a file dialog and return the name of multiple existing files selected by the user.

        :returns: the name of multiple existing files selected by the user

        :param parent: Dialog parent widget
        :param caption: Dialog caption
        :param directory: Starting directory for the file dialog
        :param filter: Name filters for files shown
        :param selectedFilter: The selected name filter
        :param dialogName: Internal name of the dialog used for remembering the opened directory
        """

        ...

    @staticmethod
    def getSaveFileName(parent: QWidget = None, caption: str = "", directory: str = "", filter: str = "", selectedFilter: str = "", dialogName: str = "") -> str:
        """
        Create and show a file dialog and return the name of a file to save to selected by the user.

        :returns: the name of a file to save to selected by the user

        :param parent: Dialog parent widget
        :param caption: Dialog caption
        :param directory: Starting directory for the file dialog
        :param filter: Name filters for files shown
        :param selectedFilter: The selected name filter
        :param dialogName: Internal name of the dialog used for remembering the opened directory
        """

        ...

    def onFilterSelected(self, filter: str) -> None:
        ...

    def selectNameFilter(self, filter: str) -> None:
        ...

    def selectedMimeType(self) -> str:
        ...

    def selectedNameFilter(self) -> str:
        """
        selectedNameFilter returns the name filter the user selected, either directory or by clicking on it.

        :returns:
        """

        ...

    def setCaption(self, caption: str) -> None:
        ...

    def setDefaultDir(self, defaultDir: str, force: bool = False) -> None:
        """
        setDefaultDir set the default directory to defaultDir.

        :param defaultDir: a path to a file or directory
        """

        ...

    def setDirectoryUrl(self, defaultUri: QUrl) -> None:
        """
        setDirectoryUrl set the default URI to defaultUri.

        :param defaultUri: a Uri to a file from some ContentProvider
        """

        ...

    def setImageFilters(self) -> None:
        """
        setImageFilters sets the name filters for the file dialog to all image formats Qt's QImageReader supports.
        """

        ...

    def setMimeTypeFilters(self, mimeTypeList: list[str], defaultMimeType: str = "") -> None:
        """
        setMimeTypeFilters Update the list of file filters from mime types.

        :param mimeTypeList: A list of mime types that forms the basis of this dialog's file filters
        :param defaultMimeType: Sets the default filter based on this mime type
        """

        ...

    def setNameFilter(self, filter: str) -> None:
        ...