# Generated by build.py — DO NOT EDIT

from typing import overload
from PyQt5.QtCore import QObject
from krita._types._opaque import KisFilterConfigurationSP
from krita._types._opaque import KisGeneratorLayerSP
from krita._types._opaque import KisImageSP
from krita._types.info_object import InfoObject
from krita._types.node import Node
from krita._types.selection import Selection


class FillLayer(Node):
    """
    The `FillLayer` class A fill layer is much like a filter layer in that it takes a name and filter. It however specializes in filters that fill the whole canvas, such as a pattern or full color fill.
    """

    @overload
    def FillLayer(self, image: KisImageSP, name: str, filterConfig: KisFilterConfigurationSP, selection: Selection, parent: QObject = None) -> None: ...

    @overload
    def FillLayer(self, layer: KisGeneratorLayerSP, parent: QObject = None) -> None: ...

    def filterConfig(self) -> InfoObject:
        ...

    def generatorName(self) -> str:
        ...

    def setGenerator(self, generatorName: str, filterConfig: InfoObject) -> bool:
        """
        setGenerator set the given generator for this fill layer

        :returns: true if the generator was correctly created and set on the layer

        :param generatorName: "pattern" or "color"
        :param filterConfig: a configuration object appropriate to the given generator plugin
        """

        ...

    def type(self) -> str:
        """
        type `Krita` has several types of nodes, split in layers and masks. Group layers can contain other layers, any layer can contain masks.

        :returns: The type of the node. Valid types are: 

        - paintlayer

        - grouplayer

        - filelayer

        - filterlayer

        - filllayer

        - clonelayer

        - vectorlayer

        - transparencymask

        - filtermask

        - transformmask

        - selectionmask

        - colorizemask
        If the `Node` object isn't wrapping a valid `Krita` layer or mask object, and empty string is returned.
        """

        ...