# Generated by build.py — DO NOT EDIT

from typing import overload
from PyQt5.QtCore import QObject
from krita._types._opaque import KisAdjustmentLayerSP
from krita._types._opaque import KisImageSP
from krita._types.filter import Filter
from krita._types.node import Node
from krita._types.selection import Selection


class FilterLayer(Node):
    """
    The `FilterLayer` class A filter layer will, when compositing, take the composited image up to the point of the location of the filter layer in the stack, create a copy and apply a filter.

    This means you can use blending modes on the filter layers, which will be used to blend the filtered image with the original.


    Similarly, you can activate things like alpha inheritance, or you can set grayscale pixeldata on the filter layer to act as a mask.


    `Filter` layers can be animated.
    """

    @overload
    def FilterLayer(self, image: KisImageSP, name: str, filter: Filter, selection: Selection, parent: QObject = None) -> None: ...

    @overload
    def FilterLayer(self, layer: KisAdjustmentLayerSP, parent: QObject = None) -> None: ...

    def filter(self) -> Filter:
        ...

    def setFilter(self, filter: Filter) -> None:
        ...

    def type(self) -> str:
        """
        type `Krita` has several types of nodes, split in layers and masks. Group layers can contain other layers, any layer can contain masks.

        :returns: "filterlayer"
        """

        ...