# Generated by build.py — DO NOT EDIT

from typing import overload
from PyQt5.QtCore import QObject
from krita._types._opaque import KisFilterMaskSP
from krita._types._opaque import KisImageSP
from krita._types.filter import Filter
from krita._types.node import Node


class FilterMask(Node):
    """
    The `FilterMask` class A filter mask, unlike a filter layer, will add a non-destructive filter to the composited image of the node it is attached to.

    You can set grayscale pixeldata on the filter mask to adjust where the filter is applied.


    Filtermasks can be animated.
    """

    @overload
    def FilterMask(self, image: KisImageSP, name: str, filter: Filter, parent: QObject = None) -> None: ...

    @overload
    def FilterMask(self, image: KisImageSP, mask: KisFilterMaskSP, parent: QObject = None) -> None: ...

    def filter(self) -> Filter:
        ...

    def setFilter(self, filter: Filter) -> None:
        ...

    def type(self) -> str:
        """
        type `Krita` has several types of nodes, split in layers and masks. Group layers can contain other layers, any layer can contain masks.

        :returns: The type of the node. Valid types are: 

        - paintlayer

        - grouplayer

        - filelayer

        - filterlayer

        - filllayer

        - clonelayer

        - vectorlayer

        - transparencymask

        - filtermask

        - transformmask

        - selectionmask

        - colorizemask
        If the `Node` object isn't wrapping a valid `Krita` layer or mask object, and empty string is returned.
        """

        ...