# Generated by build.py — DO NOT EDIT

from typing import overload
from PyQt5.QtCore import QObject, QPoint
from PyQt5.QtGui import QColor
from krita._types._opaque import KisGridConfig


class GridConfig:
    """
    The `GridConfig` class encapsulates a `Krita` Guides configuration.
    """

    @overload
    def GridConfig(self, guidesConfig: KisGridConfig) -> None: ...

    @overload
    def GridConfig(self, parent: QObject = None) -> None: ...

    def angleAspectLocked(self) -> bool:
        """
        Returns status of "Aspect locked" property for angles values (mean, left and right angles values are linked to keep ratio) AngleAspectLocked value is used for grid type "isometric" and "isometric_legacy".

        :returns: If locked, return True.
        """

        ...

    def angleLeft(self) -> float:
        """
        Returns left angle (in degrees) of isometric grid for document. AngleLeft value is used for grid type "isometric".

        :returns: A positive decimal value, in range [0.00 - 89.00]
        """

        ...

    def angleLeftActive(self) -> bool:
        """
        Returns if left angle grid is active. Spacing value is used for grid type "isometric".

        :returns: a boolean which indicate if left angle grid is active or not
        """

        ...

    def angleRight(self) -> float:
        """
        Returns right angle (in degrees) of isometric grid for document. AngleRight value is used for grid type "isometric".

        :returns: A positive decimal value, in range [0.00 - 89.00]
        """

        ...

    def angleRightActive(self) -> bool:
        """
        Returns if right angle grid is active. Spacing value is used for grid type "isometric".

        :returns: a boolean which indicate if right angle grid is active or not
        """

        ...

    def cellSize(self) -> int:
        """
        Returns grid cell border size (in pixels) for document. Cell spacing value is used for grid type "isometric".

        :returns: A positive integer value, in range [10 - 1000]
        """

        ...

    def cellSpacing(self) -> int:
        """
        Returns grid cell spacing (in pixels) for document. Cell spacing value is used for grid type "isometric_legacy".

        :returns: A positive integer value, minimum value is 10
        """

        ...

    def colorMain(self) -> QColor:
        """
        Returns grid main line color.

        :returns: The color for grid main line
        """

        ...

    def colorSubdivision(self) -> QColor:
        """
        Returns grid subdivision line color ColorSubdivision value is used for grid type "rectangular".

        :returns: The color for grid subdivision line
        """

        ...

    def colorVertical(self) -> QColor:
        """
        Returns grid vertical line color ColorSubdivision value is used for grid type "isometric".

        :returns: The color for grid vertical line
        """

        ...

    def fromXml(self, xmlContent: str) -> bool:
        """
        Load grid definition from an XML document.

        :returns: True if xml content is valid and grid has been loaded, otherwise False

        :param xmlContent: xml content provided as a string
        """

        ...

    def lineTypeMain(self) -> str:
        """
        Returns grid main line type.

        :returns: The main line type for grid in current document Can be:

        - "solid"
        - "dashed"
        - "dotted"
        """

        ...

    def lineTypeSubdivision(self) -> str:
        """
        Returns grid subdivision line type.

        :returns: The subdivision line type for grid in current document Can be:

        - "solid"
        - "dashed"
        - "dotted"
        LineTypeSubdivision value is used for grid type "rectangular".
        """

        ...

    def lineTypeVertical(self) -> str:
        """
        Returns grid vertical line type.

        :returns: The vertical line type for grid in current document Can be:

        - "solid"
        - "dashed"
        - "dotted"
        - "none"
        LineTypeVertical value is used for grid type "isometric".
        """

        ...

    def offset(self) -> QPoint:
        """
        Returns grid offset (in pixels, from origin) for document.

        :returns: A QPoint that define X and Y offset.
        """

        ...

    def offsetAspectLocked(self) -> bool:
        """
        Returns status of "Aspect locked" property for offset values (X and Y values are linked to keep ratio)

        :returns: If locked, return True.
        """

        ...

    def setAngleAspectLocked(self, angleAspectLocked: bool) -> None:
        """
        Set status of "Aspect locked" property for angles values (left and right angles values are linked to keep ratio) AngleAspectLocked value is used for grid type "isometric" and "isometric_legacy".

        :param angleAspectLocked: Set to True lock aspect.
        """

        ...

    def setAngleLeft(self, angleLeft: float) -> None:
        """
        Set left angle (in degrees) of isometric grid for document. AngleLeft value is used for grid type "isometric".

        :param angleLeft: A positive decimal value, in range [0.00 - 89.00]
        """

        ...

    def setAngleLeftActive(self, active: bool) -> None:
        """
        Set left angle grid active. Spacing value is used for grid type "isometric".

        :param active: True to activate left angle grid, False to deactivate it.
        """

        ...

    def setAngleRight(self, angleRight: float) -> None:
        """
        Set right angle (in degrees) of isometric grid for document. AngleRight value is used for grid type "isometric".

        :param angleRight: A positive decimal value, in range [0.00 - 89.00]
        """

        ...

    def setAngleRightActive(self, active: bool) -> None:
        """
        Set right angle grid active. Spacing value is used for grid type "isometric".

        :param active: True to activate right angle grid, False to deactivate it.
        """

        ...

    def setCellSize(self, cellSize: int) -> None:
        """
        Set grid cell size (in pixels) for document. Cell spacing value is used for grid type "isometric".

        :param cellSize: An integer that define cell border size.
        """

        ...

    def setCellSpacing(self, cellSpacing: int) -> None:
        """
        Set grid cell spacing for document. Cell spacing value is used for grid type "isometric_legacy".

        :param cellSpacing: A integer that define spacing, in range [10 - 1000]
        """

        ...

    def setColorMain(self, colorMain: QColor) -> None:
        """
        Set grid main line color.

        :param color: The color to apply for grid main line
        """

        ...

    def setColorSubdivision(self, colorSubdivision: QColor) -> None:
        """
        Set grid subdivision line color ColorSubdivision value is used for grid type "rectangular".

        :param color: The color to apply for grid subdivision line
        """

        ...

    def setColorVertical(self, colorVertical: QColor) -> None:
        """
        Set grid vertical line color ColorSubdivision value is used for grid type "isometric".

        :param color: The color to apply for grid vertical line
        """

        ...

    def setLineTypeMain(self, lineType: str) -> None:
        """
        Set grid main line type.

        :param lineType: The main line type to apply for grid Can be:

        - "solid"
        - "dashed"
        - "dotted"
        """

        ...

    def setLineTypeSubdivision(self, lineType: str) -> None:
        """
        Set grid subdivision line type.

        LineTypeSubdivision value is used for grid type "rectangular".

        :param lineType: The subdivision line type to apply for grid Can be:

        - "solid"
        - "dashed"
        - "dotted"
        """

        ...

    def setLineTypeVertical(self, lineType: str) -> None:
        """
        Set grid vertical line type.

        LineTypeVertical value is used for grid type "isometric".

        :param lineType: The vertical line type to apply for grid Can be:

        - "solid"
        - "dashed"
        - "dotted"
        - "none"
        """

        ...

    def setOffset(self, offset: QPoint) -> None:
        """
        Define grid offset (in pixels, from origin) for document.

        :param offset: A QPoint that define X and Y offset (X and Y in range [0 - 500])
        """

        ...

    def setOffsetAspectLocked(self, offsetAspectLocked: bool) -> None:
        """
        Set status of "Aspect locked" property for offset values (X and Y values are linked to keep ratio)

        :param offsetAspectLocked: Set to True lock aspect.
        """

        ...

    def setSnap(self, snap: bool) -> None:
        """
        Activate or deactivate snap to grid for document.

        :param snap: Set to True to activate snap to grid.
        """

        ...

    def setSpacing(self, spacing: QPoint) -> None:
        """
        Set grid spacing (in pixels) for document. Spacing value is used for grid type "rectangular".

        :param spacing: A QPoint that define X and Y spacing (minimum value for X and Y is 1)
        """

        ...

    def setSpacingActiveHorizontal(self, active: bool) -> None:
        """
        Set horizontal grid spacing active. Spacing value is used for grid type "rectangular".

        :param active: True to activate horizontal spacing, False to deactivate it.
        """

        ...

    def setSpacingActiveVertical(self, active: bool) -> None:
        """
        Set vertical grid spacing active. Spacing value is used for grid type "rectangular".

        :param active: True to activate vertical spacing, False to deactivate it.
        """

        ...

    def setSpacingAspectLocked(self, spacingAspectLocked: bool) -> None:
        """
        Set status of "Aspect locked" property for spacing values (X and Y values are linked to keep ratio) SpacingAspectLocked value is used for grid type "rectangular".

        :param spacingAspectLocked: Set to True lock aspect.
        """

        ...

    def setSubdivision(self, subdivision: int) -> None:
        """
        Set number of grid subdivision for document. Subdivision value is used for grid type "rectangular".

        :param subdivision: A positive integer value, in range [1 - 10]
        """

        ...

    def setType(self, gridType: str) -> None:
        """
        Set current grid type applied for document.

        :param gridType: The grid type can be:

        - "rectangular"
        - "isometric"
        - "isometric_legacy"
        """

        ...

    def setVisible(self, visible: bool) -> None:
        """
        Set grid visibility for document.

        :param snap: Set to True to get grid visible.
        """

        ...

    def snap(self) -> bool:
        """
        Returns snap to grid status for document.

        :returns: If snap to grid is active on document, return True.
        """

        ...

    def spacing(self) -> QPoint:
        """
        Returns grid spacing (in pixels) for document. Spacing value is used for grid type "rectangular".

        :returns: A QPoint that define X and Y spacing.
        """

        ...

    def spacingActiveHorizontal(self) -> bool:
        """
        Returns if horizontal grid spacing is active. Spacing value is used for grid type "rectangular".

        :returns: a boolean which indicate if horizontal grid is active or not
        """

        ...

    def spacingActiveVertical(self) -> bool:
        """
        Returns if vertical grid spacing is active. Spacing value is used for grid type "rectangular".

        :returns: a boolean which indicate if vertical grid is active or not
        """

        ...

    def spacingAspectLocked(self) -> bool:
        """
        Returns status of "Aspect locked" property for spacing values (mean, X and Y values are linked to keep ratio) SpacingAspectLocked value is used for grid type "rectangular".

        :returns: If locked, return True.
        """

        ...

    def subdivision(self) -> int:
        """
        Returns number of grid subdivision for document. Subdivision value is used for grid type "rectangular".

        :returns: A positive integer value, starting from 1
        """

        ...

    def toXml(self) -> str:
        """
        Save grid definition as an XML document.

        :returns: A string with xml content
        """

        ...

    def type(self) -> str:
        """
        Returns current grid type applied for document.

        :returns: The grid type can be:

        - "rectangular"
        - "isometric"
        - "isometric_legacy"
        """

        ...

    def visible(self) -> bool:
        """
        Returns grid visibility for document.

        :returns: If grid is visible, return True.
        """

        ...