# Generated by build.py — DO NOT EDIT

from typing import overload
from PyQt5.QtCore import QObject
from krita._types._opaque import KisGroupLayerSP
from krita._types._opaque import KisImageSP
from krita._types.node import Node


class GroupLayer(Node):
    """
    The `GroupLayer` class A group layer is a layer that can contain other layers. In `Krita`, layers within a group layer are composited first before they are added into the composition code for where the group is in the stack. This has a significant effect on how it is interpreted for blending modes.

    PassThrough changes this behaviour.


    Group layer cannot be animated, but can contain animated layers or masks.
    """

    @overload
    def GroupLayer(self, image: KisImageSP, name: str, parent: QObject = None) -> None: ...

    @overload
    def GroupLayer(self, layer: KisGroupLayerSP, parent: QObject = None) -> None: ...

    def passThroughMode(self) -> bool:
        """
        passThroughMode

        :returns: returns whether or not this layer is in passthrough mode.

        See also: `setPassThroughMode`
        """

        ...

    def setPassThroughMode(self, passthrough: bool) -> None:
        """
        setPassThroughMode This changes the way how compositing works. Instead of compositing all the layers before compositing it with the rest of the image, the group layer becomes a sort of formal way to organise everything.

        Passthrough mode is the same as it is in photoshop, and the inverse of SVG's isolation attribute(with passthrough=false being the same as isolation="isolate").

        :param passthrough: whether or not to set the layer to passthrough.
        """

        ...

    def type(self) -> str:
        """
        type `Krita` has several types of nodes, split in layers and masks. Group layers can contain other layers, any layer can contain masks.

        :returns: grouplayer
        """

        ...