# Generated by build.py — DO NOT EDIT

from typing import overload
from PyQt5.QtCore import QObject
from krita._types._opaque import KoShapeGroup
from krita._types.shape import Shape


class GroupShape(Shape):
    """
    The `GroupShape` class A group shape is a vector object with child shapes.
    """

    @overload
    def GroupShape(self, parent: QObject = None) -> None: ...

    @overload
    def GroupShape(self, shape: KoShapeGroup, parent: QObject = None) -> None: ...

    def children(self) -> list[Shape]:
        """
        children

        :returns: the child shapes of this group shape.
        """

        ...

    def type(self) -> str:
        """
        type returns the type.

        :returns: "groupshape"
        """

        ...