# Generated by build.py — DO NOT EDIT

from typing import overload
from PyQt5.QtCore import QObject
from PyQt5.QtGui import QColor
from krita._types._opaque import KisGuidesConfig


class GuidesConfig:
    """
    The `GuidesConfig` class encapsulates a `Krita` Guides configuration.
    """

    @overload
    def GuidesConfig(self, guidesConfig: KisGuidesConfig) -> None: ...

    @overload
    def GuidesConfig(self, parent: QObject = None) -> None: ...

    def color(self) -> QColor:
        """
        Guides color.

        :returns: color applied for all guides
        """

        ...

    def fromXml(self, xmlContent: str) -> bool:
        """
        Load guides definition from an XML document.

        :returns: True if xml content is valid and guides has been loaded, otherwise False

        :param xmlContent: xml content provided as a string
        """

        ...

    def hasGuides(self) -> bool:
        """
        indicate if there's guides defined

        :returns: True if at least one guide is defined, otherwise False
        """

        ...

    def hasSamePositionAs(self, guideConfig: GuidesConfig) -> bool:
        """
        indicate if position from current guides configuration match positions from another guides configuration

        :returns: True if positions are the same
        """

        ...

    def horizontalGuides(self) -> list[float]:
        """
        The horizontal guides.

        :returns: a list of the horizontal positions of guides.
        """

        ...

    def lineType(self) -> str:
        """
        Guides line type.

        :returns: line type applied for all guides Can be:

        - "solid"
        - "dashed"
        - "dot"
        """

        ...

    def locked(self) -> bool:
        """
        Returns guide lock status.

        :returns: True if guides are locked, otherwise False
        """

        ...

    def removeAllGuides(self) -> None:
        """
        Remove all guides.
        """

        ...

    def setColor(self, color: QColor) -> None:
        """
        Define guides color.

        :param color: color to apply
        """

        ...

    def setHorizontalGuides(self, lines: list[float]) -> None:
        """
        Set the horizontal guides.

        :param lines: a list of the horizontal positions of guides to set
        """

        ...

    def setLineType(self, lineType: str) -> None:
        """
        Define guides lines type.

        :param lineType: line type to use for guides: Can be:

        - "solid"
        - "dashed"
        - "dot"
        """

        ...

    def setLocked(self, value: bool) -> None:
        """
        Set guides lock status.

        :param value: True to set guides locked, otherwise False
        """

        ...

    def setSnap(self, value: bool) -> None:
        """
        Set guides snap status.

        :param value: True to set snap to guides active, otherwise False
        """

        ...

    def setVerticalGuides(self, lines: list[float]) -> None:
        """
        Set the vertical guides.

        :param lines: a list of the vertical positions of guides to set
        """

        ...

    def setVisible(self, value: bool) -> None:
        """
        Set guides visibility status.

        :param value: True to set guides visible, otherwise False
        """

        ...

    def snap(self) -> bool:
        """
        Returns guide snap status.

        :returns: True if snap to guides is active, otherwise False
        """

        ...

    def toXml(self) -> str:
        """
        Save guides definition as an XML document.

        :returns: A string with xml content
        """

        ...

    def verticalGuides(self) -> list[float]:
        """
        The vertical guides.

        :returns: a list of vertical positions of guides.
        """

        ...

    def visible(self) -> bool:
        """
        Returns guides visibility status.

        :returns: True if guides are visible, otherwise False
        """

        ...