# Generated by build.py — DO NOT EDIT

from typing import Any, overload
from PyQt5.QtCore import QObject
from krita._types._opaque import KisPropertiesConfigurationSP


class InfoObject:
    """
    `InfoObject` wrap a properties map. These maps can be used to set the configuration for filters.
    """

    @overload
    def InfoObject(self, configuration: KisPropertiesConfigurationSP) -> None: ...

    @overload
    def InfoObject(self, parent: QObject = None) -> None: ...

    def properties(self) -> dict[str, Any]:
        """
        Return all properties this `InfoObject` manages.
        """

        ...

    def property(self, key: str) -> Any:
        """
        return the value for the property identified by key, or None if there is no such key.
        """

        ...

    def setProperties(self, propertyMap: dict[str, Any]) -> None:
        """
        Add all properties in the `propertyMap` to this `InfoObject`
        """

        ...

    def setProperty(self, key: str, value: Any) -> None:
        """
        set the property identified by `key` to `value`


        If you want create a property that represents a color, you can use a QColor or hex string, as defined in [https://doc.qt.io/qt-5/qcolor.html#setNamedColor](https://doc.qt.io/qt-5/qcolor.html#setNamedColor).
        """

        ...