# Generated by build.py — DO NOT EDIT

from typing import Any
from PyQt5.QtCore import QObject
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QAction, QDockWidget
from krita._types.dock_widget_factory_base import DockWidgetFactoryBase
from krita._types.document import Document
from krita._types.extension import Extension
from krita._types.filter import Filter
from krita._types.notifier import Notifier
from krita._types.resource import Resource
from krita._types.view import View
from krita._types.window import Window


class Krita:
    """
    `Krita` is a singleton class that offers the root access to the `Krita` object hierarchy.


    The `Krita.instance()` is aliased as two builtins: Scripter and Application.
    """

    def __init__(self, parent: QObject = None) -> None:
        ...

    def action(self, name: str) -> QAction:
        """
        :returns: the action that has been registered under the given name, or 0 if no such action exists.
        """

        ...

    def actions(self) -> list[QAction]:
        """
        :returns: return a list of all actions for the currently active mainWindow.
        """

        ...

    def activeDocument(self) -> Document:
        """
        :returns: the currently active document, if there is one.
        """

        ...

    def activeWindow(self) -> Window:
        """
        :returns: the currently active window or None if there is no window
        """

        ...

    def addDockWidgetFactory(self, factory: DockWidgetFactoryBase) -> None:
        """
        addDockWidgetFactory Add the given docker factory to the application. For scripts loaded on startup, this means that every window will have one of the dockers created by the factory.

        :param factory: The factory object.
        """

        ...

    def addExtension(self, extension: Extension) -> None:
        """
        addExtension add the given plugin to `Krita`. There will be a single instance of each `Extension` in the `Krita` process.

        :param extension: the extension to add.
        """

        ...

    def addProfile(self, profilePath: str) -> bool:
        """
        addProfile load the given profile into the profile registry.

        :returns: true if adding the profile succeeded.

        :param profilePath: the path to the profile.
        """

        ...

    def batchmode(self) -> bool:
        """
        batchmode determines whether the script is run in batch mode. If batchmode is true, scripts should now show messageboxes or dialog boxes.

        Note that this separate from `Document.setBatchmode()`, which determines whether export/save option dialogs are shown.


        :returns: true if the script is run in batchmode
        """

        ...

    def colorDepths(self, colorModel: str) -> list[str]:
        """
        colorDepths creates a list with the names of all color depths compatible with the given color model.

        :returns: a list of all color depths or a empty list if there is no such color depths.

        :param colorModel: the id of a color model.
        """

        ...

    def colorModels(self) -> list[str]:
        """
        colorModels creates a list with all color models id's registered.

        :returns: a list of all color models or a empty list if there is no such color models.
        """

        ...

    def createDocument(self, width: int, height: int, name: str, colorModel: str, colorDepth: str, profile: str, resolution: float) -> Document:
        """
        createDocument creates a new document and image and registers
           the document with the Krita application.

           Unless you explicitly call Document::close() the document will remain
           known to the Krita document registry. The document and its image will
           only be deleted when Krita exits.

           The document will have one transparent layer.

           To create a new document and show it, do something like:

        ```
        from `Krita` import *

        def add_document_to_window():
            d = Application.createDocument(100, 100, "Test", "RGBA", "U8", "", 120.0)
            Application.`activeWindow`().`addView`(d)

        add_document_to_window()
        ```
            @param width the width in pixels
           @param height the height in pixels
           @param name the name of the image (not the filename of the document)
           @param colorModel A string describing the color model of the image:
           <ul>
           <li>A: Alpha mask</li>
           <li>RGBA: RGB with alpha channel (The actual order of channels is most often BGR!)</li>
           <li>XYZA: XYZ with alpha channel</li>
           <li>LABA: LAB with alpha channel</li>
           <li>CMYKA: CMYK with alpha channel</li>
           <li>GRAYA: Gray with alpha channel</li>
           <li>YCbCrA: YCbCr with alpha channel</li>
           </ul>
           @param colorDepth A string describing the color depth of the image:
           <ul>
           <li>U8: unsigned 8 bits integer, the most common type</li>
           <li>U16: unsigned 16 bits integer</li>
           <li>F16: half, 16 bits floating point. Only available if Krita was built with OpenEXR</li>
           <li>F32: 32 bits floating point</li>
           </ul>
           @param profile The name of an icc profile that is known to Krita. If an empty string is passed, the default is
           taken.
           @param resolution the resolution in points per inch.
           @return the created document.
        """

        ...

    def dockers(self) -> list[QDockWidget]:
        """
        :returns: a list of all the dockers
        """

        ...

    def documents(self) -> list[Document]:
        """
        :returns: a list of all open Documents
        """

        ...

    def extensions(self) -> list[Extension]:
        """
        return a list with all registered extension objects.
        """

        ...

    def filter(self, name: str) -> Filter:
        """
        filter construct a `Filter` object with a default configuration.

        :returns: the filter or None if there is no such filter.

        :param name: the name of the filter. Use `Krita.instance()`.`filters()` to get a list of all possible filters.
        """

        ...

    def filterStrategies(self) -> list[str]:
        """
        filterStrategies Retrieves all installed filter strategies. A filter strategy is used when transforming (scaling, shearing, rotating) an image to calculate the value of the new pixels. You can use th

        :returns: the id's of all available filters.
        """

        ...

    def filters(self) -> list[str]:
        """
        Filters are identified by an internal name. This function returns a list of all existing registered filters.

        :returns: a list of all registered filters
        """

        ...

    @staticmethod
    def fromVariant(v: Any) -> QObject:
        """
        Scripter.fromVariant(variant) variant is a QVariant returns instance of QObject-subclass


        This is a helper method for PyQt because PyQt cannot cast a variant to a QObject or QWidget
        """

        ...

    @staticmethod
    def getAppDataLocation() -> str:
        ...

    def icon(self, iconName: str) -> QIcon:
        """
        icon This allows you to get icons from `Krita`'s internal icons.

        :returns: the icon related to this name.

        :param iconName: name of the icon.
        """

        ...

    @staticmethod
    def instance() -> Krita:
        """
        instance retrieve the singleton instance of the Application object.
        """

        ...

    @staticmethod
    def krita_i18n(text: str) -> str:
        ...

    @staticmethod
    def krita_i18nc(context: str, text: str) -> str:
        ...

    def notifier(self) -> Notifier:
        """
        notifier the `Notifier` singleton emits signals when documents are opened and closed, the configuration changes, views are opened and closed or windows are opened.

        :returns: the notifier object
        """

        ...

    def openDocument(self, filename: str) -> Document:
        """
        openDocument creates a new `Document`, registers it with the `Krita` application and loads the given file.

        :returns: the document

        :param filename: the file to open in the document
        """

        ...

    def openWindow(self) -> Window:
        """
        openWindow create a new main window. The window is not shown by default.
        """

        ...

    def profiles(self, colorModel: str, colorDepth: str) -> list[str]:
        """
        profiles creates a list with the names of all color profiles compatible with the given color model and color depth.

        :returns: a list with valid names

        :param colorModel: A string describing the color model of the image: 

        - A: Alpha mask

        - RGBA: RGB with alpha channel (The actual order of channels is most often BGR!)

        - XYZA: XYZ with alpha channel

        - LABA: LAB with alpha channel

        - CMYKA: CMYK with alpha channel

        - GRAYA: Gray with alpha channel

        - YCbCrA: YCbCr with alpha channel
        :param colorDepth: A string describing the color depth of the image: 

        - U8: unsigned 8 bits integer, the most common type

        - U16: unsigned 16 bits integer

        - F16: half, 16 bits floating point. Only available if `Krita` was built with OpenEXR

        - F32: 32 bits floating point
        """

        ...

    def readSetting(self, group: str, name: str, defaultValue: str) -> str:
        """
        readSetting read the given setting value from the kritarc file.

        :returns: a string representing the setting.

        :param group: The group the setting is part of. If empty, then the setting is read from the general group.
        :param name: The name of the setting
        :param defaultValue: The default value of the setting
        """

        ...

    def recentDocuments(self) -> list[str]:
        """
        return all recent documents registered in the RecentFiles group of the kritarc
        """

        ...

    def resources(self, type: str) -> dict[str, Resource]:
        """
        resources returns a list of `Resource` objects of the given type

        - pattern

        - gradient

        - brush

        - preset

        - palette

        - workspace

        :param type: Valid types are:
        """

        ...

    def setActiveDocument(self, value: Document) -> None:
        """
        setActiveDocument activates the first view that shows the given document

        :param value: the document we want to activate
        """

        ...

    def setBatchmode(self, value: bool) -> None:
        """
        setBatchmode sets the batchmode to

        :param value;: if true, scripts should not show dialogs or messageboxes.
        """

        ...

    def version(self) -> str:
        """
        version Determine the version of `Krita`

        Usage: print(Application.version ())


        :returns: the version string including git sha1 if `Krita` was built from git
        """

        ...

    def views(self) -> list[View]:
        """
        :returns: a list of all views. A `Document` can be shown in more than one view.
        """

        ...

    def windows(self) -> list[Window]:
        """
        :returns: a list of all windows
        """

        ...

    def writeSetting(self, group: str, name: str, value: str) -> None:
        """
        writeSetting write the given setting under the given name to the kritarc file in the given settings group.

        :param group: The group the setting belongs to. If empty, then the setting is written in the general section
        :param name: The name of the setting
        :param value: The value of the setting. Script settings are always written as strings.
        """

        ...