# Generated by build.py — DO NOT EDIT

from PyQt5.QtCore import QByteArray, QObject, QPoint, QPointF, QRect, QRectF, QUuid
from PyQt5.QtGui import QIcon, QImage, QPainterPath
from krita._types._opaque import KisImageSP
from krita._types._opaque import KisNodeSP
from krita._types.channel import Channel
from krita._types.info_object import InfoObject


class Node:
    """
    `Node` represents a layer or mask in a `Krita` image's `Node` hierarchy. Group layers can contain other layers and masks; layers can contain masks.
    """

    def addChildNode(self, child: Node, above: Node) -> bool:
        """
        addChildNode adds the given node in the list of children.

        :returns: false if adding the node failed

        :param child: the node to be added
        :param above: the node above which this node will be placed
        """

        ...

    def alphaLocked(self) -> bool:
        """
        alphaLocked checks whether the node is a paint layer and returns whether it is alpha locked

        :returns: whether the paint layer is alpha locked, or false if the node is not a paint layer
        """

        ...

    def animated(self) -> bool:
        """
        `Krita` layers can be animated, i.e., have frames.

        :returns: return true if the layer has frames. Currently, the scripting framework does not give access to the animation features.
        """

        ...

    def blendingMode(self) -> str:
        """
        :returns: the blending mode of the layer. The values of the blending modes are defined in

        See also: KoCompositeOpRegistry.h
        """

        ...

    def bounds(self) -> QRect:
        """
        bounds return the exact bounds of the node's paint device

        :returns: the bounds, or an empty QRect if the node has no paint device or is empty.
        """

        ...

    def channels(self) -> list[Channel]:
        """
        channels creates a list of `Channel` objects that can be used individually to show or hide certain channels, and to retrieve the contents of each channel in a node separately.

        Only layers have channels, masks do not, and calling channels on a `Node` that is a mask will return an empty list.


        :returns: the list of channels ordered in by position of the channels in pixel position
        """

        ...

    def childNodes(self) -> list[Node]:
        """
        childNodes

        :returns: returns a list of child nodes of the current node. The nodes are ordered from the bottommost up. The function is not recursive.
        """

        ...

    def clone(self) -> Node:
        """
        clone clone the current node. The node is not associated with any image.
        """

        ...

    def collapsed(self) -> bool:
        """
        returns the collapsed state of this node
        """

        ...

    def colorDepth(self) -> str:
        """
        colorDepth A string describing the color depth of the image: 

        - U8: unsigned 8 bits integer, the most common type

        - U16: unsigned 16 bits integer

        - F16: half, 16 bits floating point. Only available if `Krita` was built with OpenEXR

        - F32: 32 bits floating point


        :returns: the color depth.
        """

        ...

    def colorLabel(self) -> int:
        """
        Sets a color label index associated to the layer. The actual color of the label and the number of available colors is defined by `Krita` GUI configuration.
        """

        ...

    def colorModel(self) -> str:
        """
        colorModel retrieve the current color model of this document:

        - A: Alpha mask

        - RGBA: RGB with alpha channel (The actual order of channels is most often BGR!)

        - XYZA: XYZ with alpha channel

        - LABA: LAB with alpha channel

        - CMYKA: CMYK with alpha channel

        - GRAYA: Gray with alpha channel

        - YCbCrA: YCbCr with alpha channel


        :returns: the internal color model string.
        """

        ...

    def colorProfile(self) -> str:
        """
        :returns: the name of the current color profile
        """

        ...

    @staticmethod
    def createNode(image: KisImageSP, node: KisNodeSP, parent: QObject = None) -> Node:
        ...

    def cropNode(self, x: int, y: int, w: int, h: int) -> None:
        """
        cropNode crop this layer.

        :param x: the left edge of the cropping rectangle.
        :param y: the top edge of the cropping rectangle
        :param w: the right edge of the cropping rectangle
        :param h: the bottom edge of the cropping rectangle
        """

        ...

    def duplicate(self) -> Node:
        """
        duplicate returns a full copy of the current node. The node is not inserted in the graphic

        :returns: a valid `Node` object or 0 if the node couldn't be duplicated.
        """

        ...

    def enableAnimation(self) -> None:
        """
        enableAnimation make the current layer animated, so it can have frames.
        """

        ...

    def findChildNodes(self, name: str = "", recursive: bool = False, partialMatch: bool = False, type: str = "", colorLabelIndex: int = 0) -> list[Node]:
        """
        findChildNodes

        :returns: returns a list of child nodes and grand child nodes of the current node that match the search criteria.

        :param name: name of the child node to search for. Leaving this blank will return all nodes.
        :param recursive: whether or not to search recursively. Defaults to false.
        :param partialMatch: return if the name partially contains the string (case insensitive). Defaults to false.
        :param type: filter returned nodes based on type
        :param colorLabelIndex: filter returned nodes based on color label index
        """

        ...

    def hasExtents(self) -> bool:
        """
        does the node have any content in it?

        :returns: if node has any content in it
        """

        ...

    def hasKeyframeAtTime(self, frameNumber: int) -> bool:
        """
        Check to see if frame number on layer is a keyframe
        """

        ...

    def icon(self) -> QIcon:
        """
        icon

        :returns: the icon associated with the layer.
        """

        ...

    def index(self) -> int:
        """
        index the index of the node inside the parent

        :returns: an integer representing the node's index inside the parent
        """

        ...

    def inheritAlpha(self) -> bool:
        """
        inheritAlpha checks whether this node has the inherits alpha flag set

        :returns: true if the Inherit Alpha is set
        """

        ...

    def isPinnedToTimeline(self) -> bool:
        """
        :returns: Returns true if node is pinned to the Timeline Docker or false if it is not.
        """

        ...

    def layerStyleToAsl(self) -> str:
        """
        layerStyleToAsl retrieve the current layer's style in ASL format.

        :returns: a QString in ASL format representing the layer style.
        """

        ...

    def locked(self) -> bool:
        """
        locked checks whether the `Node` is locked. A locked node cannot be changed.

        :returns: true if the `Node` is locked, false if it hasn't been locked.
        """

        ...

    def mergeDown(self) -> Node:
        """
        mergeDown merges the given node with the first visible node underneath this node in the layerstack. This will drop all per-layer metadata.
        """

        ...

    def move(self, x: int, y: int) -> None:
        """
        move the pixels to the given x, y location in the image coordinate space.
        """

        ...

    def name(self) -> str:
        """
        :returns: the user-visible name of this node.
        """

        ...

    def opacity(self) -> int:
        """
        return the opacity of the `Node`. The opacity is a value between 0 and 255.
        """

        ...

    def paintAbility(self) -> str:
        """
        paintAbility can be used to determine whether this node can be painted on with the current brush preset.

        :returns: QString, one of the following: 

        - VECTOR - This node is vector-based.

        - CLONE - This node is a Clone Layer.

        - PAINT - This node is paintable by the current brush preset.

        - UNPAINTABLE - This node is not paintable, or a null preset is somehow selected./li>

        - MYPAINTBRUSH_UNPAINTABLE - This node's non-RGBA colorspace cannot be painted on by the currently selected MyPaint brush.
        """

        ...

    def paintEllipse(self, rect: QRectF, strokeStyle: str = "ForegroundColor", fillStyle: str = "None") -> None:
        """
        paint an ellipse on the canvas. Uses current brush preset

        :param rect: QRect with x, y, width, and height 

        - None

        - ForegroundColor

        - BackgroundColor


        Default is ForegroundColor.
        :param fillStyle: appearance of the fill, one of: 

        - None

        - ForegroundColor

        - BackgroundColor

        - Pattern


        Default is None.
        """

        ...

    def paintLine(self, pointOne: QPointF, pointTwo: QPointF, pressureOne: float = 1.0, pressureTwo: float = 1.0, strokeStyle: str = "ForegroundColor") -> None:
        """
        paint a line on the canvas. Uses current brush preset

        :param pointOne: starting point
        :param pointTwo: end point
        :param pressureOne: starting pressure
        :param pressureTwo: end pressure
        :param strokeStyle: appearance of the outline, one of: 

        - None - will use Foreground Color, since line would be invisible otherwise

        - ForegroundColor

        - BackgroundColor
        """

        ...

    def paintPath(self, path: QPainterPath, strokeStyle: str = "ForegroundColor", fillStyle: str = "None") -> None:
        """
        paint a custom path on the canvas. Uses current brush preset

        :param path: QPainterPath to determine path 

        - None

        - ForegroundColor

        - BackgroundColor


        Default is ForegroundColor.
        :param fillStyle: appearance of the fill, one of: 

        - None

        - ForegroundColor

        - BackgroundColor

        - Pattern


        Default is None.
        """

        ...

    def paintPolygon(self, points: list[QPointF], strokeStyle: str = "ForegroundColor", fillStyle: str = "None") -> None:
        """
        paint a polygon on the canvas. Uses current brush preset

        :param list: of Qpoints 

        - None

        - ForegroundColor

        - BackgroundColor


        Default is ForegroundColor.
        :param fillStyle: appearance of the fill, one of: 

        - None

        - ForegroundColor

        - BackgroundColor

        - Pattern


        Default is None.
        """

        ...

    def paintRectangle(self, rect: QRectF, strokeStyle: str = "ForegroundColor", fillStyle: str = "None") -> None:
        """
        paint a rectangle on the canvas. Uses current brush preset

        :param rect: QRect with x, y, width, and height
        :param strokeStyle: appearance of the outline, one of: 

        - None

        - ForegroundColor

        - BackgroundColor


        Default is ForegroundColor.
        :param fillStyle: appearance of the fill, one of: 

        - None

        - ForegroundColor

        - BackgroundColor

        - Pattern


        Default is None.
        """

        ...

    def parentNode(self) -> Node:
        """
        return the `Node` that is the parent of the current `Node`, or 0 if this is the root `Node`.
        """

        ...

    def pixelData(self, x: int, y: int, w: int, h: int) -> QByteArray:
        """
        pixelData reads the given rectangle from the `Node`'s paintable pixels, if those exist, and returns it as a byte array. The pixel data starts top-left, and is ordered row-first.

        The byte array can be interpreted as follows: 8 bits images have one byte per channel, and as many bytes as there are channels. 16 bits integer images have two bytes per channel, representing an unsigned short. 16 bits float images have two bytes per channel, representing a half, or 16 bits float. 32 bits float images have four bytes per channel, representing a float.


        You can read outside the node boundaries; those pixels will be transparent black.


        The order of channels is:


        - Integer RGBA: Blue, Green, Red, Alpha

        - Float RGBA: Red, Green, Blue, Alpha

        - GrayA: Gray, Alpha

        - `Selection`: selectedness

        - LabA: L, a, b, Alpha

        - CMYKA: Cyan, Magenta, Yellow, Key, Alpha

        - XYZA: X, Y, Z, A

        - YCbCrA: Y, Cb, Cr, Alpha


        The byte array is a copy of the original node data. In Python, you can use bytes, bytearray and the struct module to interpret the data and construct, for instance, a Pillow Image object.


        If you read the pixeldata of a mask, a filter or generator layer, you get the selection bytes, which is one channel with values in the range from 0..255.


        If you want to change the pixels of a node you can write the pixels back after manipulation with `setPixelData()`. This will only succeed on nodes with writable pixel data, e.g not on groups or file layers.


        :returns: a QByteArray with the pixel data. The byte array may be empty.

        :param x: x position from where to start reading
        :param y: y position from where to start reading
        :param w: row length to read
        :param h: number of rows to read
        """

        ...

    def pixelDataAtTime(self, x: int, y: int, w: int, h: int, time: int) -> QByteArray:
        """
        pixelDataAtTime a basic function to get pixeldata from an animated node at a given time.

        :returns: a QByteArray with the pixel data. The byte array may be empty.

        :param x: the position from the left to start reading.
        :param y: the position from the top to start reader
        :param w: the row length to read
        :param h: the number of rows to read
        :param time: the frame number
        """

        ...

    def position(self) -> QPoint:
        """
        position returns the position of the paint device of this node. The position is always 0,0 unless the layer has been moved. If you want to know the topleft position of the rectangle around the actual non-transparent pixels in the node, use `bounds()`.

        :returns: the top-left position of the node
        """

        ...

    def projectionPixelData(self, x: int, y: int, w: int, h: int) -> QByteArray:
        """
        projectionPixelData reads the given rectangle from the `Node`'s projection (that is, what the node looks like after all sub-Nodes (like layers in a group or masks on a layer) have been applied, and returns it as a byte array. The pixel data starts top-left, and is ordered row-first.

        The byte array can be interpreted as follows: 8 bits images have one byte per channel, and as many bytes as there are channels. 16 bits integer images have two bytes per channel, representing an unsigned short. 16 bits float images have two bytes per channel, representing a half, or 16 bits float. 32 bits float images have four bytes per channel, representing a float.


        You can read outside the node boundaries; those pixels will be transparent black.


        The order of channels is:


        - Integer RGBA: Blue, Green, Red, Alpha

        - Float RGBA: Red, Green, Blue, Alpha

        - GrayA: Gray, Alpha

        - `Selection`: selectedness

        - LabA: L, a, b, Alpha

        - CMYKA: Cyan, Magenta, Yellow, Key, Alpha

        - XYZA: X, Y, Z, A

        - YCbCrA: Y, Cb, Cr, Alpha


        The byte array is a copy of the original node data. In Python, you can use bytes, bytearray and the struct module to interpret the data and construct, for instance, a Pillow Image object.


        If you read the projection of a mask, you get the selection bytes, which is one channel with values in the range from 0..255.


        If you want to change the pixels of a node you can write the pixels back after manipulation with `setPixelData()`. This will only succeed on nodes with writable pixel data, e.g not on groups or file layers.


        :returns: a QByteArray with the pixel data. The byte array may be empty.

        :param x: x position from where to start reading
        :param y: y position from where to start reading
        :param w: row length to read
        :param h: number of rows to read
        """

        ...

    def remove(self) -> bool:
        """
        remove removes this node from its parent image.
        """

        ...

    def removeChildNode(self, child: Node) -> bool:
        """
        removeChildNode removes the given node from the list of children.

        :param child: the node to be removed
        """

        ...

    def rotateNode(self, radians: float) -> None:
        """
        rotateNode rotate this layer by the given radians.

        :param radians: amount the layer should be rotated in, in radians.
        """

        ...

    def save(self, filename: str, xRes: float, yRes: float, exportConfiguration: InfoObject, exportRect: QRect = QRect()) -> bool:
        """
        save exports the given node with this filename. The extension of the filename determines the filetype.

        :returns: true if saving succeeded, false if it failed.

        :param filename: the filename including extension
        :param xRes: the horizontal resolution in pixels per pt (there are 72 pts in an inch)
        :param yRes: the horizontal resolution in pixels per pt (there are 72 pts in an inch)
        :param exportConfiguration: a configuration object appropriate to the file format.
        :param exportRect: the export bounds for saving a node as a QRect If `exportRect` is empty, then save exactBounds() of the node. If you'd like to save the image- aligned area of the node, just pass image->`bounds()` there. See Document->exportImage for `InfoObject` details.
        """

        ...

    def scaleNode(self, origin: QPointF, width: int, height: int, strategy: str) -> None:
        """
        scaleNode

        :param origin: the origin point
        :param width: the width
        :param height: the height
        :param strategy: the scaling strategy. There's several ones amongst these that aren't available in the regular UI. 

        - Hermite

        - Bicubic - Adds pixels using the color of surrounding pixels. Produces smoother tonal gradations than Bilinear.

        - Box - Replicate pixels in the image. Preserves all the original detail, but can produce jagged effects.

        - Bilinear - Adds pixels averaging the color values of surrounding pixels. Produces medium quality results when the image is scaled from half to two times the original size.

        - Bell

        - BSpline

        - Lanczos3 - Offers similar results than Bicubic, but maybe a little bit sharper. Can produce light and dark halos along strong edges.

        - Mitchell
        """

        ...

    def setAlphaLocked(self, value: bool) -> None:
        """
        setAlphaLocked set the layer to value if the node is paint layer.
        """

        ...

    def setBlendingMode(self, value: str) -> None:
        """
        setBlendingMode set the blending mode of the node to the given value

        See also: KoCompositeOpRegistry.h

        :param value: one of the string values from
        """

        ...

    def setChildNodes(self, nodes: list[Node]) -> None:
        """
        setChildNodes this replaces the existing set of child nodes with the new set.

        :param nodes: The list of nodes that will become children, bottom-up — the first node, is the bottom-most node in the stack.
        """

        ...

    def setCollapsed(self, collapsed: bool) -> None:
        """
        Sets the state of the node to the value of
        """

        ...

    def setColorLabel(self, index: int) -> None:
        """
        setColorLabel sets a color label index associated to the layer. The actual color of the label and the number of available colors is defined by `Krita` GUI configuration.

        :param index: an integer corresponding to the set of available color labels.
        """

        ...

    def setColorProfile(self, colorProfile: str) -> bool:
        """
        setColorProfile set the color profile of the image to the given profile. The profile has to be registered with krita and be compatible with the current color model and depth; the image data is `not` converted.

        :returns: if assigning the color profile worked
        """

        ...

    def setColorSpace(self, colorModel: str, colorDepth: str, colorProfile: str) -> bool:
        """
        setColorSpace convert the node to the given colorspace

        :param colorModel: A string describing the color model of the node: 

        - A: Alpha mask

        - RGBA: RGB with alpha channel (The actual order of channels is most often BGR!)

        - XYZA: XYZ with alpha channel

        - LABA: LAB with alpha channel

        - CMYKA: CMYK with alpha channel

        - GRAYA: Gray with alpha channel

        - YCbCrA: YCbCr with alpha channel
        :param colorDepth: A string describing the color depth of the image: 

        - U8: unsigned 8 bits integer, the most common type

        - U16: unsigned 16 bits integer

        - F16: half, 16 bits floating point. Only available if `Krita` was built with OpenEXR

        - F32: 32 bits floating point
        :param colorProfile: a valid color profile for this color model and color depth combination.
        """

        ...

    def setInheritAlpha(self, value: bool) -> None:
        """
        set the Inherit Alpha flag to the given value
        """

        ...

    def setLayerStyleFromAsl(self, asl: str) -> bool:
        """
        setLayerStyleFromAsl set a new layer style for this node.

        :returns: true if layer style was set, false if failed.

        :param aslContent: a string formatted in ASL format containing the layer style
        """

        ...

    def setLocked(self, value: bool) -> None:
        """
        set the Locked flag to the give value
        """

        ...

    def setName(self, name: str) -> None:
        """
        rename the `Node` to the given name
        """

        ...

    def setOpacity(self, value: int) -> None:
        """
        set the opacity of the `Node` to the given value. The opacity is a value between 0 and 255.
        """

        ...

    def setPinnedToTimeline(self, pinned: bool) -> None:
        """
        Sets whether or not node should be pinned to the Timeline Docker, regardless of selection activity.
        """

        ...

    def setPixelData(self, value: QByteArray, x: int, y: int, w: int, h: int) -> bool:
        """
        setPixelData writes the given bytes, of which there must be enough, into the `Node`, if the `Node` has writable pixel data:

        - paint layer: the layer's original pixels are overwritten

        - filter layer, generator layer, any mask: the embedded selection's pixels are overwritten. `Note:` for these


        File layers, Group layers, Clone layers cannot be written to. Calling setPixelData on those layer types will silently do nothing.


        :returns: true if writing the pixeldata worked

        :param value: the byte array representing the pixels. There must be enough bytes available. `Krita` will take the raw pointer from the QByteArray and start reading, not stopping before (number of channels * size of channel * w * h) bytes are read.
        :param x: the x position to start writing from
        :param y: the y position to start writing from
        :param w: the width of each row
        :param h: the number of rows to write
        """

        ...

    def setVisible(self, visible: bool) -> None:
        """
        Set the visibility of the current node to
        """

        ...

    def shearNode(self, angleX: float, angleY: float) -> None:
        """
        shearNode perform a shear operation on this node.

        :param angleX: the X-angle in degrees to shear by
        :param angleY: the Y-angle in degrees to shear by
        """

        ...

    def thumbnail(self, w: int, h: int) -> QImage:
        """
        thumbnail create a thumbnail of the given dimensions. The thumbnail is sized according to the layer dimensions, not the image dimensions. If the requested size is too big a null QImage is created. If the current node cannot generate a thumbnail, a transparent QImage of the requested size is generated.

        :returns: a QImage representing the layer contents.
        """

        ...

    def type(self) -> str:
        """
        type `Krita` has several types of nodes, split in layers and masks. Group layers can contain other layers, any layer can contain masks.

        :returns: The type of the node. Valid types are: 

        - paintlayer

        - grouplayer

        - filelayer

        - filterlayer

        - filllayer

        - clonelayer

        - vectorlayer

        - transparencymask

        - filtermask

        - transformmask

        - selectionmask

        - colorizemask
        If the `Node` object isn't wrapping a valid `Krita` layer or mask object, and empty string is returned.
        """

        ...

    def uniqueId(self) -> QUuid:
        """
        uniqueId uniqueId of the node

        :returns: a QUuid representing a unique id to identify the node
        """

        ...

    def visible(self) -> bool:
        """
        Check whether the current `Node` is visible in the layer stack
        """

        ...