# Generated by build.py — DO NOT EDIT

from typing import ClassVar
from PyQt5.QtCore import QObject, pyqtSignal
from krita._types.document import Document
from krita._types.view import View
from krita._types.window import Window


class Notifier:
    """
    The `Notifier` can be used to be informed of state changes in the `Krita` application.
    """

    def __init__(self, parent: QObject = None) -> None:
        ...

    def active(self) -> bool:
        """
        :returns: true if the `Notifier` is active.
        """

        ...

    def setActive(self, value: bool) -> None:
        """
        Enable or disable the `Notifier`
        """

        ...

    applicationClosing: ClassVar[pyqtSignal]  # applicationClosing is emitted when the application is about to close. This happens after any documents and windows are closed.

    configurationChanged: ClassVar[pyqtSignal]  # configurationChanged is emitted every time `Krita`'s configuration has changed.

    imageClosed: ClassVar[pyqtSignal]
    """
    imageClosed is emitted whenever the last view on an image is closed. The image does not exist anymore in `Krita`

    :param filename: the filename of the image.
    """

    imageCreated: ClassVar[pyqtSignal]  # imageCreated is emitted whenever a new image is created and registered with the application.

    imageSaved: ClassVar[pyqtSignal]
    """
    imageSaved is emitted whenever a document is saved.

    :param filename: the filename of the document that has been saved.
    """

    viewClosed: ClassVar[pyqtSignal]
    """
    viewClosed is emitted whenever a view is closed

    :param view: the view
    """

    viewCreated: ClassVar[pyqtSignal]
    """
    viewCreated is emitted whenever a new view is created.

    :param view: the view
    """

    windowCreated: ClassVar[pyqtSignal]  # windowIsCreated is emitted after main window is completely created

    windowIsBeingCreated: ClassVar[pyqtSignal]
    """
    windowCreated is emitted whenever a window is being created

    :param window: the window; this is called from the constructor of the window, before the xmlgui file is loaded
    """