# Generated by build.py — DO NOT EDIT

from typing import ClassVar
from PyQt5.QtCore import pyqtSignal
from PyQt5.QtWidgets import QWidget
from krita._types.managed_color import ManagedColor
from krita._types.palette import Palette
from krita._types.swatch import Swatch


class PaletteView:
    """
    The `PaletteView` class is a wrapper around a MVC method for handling palettes. This class shows a nice widget that can drag and drop, edit colors in a colorset and will handle adding and removing entries if you'd like it to.
    """

    def __init__(self, parent: QWidget = None) -> None:
        ...

    def addEntryWithDialog(self, color: ManagedColor) -> bool:
        """
        addEntryWithDialog This gives a simple dialog for adding colors, with options like adding name, id, and to which group the color should be added.

        :returns: whether it was successful.

        :param color: the default color to add
        """

        ...

    def addGroupWithDialog(self) -> bool:
        """
        addGroupWithDialog gives a little dialog to ask for the desired groupname.

        :returns: whether this was successful.
        """

        ...

    def removeSelectedEntryWithDialog(self) -> bool:
        """
        removeSelectedEntryWithDialog removes the selected entry. If it is a group, it pop up a dialog asking whether the colors should also be removed.

        :returns: whether this was successful
        """

        ...

    def setPalette(self, palette: Palette) -> None:
        """
        setPalette Set a new palette.
        """

        ...

    def trySelectClosestColor(self, color: ManagedColor) -> None:
        """
        trySelectClosestColor tries to select the closest color to the one given. It does not force a change on the active color.

        :param color: the color to compare to.
        """

        ...

    entrySelectedBackGround: ClassVar[pyqtSignal]  # entrySelectedBackGround fires when a swatch is selected with rightclick.

    entrySelectedForeGround: ClassVar[pyqtSignal]  # entrySelectedForeGround fires when a swatch is selected with leftclick.