# Generated by build.py — DO NOT EDIT

from PyQt5.QtCore import QObject
from krita._types.resource import Resource
from krita._types.swatch import Swatch


class Palette:
    """
    The `Palette` class `Palette` is a resource object that stores organised color data. It's purpose is to allow artists to save colors and store them.

    An example for printing all the palettes and the entries:


    ```
    import sys
    from krita import *

    resources = Application.resources("palette")

    for (k, v) in resources.items():
        print(k)
        palette = `Palette`(v)
        for x in range(palette.numberOfEntries()):
            entry = palette.`colorSetEntryByIndex`(x)
            print(x, entry.name(), entry.id(), entry.spotColor())
    ```
    """

    def __init__(self, resource: Resource, parent: QObject = None) -> None:
        ...

    def addEntry(self, entry: Swatch, groupName: str = "") -> None:
        """
        add a color entry to a group. Color is appended to the end.

        :param entry: the entry
        :param groupName: the name of the group to add to.
        """

        ...

    def addGroup(self, name: str) -> None:
        """
        `Palette` content can be organized in groups. This method allows to add a new group in palette.

        :param name: The name of the new group to add.
        """

        ...

    def changeGroupName(self, oldGroupName: str, newGroupName: str) -> None:
        """
        changeGroupName change the group name.

        DEPRECATED: use ``renameGroup()`` instead


        :returns: whether successful. Reasons for failure include not knowing have oldGroupName

        :param oldGroupName: the old groupname to change.
        :param newGroupName: the new name to change it into.
        """

        ...

    def colorSetEntryByIndex(self, index: int) -> Swatch:
        """
        colorSetEntryByIndex get the colorsetEntry from the global index.

        DEPRECATED: use ``entryByIndex()`` instead


        :returns: the colorset entry

        :param index: the global index
        """

        ...

    def colorSetEntryFromGroup(self, index: int, groupName: str) -> Swatch:
        """
        colorSetEntryFromGroup

        DEPRECATED: use ``entryByIndexFromGroup()`` instead


        :returns: the colorsetentry.

        :param index: index in the group.
        :param groupName: the name of the group to get the color from.
        """

        ...

    def colorsCountGroup(self, name: str) -> int:
        """
        colorsCountGroup

        :returns: the amount of filled colors within that group.

        :param name: of the group to check. Empty is the default group.
        """

        ...

    def colorsCountTotal(self) -> int:
        """
        number of filled colors (swatches) in palette NOTE: same as ``numberOfEntries()``

        :returns: total number of colors
        """

        ...

    def columnCount(self) -> int:
        """
        Palettes are defined in grids. The number of column define grid width. The number of rows will depend of columns and total number of entries.

        :returns: the number of columns this palette is set to use.
        """

        ...

    def comment(self) -> str:
        """
        the comment or description associated with the palette.

        :returns: A string for which value contains the comment/description of palette.
        """

        ...

    def entryByIndex(self, index: int) -> Swatch:
        """
        get color (swatch) from the global index.

        :returns: The `Swatch` color for given index.

        :param index: the global index
        """

        ...

    def entryByIndexFromGroup(self, index: int, groupName: str) -> Swatch:
        """
        get color (swatch) from the given group index.

        :returns: The `Swatch` color for given index within given group name.

        :param index: index in the group.
        :param groupName: the name of the group to get the color from.
        """

        ...

    def groupNames(self) -> list[str]:
        """
        `Palette` content can be organized in groups.

        :returns: The list of group names (list of string). This list follow the order the groups are defined in palette.
        """

        ...

    def moveGroup(self, groupName: str, groupNameInsertBefore: str = "") -> None:
        """
        Move the group `groupName` to position before group `groupNameInsertBefore`.

        :param groupName: group to move.
        :param groupNameInsertBefore: reference group for which `groupName` have to be moved before.
        """

        ...

    def numberOfEntries(self) -> int:
        """
        number of filled colors (swatches) in palette NOTE: same as ``colorsCountTotal()``

        :returns: total number of colors
        """

        ...

    def removeEntry(self, index: int) -> None:
        """
        Remove the color entry at the given index in this palette.

        :param index: index in this palette.
        """

        ...

    def removeEntryFromGroup(self, index: int, groupName: str) -> None:
        """
        Remove the color entry at the given index in the given group.

        :param index: index in the group.
        :param groupName: the name of the group to remove the entry from.
        """

        ...

    def removeGroup(self, name: str, keepColors: bool = True) -> None:
        """
        `Palette` content can be organized in groups. This method allows to remove an existing group from palette.

        :param name: The name of the group to remove.
        :param keepColors: whether or not to delete all the colors inside, or to move them to the default group.
        """

        ...

    def renameGroup(self, oldGroupName: str, newGroupName: str) -> None:
        """
        rename a group

        :param oldGroupName: the old groupname to change.
        :param newGroupName: the new name to change it into.
        """

        ...

    def rowCount(self) -> int:
        """
        The number of rows in the palette grid. If the palette has groups, the row count is defined by the groups' row count. Otherwise, it's determined by the number of columns and entries.

        :returns: the number of rows this palette has.
        """

        ...

    def rowCountGroup(self, name: str) -> int:
        """
        The number of rows defined in the given group.

        :returns: the number of rows this group is set to use.

        :param name: of the group to check.
        """

        ...

    def save(self) -> bool:
        """
        save the palette

        WARNING: this method does nothing and need to be implemented!


        :returns: always False
        """

        ...

    def setColumnCount(self, columns: int) -> None:
        """
        Palettes are defined in grids. The number of column define grid width, this value can be defined. The number of rows will depend of columns and total number of entries.

        :param columns: Set the amount of columns this palette should use.
        """

        ...

    def setComment(self, comment: str) -> None:
        """
        the comment or description associated with the palette.

        :param comment: set the comment or description associated with the palette.
        """

        ...

    def setRowCountGroup(self, rows: int, name: str) -> None:
        """
        Set the number of rows defined in the given group.

        :param rows: the amount of rows this group should use.
        :param name: of the group to modify.
        """

        ...

    def slotCount(self) -> int:
        """
        number of slots for swatches in palette This includes any empty slots not filled by a color.

        :returns: total number of slots
        """

        ...

    def slotCountGroup(self, name: str) -> int:
        """
        number of slots for swatches in group This includes any empty slots not filled by a color.

        :returns: number of slots in group

        :param name: of the group to check. Empty is the default group.
        """

        ...