# Generated by build.py — DO NOT EDIT

from typing import ClassVar
from PyQt5.QtCore import pyqtSignal
from PyQt5.QtWidgets import QWidget
from krita._types._opaque import KisPresetChooser
from krita._types.resource import Resource


class PresetChooser(KisPresetChooser):
    """
    The `PresetChooser` widget wraps the KisPresetChooser widget. The widget provides for selecting brush presets. It has a tagging bar and a filter field. It is not automatically synchronized with the currently selected preset in the current Windows.
    """

    def __init__(self, parent: QWidget = None) -> None:
        ...

    def currentPreset(self) -> Resource:
        """
        :returns: a `Resource` wrapper around the currently selected preset.
        """

        ...

    def setCurrentPreset(self, resource: Resource) -> None:
        """
        Make the given preset active.
        """

        ...

    presetClicked: ClassVar[pyqtSignal]  # Emitted whenever a user clicks on the given preset.

    presetSelected: ClassVar[pyqtSignal]  # Emitted whenever a user selects the given preset.