# Generated by build.py — DO NOT EDIT

from krita._types.resource import Resource


class Preset:
    """
    The `Preset` class `Preset` is a resource object that stores brush preset data.

    An example for printing the current brush preset and all its settings:


    ```
    from krita import *

    view = Krita.instance().activeWindow().activeView()
    preset = Preset(view.currentBrushPreset())

    print ( preset.toXML() )
    ```
    """

    def __init__(self, resource: Resource) -> None:
        ...

    def fromXML(self, xml: str) -> None:
        """
        fromXML convert the preset settings into a preset formatted xml.

        :param xml: valid xml preset string.
        """

        ...

    def toXML(self) -> str:
        """
        toXML convert the preset settings into a preset formatted xml.

        :returns: the xml in a string.
        """

        ...