# Generated by build.py — DO NOT EDIT

from typing import overload
from PyQt5.QtCore import QObject
from PyQt5.QtGui import QImage
from krita._types._opaque import KoResourceSP


class Resource:
    """
    A `Resource` represents a gradient, pattern, brush tip, brush preset, palette or workspace definition.


    ```
    allPresets = Application.resources("preset")
    for preset in allPresets:
        print(preset.name())
    ```


    Resources are identified by their type, name and filename. If you want to change the contents of a resource, you should read its data using data(), parse it and write the changed contents back.
    """

    @overload
    def Resource(self, resourceId: int, type: str, name: str, filename: str, image: QImage, parent: QObject = None) -> None: ...

    @overload
    def Resource(self, resource: KoResourceSP, type: str, parent: QObject = None) -> None: ...

    @overload
    def Resource(self, rhs: Resource) -> None: ...

    def filename(self) -> str:
        """
        The filename of the resource, if present. Not all resources are loaded from files.
        """

        ...

    def image(self) -> QImage:
        """
        An image that can be used to represent the resource in the user interface. For some resources, like patterns, the image is identical to the resource, for others it's a mere icon.
        """

        ...

    def name(self) -> str:
        """
        The user-visible name of the resource.
        """

        ...

    def setImage(self, image: QImage) -> None:
        """
        Change the image for this resource.
        """

        ...

    def setName(self, value: str) -> None:
        """
        setName changes the user-visible name of the current resource.
        """

        ...

    def type(self) -> str:
        """
        Return the type of this resource. Valid types are: 

        - pattern: a raster image representing a pattern

        - gradient: a gradient

        - brush: a brush tip

        - preset: a brush preset

        - palette: a color set

        - workspace: a workspace definition.
        """

        ...