# Generated by build.py — DO NOT EDIT

from typing import ClassVar
from PyQt5.QtCore import QPoint, QRect, pyqtSignal
from PyQt5.QtGui import QColor, QImage, QTransform
from PyQt5.QtWidgets import QWidget
from krita._types.view import View


class Scratchpad:
    """
    The `Scratchpad` class A scratchpad is a type of blank canvas area that can be painted on with the normal painting devices.
    """

    def __init__(self, view: View, defaultColor: QColor, parent: QWidget = None) -> None:
        ...

    def canvasZoomLink(self) -> bool:
        """
        return if scratchpad zoom level is linked with current view zoom level

        :returns: return True if connection between the zoom of the canvas and scratchpad (so they zoom in sync) is active
        """

        ...

    def clear(self) -> None:
        """
        Clears out scratchpad with color specified set during setup.
        """

        ...

    def contentBounds(self) -> QRect:
        """
        The content of scratchpad can be bigger or smaller than scratchpad dimension. The bounds return the area in which there's some content.

        :returns: scratchpad content bounds as a QRect
        """

        ...

    def copyScratchpadImageData(self) -> QImage:
        """
        Take what is on the scratchpad area and grab image.

        :returns: the image data from the scratchpad
        """

        ...

    def fillBackground(self) -> None:
        """
        Fill the entire scratchpad with current background color.
        """

        ...

    def fillDefault(self) -> None:
        """
        Fill the entire scratchpad with default color.
        """

        ...

    def fillDocument(self, fullContent: bool = True) -> None:
        """
        Fill the entire scratchpad with current document projection content.

        :param fullContent: when True, full document projection is loaded in scratchpad, otherwise only content matching scratchpad viewport is loaded
        """

        ...

    def fillForeground(self) -> None:
        """
        Fill the entire scratchpad with current foreground color.
        """

        ...

    def fillGradient(self, gradientVectorStart: QPoint = QPoint(), gradientVectorEnd: QPoint = QPoint(), gradientShape: str = 'linear', gradientRepeat: str = 'none', reverseGradient: bool = False, dither: bool = False) -> None:
        """
        Fill the entire scratchpad with current gradient.

        :param gradientVectorStart: is a QPoint to define origin of gradient Set an empty QPoint() to use default scratchpad top-left
        :param gradientVectorEnd: is a QPoint to define end of gradient set an empty QPoint() to use default scratchpad bottom-right
        :param gradientShape: define which gradient to apply, can be:

        - "linear"
        - "bilinear"
        - "radial"
        - "square"
        - "conical"
        - "conicalSymmetric"
        - "spiral"
        - "reverseSpiral"
        - "polygonal"
        :param gradientRepeat: define how to repeat gradient, can be:

        - "none"
        - "alternate"
        - "forwards"
        :param reverseGradient: a boolean to define if gradient is reversed or not
        :param dither: a boolean to define if gradient is dithered or not
        """

        ...

    def fillLayer(self, fullContent: bool = True) -> None:
        """
        Fill the entire scratchpad with current layer content.

        :param fullContent: when True, full layer content is loaded in scratchpad, otherwise only content matching scratchpad viewport is loaded
        """

        ...

    def fillPattern(self, transform: QTransform = QTransform()) -> None:
        """
        Fill the entire scratchpad with current pattern.

        :param transform: is QTransform that let define pattern scale/rotation property
        """

        ...

    def fillTransparent(self) -> None:
        """
        Fill the entire scratchpad with a transparent color.
        """

        ...

    def linkCanvasZoom(self, value: bool) -> None:
        """
        DEPRECATED — USE `setCanvasZoomLink()` instead Makes a connection between the zoom of the canvas and scratchpad area so they zoom in sync.

        :param value: If True (default) the scratchpad will share the current view zoom level. If False, then use scratchpad scale methods to define current zoom level
        """

        ...

    def loadScratchpadImage(self, image: QImage) -> None:
        """
        Load image data to the scratchpad.

        :param image: Image object to load
        """

        ...

    def panCenter(self) -> None:
        """
        pan scratchpad content to center content in viewport
        """

        ...

    def panTo(self, x: int, y: int) -> None:
        """
        pan scratchpad content to top-left position of scratchpad viewport Provided value are absolute

        :param x: abscissa position to pan to
        :param y: ordinate position to pan to
        """

        ...

    def scale(self) -> float:
        """
        return current zoom level applied on scratchpad (whatever the zoom source is: view zoom level or set manually)

        :returns: a float value (1.00 = 100%)
        """

        ...

    def scaleReset(self) -> None:
        """
        reset scale and pan to origin Note: call method is ignored if `canvasZoomLink()` is True
        """

        ...

    def scaleToFit(self) -> None:
        """
        calculate scale automatically to fit scratchpad content in scratchpad viewport Note: call method is ignored if `canvasZoomLink()` is True
        """

        ...

    def setCanvasZoomLink(self, value: bool) -> None:
        """
        Makes a connection between the zoom of the canvas and scratchpad area so they zoom in sync.

        :param value: If True (default) the scratchpad will share the current view zoom level. If False, then use scratchpad scale methods to define current zoom level
        """

        ...

    def setFillColor(self, color: QColor) -> None:
        """
        Define default fill color for scratchpad.

        :param Color: to fill the canvas with
        """

        ...

    def setMode(self, modeName: str) -> None:
        """
        Manually set what mode scratchpad is in. Ignored if "setModeManually is set to false.

        :param modeName: Available options are:

        - "painting"
        - "panning"
        - "colorsampling"
        """

        ...

    def setModeManually(self, value: bool) -> None:
        """
        Switches between a GUI controlling the current mode and when mouse clicks control mode.

        :param value: Set to True allows GUI to control the mode with explicitly setting mode
        """

        ...

    def setScale(self, scale: float) -> bool:
        """
        allow to manually set scratchpad zoom level Note: call method is ignored if `canvasZoomLink()` is True,

        :returns: if scale has been applied return True, otherwise return False

        :param scale: zoom level to apply (1.00 = 100%)
        """

        ...

    def viewportBounds(self) -> QRect:
        """
        The viewport indicates which part of scratchpad content is visible. It takes in account the current translation & scale.

        Example 1:

        - `Scratchpad` size: 500x500
        - `Scratchpad` content: 2000x2000
        - `Scratchpad` scale: 1.0
        - `Scratchpad` pan: 0, 0 Returned viewport is a QRect(0, 0, 500, 500) matching content really visible in scratchpad. If scale is 2.00, returned viewport will be QRect(0, 0, 250, 250) If scale is 0.50, returned viewport will be QRect(0, 0, 1000, 1000)


        Example 2:

        - `Scratchpad` size: 500x500
        - `Scratchpad` content: 2000x2000
        - `Scratchpad` scale: 2.0
        - `Scratchpad` pan: 500, 1500 Returned viewport is a QRect(500, 1500, 250, 250) matching content really visible in scratchpad.


        :returns: scratchpad viewport bounds as a QRect
        """

        ...

    contentChanged: ClassVar[pyqtSignal]  # signal is emitted when scratchpad content is changed (stroke or fill)

    scaleChanged: ClassVar[pyqtSignal]
    """
    signal is emitted when scratchpad scale is changed (from zoom canvas or manually)

    :param scale: updated scale value (1.00 = 100%)
    """

    viewportChanged: ClassVar[pyqtSignal]
    """
    signal is emitted when scratchpad viewport has been modified (pan, zoom)

    :param rect: new viewport bounds
    """