# Generated by build.py — DO NOT EDIT

from typing import overload
from PyQt5.QtCore import QByteArray, QObject
from krita._types._opaque import KisSelectionSP
from krita._types.node import Node


class Selection:
    """
    `Selection` represents a selection on `Krita`. A selection is not necessarily associated with a particular `Node` or Image.


    ```
    from krita import *

    d = Application.activeDocument()
    n = d.activeNode()
    r = n.bounds() 
    s = Selection()
    s.select(r.width() / 3, r.height() / 3, r.width() / 3, r.height() / 3, 255)
    s.cut(n)
    ```
    """

    @overload
    def Selection(self, selection: KisSelectionSP, parent: QObject = None) -> None: ...

    @overload
    def Selection(self, parent: QObject = None) -> None: ...

    def add(self, selection: Selection) -> None:
        """
        Add the given selection's selected pixels to the current selection.
        """

        ...

    def border(self, xRadius: int, yRadius: int) -> None:
        """
        Border the selection with the given radius.
        """

        ...

    def clear(self) -> None:
        """
        Make the selection entirely unselected.
        """

        ...

    def contract(self, value: int) -> None:
        """
        Make the selection's width and height smaller by the given value. This will not move the selection's top-left position.
        """

        ...

    def copy(self, node: Node) -> None:
        """
        copy copies the area defined by the selection from the node to the clipboard.

        :param node: the node from where the pixels will be copied.
        """

        ...

    def cut(self, node: Node) -> None:
        """
        cut erases the area defined by the selection from the node and puts a copy on the clipboard.

        :param node: the node from which the selection will be cut.
        """

        ...

    def dilate(self) -> None:
        """
        Dilate the selection with a radius of 1 pixel.
        """

        ...

    def duplicate(self) -> Selection:
        """
        :returns: a duplicate of the selection
        """

        ...

    def erode(self) -> None:
        """
        Erode the selection with a radius of 1 pixel.
        """

        ...

    def feather(self, radius: int) -> None:
        """
        Feather the selection with the given radius.
        """

        ...

    def grow(self, xradius: int, yradius: int) -> None:
        """
        Grow the selection with the given radius.
        """

        ...

    def height(self) -> int:
        """
        :returns: the height of the selection
        """

        ...

    def intersect(self, selection: Selection) -> None:
        """
        Intersect the given selection with this selection.
        """

        ...

    def invert(self) -> None:
        """
        Invert the selection.
        """

        ...

    def move(self, x: int, y: int) -> None:
        """
        Move the selection's top-left corner to the given coordinates.
        """

        ...

    def paste(self, destination: Node, x: int, y: int) -> None:
        """
        paste pastes the content of the clipboard to the given node, limited by the area of the current selection.

        :param destination: the node where the pixels will be written
        :param x: the x position at which the clip will be written
        :param y: the y position at which the clip will be written
        """

        ...

    def pixelData(self, x: int, y: int, w: int, h: int) -> QByteArray:
        """
        pixelData reads the given rectangle from the `Selection`'s mask and returns it as a byte array. The pixel data starts top-left, and is ordered row-first.

        The byte array will contain one byte for every pixel, representing the selectedness. 0 is totally unselected, 255 is fully selected.


        You can read outside the `Selection`'s boundaries; those pixels will be unselected.


        The byte array is a copy of the original selection data. 
        :returns: a QByteArray with the pixel data. The byte array may be empty.

        :param x: x position from where to start reading
        :param y: y position from where to start reading
        :param w: row length to read
        :param h: number of rows to read
        """

        ...

    def replace(self, selection: Selection) -> None:
        """
        Replace the current selection's selection with the one of the given selection.
        """

        ...

    def resize(self, w: int, h: int) -> None:
        """
        Resize the selection to the given width and height. The top-left position will not be moved.
        """

        ...

    def select(self, x: int, y: int, w: int, h: int, value: int) -> None:
        """
        Select the given area. The value can be between 0 and 255; 0 is totally unselected, 255 is totally selected.
        """

        ...

    def selectAll(self, node: Node, value: int) -> None:
        """
        Select all pixels in the given node. The value can be between 0 and 255; 0 is totally unselected, 255 is totally selected.
        """

        ...

    def setPixelData(self, value: QByteArray, x: int, y: int, w: int, h: int) -> None:
        """
        setPixelData writes the given bytes, of which there must be enough, into the `Selection`.

        :param value: the byte array representing the pixels. There must be enough bytes available. `Krita` will take the raw pointer from the QByteArray and start reading, not stopping before (w * h) bytes are read.
        :param x: the x position to start writing from
        :param y: the y position to start writing from
        :param w: the width of each row
        :param h: the number of rows to write
        """

        ...

    def shrink(self, xRadius: int, yRadius: int, edgeLock: bool) -> None:
        """
        Shrink the selection with the given radius.
        """

        ...

    def smooth(self) -> None:
        """
        Smooth the selection.
        """

        ...

    def subtract(self, selection: Selection) -> None:
        """
        Subtract the given selection's selected pixels from the current selection.
        """

        ...

    def symmetricdifference(self, selection: Selection) -> None:
        """
        Intersect with the inverse of the given selection with this selection.
        """

        ...

    def width(self) -> int:
        """
        :returns: the width of the selection
        """

        ...

    def x(self) -> int:
        """
        :returns: the left-hand position of the selection.
        """

        ...

    def y(self) -> int:
        """
        :returns: the top position of the selection.
        """

        ...