# Generated by build.py — DO NOT EDIT

from typing import overload
from PyQt5.QtCore import QObject
from krita._types._opaque import KisImageSP
from krita._types._opaque import KisSelectionMaskSP
from krita._types.node import Node
from krita._types.selection import Selection


class SelectionMask(Node):
    """
    The `SelectionMask` class A selection mask is a mask type node that can be used to store selections. In the gui, these are referred to as local selections.

    A selection mask can hold both raster and vector selections, though the API only supports raster selections.
    """

    @overload
    def SelectionMask(self, image: KisImageSP, name: str, parent: QObject = None) -> None: ...

    @overload
    def SelectionMask(self, image: KisImageSP, mask: KisSelectionMaskSP, parent: QObject = None) -> None: ...

    def selection(self) -> Selection:
        ...

    def setSelection(self, selection: Selection) -> None:
        ...

    def type(self) -> str:
        """
        type `Krita` has several types of nodes, split in layers and masks. Group layers can contain other layers, any layer can contain masks.

        :returns: selectionmask
        If the `Node` object isn't wrapping a valid `Krita` layer or mask object, and empty string is returned.
        """

        ...