# Generated by build.py — DO NOT EDIT

from PyQt5.QtCore import QObject, QPointF, QRectF
from PyQt5.QtGui import QTransform
from krita._types._opaque import KoShape


class Shape:
    """
    The `Shape` class The shape class is a wrapper around `Krita`'s vector objects.

    Some example code to parse through interesting information in a given vector layer with shapes. 
    ```
    import sys
    from krita import *

    doc = Application.activeDocument()

    root = doc.rootNode()

    for layer in root.childNodes():
        print (str(layer.type())+" "+str(layer.name()))
        if (str(layer.type())=="vectorlayer"):
            for shape in layer.shapes():
                print(shape.`name`())
                print(shape.`toSvg`())
    ```
    """

    def __init__(self, shape: KoShape, parent: QObject = None) -> None:
        ...

    def absoluteTransformation(self) -> QTransform:
        """
        transformation the 2D transformation matrix of the shape including all grandparent transforms.

        :returns: the 2D transformation matrix.
        """

        ...

    def boundingBox(self) -> QRectF:
        """
        boundingBox the bounding box of the shape in points

        :returns: RectF containing the bounding box.
        """

        ...

    def deselect(self) -> None:
        """
        deselect deselects the shape.
        """

        ...

    def geometryProtected(self) -> bool:
        """
        geometryProtected

        :returns: whether the shape is protected from user changing the shape geometry.
        """

        ...

    def isSelected(self) -> bool:
        """
        isSelected

        :returns: whether the shape is selected.
        """

        ...

    def name(self) -> str:
        """
        name

        :returns: the name of the shape
        """

        ...

    def parentShape(self) -> Shape:
        """
        parentShape

        :returns: the parent `GroupShape` of the current shape.
        """

        ...

    def position(self) -> QPointF:
        """
        position the position of the shape in points.

        :returns: the position of the shape in points.
        """

        ...

    def remove(self) -> bool:
        """
        remove delete the shape.
        """

        ...

    def select(self) -> None:
        """
        select selects the shape.
        """

        ...

    def selectable(self) -> bool:
        """
        selectable

        :returns: whether the shape is user selectable.
        """

        ...

    def setGeometryProtected(self, protect: bool) -> None:
        """
        setGeometryProtected

        :param protect: whether the shape should be geometry protected from the user.
        """

        ...

    def setName(self, name: str) -> None:
        """
        setName

        :param name: which name the shape should have.
        """

        ...

    def setPosition(self, point: QPointF) -> None:
        """
        setPosition set the position of the shape.

        :param point: the new position in points
        """

        ...

    def setSelectable(self, selectable: bool) -> None:
        """
        setSelectable

        :param selectable: whether the shape should be user selectable.
        """

        ...

    def setTransformation(self, matrix: QTransform) -> None:
        """
        setTransformation set the 2D transformation matrix of the shape.

        :param matrix: the new 2D transformation matrix.
        """

        ...

    def setVisible(self, visible: bool) -> None:
        """
        setVisible

        :param visible: whether the shape should be visible.
        """

        ...

    def setZIndex(self, zindex: int) -> None:
        """
        setZIndex

        :param zindex: set the shape zindex value.
        """

        ...

    def toSvg(self, prependStyles: bool = False, stripTextMode: bool = True) -> str:
        """
        toSvg convert the shape to svg, will not include style definitions.

        :returns: the svg in a string.

        :param prependStyles: prepend the style data. Default: false
        :param stripTextMode: enable strip text mode. Default: true
        """

        ...

    def transformation(self) -> QTransform:
        """
        transformation the 2D transformation matrix of the shape.

        :returns: the 2D transformation matrix.
        """

        ...

    def type(self) -> str:
        """
        type

        :returns: the type of shape.
        """

        ...

    def update(self) -> None:
        """
        update queue the shape update.
        """

        ...

    def updateAbsolute(self, box: QRectF) -> None:
        """
        updateAbsolute queue the shape update in the specified rectangle.

        :param box: the RectF rectangle to update.
        """

        ...

    def visible(self) -> bool:
        """
        visible

        :returns: whether the shape is visible.
        """

        ...

    def zIndex(self) -> int:
        """
        zIndex

        :returns: the zindex of the shape.
        """

        ...