# Generated by build.py — DO NOT EDIT

from typing import ClassVar
from PyQt5.QtCore import pyqtSignal
from PyQt5.QtWidgets import QWidget
from krita._types.int_parse_spin_box import IntParseSpinBox


class SliderSpinBox(IntParseSpinBox):
    """
    This class is a wrapper around KisSliderSpinBox, a spinbox in which you can click and drag to set the value, with a slider like bar displayed inside. The widget itself is accessed with the `widget()` function.

    The value can be set by click and dragging with the mouse or pen or by typing in with the keyboard. To enter the edit mode, in which the keyboard can be used, one has to right-click inside the spinbox or click and hold the pointer inside or press the enter key. To leave the edit mode, one can press the enter key again, in which case the value is committed, or press the escape key, in which case the value is rejected.


    When dragging with the pointer, one can fine tune the value by dragging far away vertically from the spinbox. The farther the pointer is, the slower the value will change. If the pointer is inside the spinbox plus a certain margin, the value will not be scaled. By pressing the shift key the slow down will be even more pronounced and by pressing the control key the value will snap to the increment set by `setFastSliderStep`. The two keys can be used at the same time.


    A "soft range" can be set to make the slider display only a sub-range of the spinbox range. This way one can have a large range but display and set with the pointer and with more precision only the most commonly used sub-set of values. A value outside the "soft range" can be set by entering the edit mode and using the keyboard. The "soft range" is considered valid if the "soft maximum" is greater than the "soft minimum".
    """

    def __init__(self) -> None:
        ...

    def fastSliderStep(self) -> int:
        """
        Get the value to which multiples the spinbox value snaps when the control key is pressed.

        :returns: the value to which multiples the spinbox value snaps when the control key is pressed

        See also: `setFastSliderStep(int)`
        """

        ...

    def isDragging(self) -> bool:
        """
        Get if the user is currently dragging the slider with the pointer.

        :returns: true if the user is currently dragging the slider with the pointer, false otherwise
        """

        ...

    def setBlockUpdateSignalOnDrag(self, newBlockUpdateSignalOnDrag: bool) -> None:
        """
        Set if the spinbox should not Q_EMIT signals when dragging the slider.

        This is useful to prevent multiple updates when changing the value if the update operation is costly. A valueChanged signal will be emitted when the pointer is released from the slider.

        :param newBlockUpdateSignalOnDrag: true if the spinbox should not emit signals when dragging the slider. false otherwise
        """

        ...

    def setExponentRatio(self, newExponentRatio: float) -> None:
        """
        Set the exponent used by a power function to modify the values as a function of the horizontal position.

        This allows having more values concentrated in one side of the slider than the other

        :param newExponentRatio: the new exponent to be used by the power function
        """

        ...

    def setFastSliderStep(self, newFastSliderStep: int) -> None:
        """
        Set the value to which multiples the spinbox value snaps when the control key is pressed.

        See also: `fastSliderStep() const`

        :param newFastSliderStep: value to which multiples the spinbox value snaps when the control key is pressed
        """

        ...

    def setMaximum(self, newMaximum: int, computeNewFastSliderStep: bool = True) -> None:
        """
        Set the maximum value of the range.

        The soft range will be adapted to fit inside the range 

        See also: setRange(int,int)

        See also: setMinimum(int)

        :param newMaximum: the new maximum value
        :param computeNewFastSliderStep: true if a new "fast slider step" must be computed based on the range
        """

        ...

    def setMinimum(self, newMinimum: int, computeNewFastSliderStep: bool = True) -> None:
        """
        Set the minimum value of the range.

        The soft range will be adapted to fit inside the range 

        See also: setRange(int,int)

        See also: setMaximum(int)

        :param newMinimum: the new minimum value
        :param computeNewFastSliderStep: true if a new "fast slider step" must be computed based on the range
        """

        ...

    def setRange(self, newMinimum: int, newMaximum: int, computeNewFastSliderStep: bool = True) -> None:
        """
        Set the minimum and the maximum values of the range, computing a new "fast slider step" based on the range if required.

        The soft range will be adapted to fit inside the range 

        See also: setMinimum(int)

        See also: setMaximum(int)

        :param newMinimum: the new minimum value
        :param newMaximum: the new maximum value
        :param computeNewFastSliderStep: true if a new "fast slider step" must be computed based on the range
        """

        ...

    def setSoftMaximum(self, newSoftMaximum: int) -> None:
        """
        Set the maximum value of the soft range.

        See also: `setSoftRange(int,int)`

        See also: `setSoftMinimum(int)`

        See also: `softMinimum() const`

        See also: `softMaximum() const`

        :param newSoftMaximum: the new maximum value
        """

        ...

    def setSoftMinimum(self, newSoftMinimum: int) -> None:
        """
        Set the minimum value of the soft range.

        See also: `setSoftRange(int,int)`

        See also: `setSoftMaximum(int)`

        See also: `softMinimum() const`

        See also: `softMaximum() const`

        :param newSoftMinimum: the new minimum value
        """

        ...

    def setSoftRange(self, newSoftMinimum: int, newSoftMaximum: int) -> None:
        """
        Set the minimum and the maximum values of the soft range.

        See also: `setSoftMinimum(int)`

        See also: `setSoftMaximum(int)`

        See also: `softMinimum() const`

        See also: `softMaximum() const`

        :param newSoftMinimum: the new minimum value
        :param newSoftMaximum: the new maximum value
        """

        ...

    def setValue(self, newValue: int) -> None:
        """
        Set the value.

        :param newValue: the new value
        """

        ...

    def softMaximum(self) -> int:
        """
        Get the maximum value of the "soft range".

        :returns: the maximum value of the "soft range"

        See also: `setSoftMaximum(int)`

        See also: `setSoftRange(int, int)`

        See also: `softMinimum`) const
        """

        ...

    def softMinimum(self) -> int:
        """
        Get the minimum value of the "soft range".

        :returns: the minimum value of the "soft range"

        See also: `setSoftMinimum(int)`

        See also: `setSoftRange(int, int)`

        See also: `softMaximum() const `
        """

        ...

    def widget(self) -> QWidget:
        """
        Get the internal KisSliderSpinBox as a QWidget, so it may be added to a UI.

        :returns: the internal KisSliderSpinBox as a QWidget
        """

        ...

    draggingFinished: ClassVar[pyqtSignal]