# Generated by build.py — DO NOT EDIT

from typing import overload
from PyQt5.QtCore import QObject
from krita._types.managed_color import ManagedColor


class Swatch:
    """
    The `Swatch` class is a thin wrapper around the KisSwatch class.

    A `Swatch` is a single color that is part of a palette, that has a name and an id. A `Swatch` color can be a spot color.
    """

    @overload
    def Swatch(self, parent: QObject = None) -> None: ...

    @overload
    def Swatch(self, rhs: Swatch, parent: QObject = None) -> None: ...

    def color(self) -> ManagedColor:
        ...

    def id(self) -> str:
        ...

    def isValid(self) -> bool:
        ...

    def name(self) -> str:
        ...

    def setColor(self, color: ManagedColor) -> None:
        ...

    def setId(self, id: str) -> None:
        ...

    def setName(self, name: str) -> None:
        ...

    def setSpotColor(self, spotColor: bool) -> None:
        ...

    def spotColor(self) -> bool:
        ...