# Generated by build.py — DO NOT EDIT

from typing import overload
from PyQt5.QtCore import QObject
from krita._types._opaque import KisImageSP
from krita._types._opaque import KisTransparencyMaskSP
from krita._types.node import Node
from krita._types.selection import Selection


class TransparencyMask(Node):
    """
    The `TransparencyMask` class A transparency mask is a mask type node that can be used to show and hide parts of a layer.
    """

    @overload
    def TransparencyMask(self, image: KisImageSP, name: str, parent: QObject = None) -> None: ...

    @overload
    def TransparencyMask(self, image: KisImageSP, mask: KisTransparencyMaskSP, parent: QObject = None) -> None: ...

    def selection(self) -> Selection:
        ...

    def setSelection(self, selection: Selection) -> None:
        ...

    def type(self) -> str:
        """
        type `Krita` has several types of nodes, split in layers and masks. Group layers can contain other layers, any layer can contain masks.

        :returns: transparencymask
        If the `Node` object isn't wrapping a valid `Krita` layer or mask object, and empty string is returned.
        """

        ...