# Generated by build.py — DO NOT EDIT

from typing import overload
from PyQt5.QtCore import QObject, QPointF, QRectF
from krita._types._opaque import KisImageSP
from krita._types._opaque import KisShapeLayerSP
from krita._types._opaque import KoShapeControllerBase
from krita._types.node import Node
from krita._types.shape import Shape


class VectorLayer(Node):
    """
    The `VectorLayer` class A vector layer is a special layer that stores and shows vector shapes.

    Vector shapes all have their coordinates in points, which is a unit that represents 1/72th of an inch. Keep this in mind wen parsing the bounding box and position data.
    """

    @overload
    def VectorLayer(self, shapeController: KoShapeControllerBase, image: KisImageSP, name: str, parent: QObject = None) -> None: ...

    @overload
    def VectorLayer(self, layer: KisShapeLayerSP, parent: QObject = None) -> None: ...

    def addShapesFromSvg(self, svg: str) -> list[Shape]:
        """
        addShapesFromSvg add shapes to the layer from a valid svg.

        :returns: the list of shapes added to the layer from the svg.

        :param svg: valid svg string.
        """

        ...

    def createGroupShape(self, name: str, shapes: list[Shape]) -> Shape:
        """
        createGroupShape combine a list of top level shapes into a group.

        :returns: if successful, a `GroupShape` object will be returned.

        :param name: the name of the shape.
        :param shapes: list of top level shapes.
        """

        ...

    def isAntialiased(self) -> bool:
        """
        return antialiasing status for the Vector layer

        :returns: True if antialiasing is active for the layer
        """

        ...

    def setAntialiased(self, antialiased: bool) -> None:
        """
        set antialiasing status for the Vector layer

        :param antialiased: set to True to activate antialiasing
        """

        ...

    def shapeAtPosition(self, position: QPointF) -> Shape:
        """
        shapeAtPoint check if the position is located within any non-group shape's boundingBox() on the current layer.

        :returns: the shape at the position, or None if no shape is found.

        :param position: a QPointF of the position.
        """

        ...

    def shapes(self) -> list[Shape]:
        """
        shapes

        :returns: the list of top-level shapes in this vector layer.
        """

        ...

    def shapesInRect(self, rect: QRectF, omitHiddenShapes: bool = True, containedMode: bool = False) -> list[Shape]:
        """
        shapeInRect get all non-group shapes that the shape's boundingBox() intersects or is contained within a given rectangle on the current layer.

        :returns: returns a list of shapes.

        :param rect: a QRectF
        :param omitHiddenShapes: true if non-visible() shapes should be omitted, false if they should be included. `omitHiddenShapes` defaults to true.
        :param containedMode: false if only shapes that are within or intersect with the outline should be included, true if only shapes that are fully contained within the outline should be included. `containedMode` defaults to false
        """

        ...

    def toSvg(self) -> str:
        """
        toSvg convert the shapes in the layer to svg.

        :returns: the svg in a string.
        """

        ...

    def type(self) -> str:
        """
        type `Krita` has several types of nodes, split in layers and masks. Group layers can contain other layers, any layer can contain masks.

        :returns: vectorlayer
        """

        ...