# Generated by build.py — DO NOT EDIT

from PyQt5.QtCore import QObject
from PyQt5.QtGui import QIcon, QTransform
from krita._types._opaque import KisView
from krita._types.canvas import Canvas
from krita._types.document import Document
from krita._types.managed_color import ManagedColor
from krita._types.node import Node
from krita._types.resource import Resource
from krita._types.window import Window


class View:
    """
    `View` represents one view on a document. A document can be shown in more than one view at a time.
    """

    def __init__(self, view: KisView, parent: QObject = None) -> None:
        ...

    def HDRExposure(self) -> float:
        """
        :returns: the current HDR Exposure value
        """

        ...

    def HDRGamma(self) -> float:
        """
        :returns: the current HDR Gamma value
        """

        ...

    def activateResource(self, resource: Resource) -> None:
        """
        activateResource activates the given resource.

        :param resource: a pattern, gradient or paintop preset
        """

        ...

    def backgroundColor(self) -> ManagedColor:
        """
        backgroundColor allows access to the currently active background color. This is nominally per canvas/view, but in practice per mainwindow.

        :returns: The current background color
        """

        ...

    def brushRotation(self) -> float:
        """
        return the current rotation for brush tip

        :returns: the brush tip rotation value (in degrees)
        """

        ...

    def brushSize(self) -> float:
        """
        return the current size for brush

        :returns: the brush size value (in pixels)
        """

        ...

    def canvas(self) -> Canvas:
        """
        :returns: the canvas this view is showing. The canvas controls things like zoom and rotation.
        """

        ...

    def currentBlendingMode(self) -> str:
        """
        return the current blending mode for brush

        :returns: the current blending mode identifier
        """

        ...

    def currentBrushPreset(self) -> Resource:
        """
        return the current selected preset

        :returns: the current preset (`Resource` type = 'preset')
        """

        ...

    def currentGradient(self) -> Resource:
        """
        return the current selected gradient

        :returns: the current gradient (`Resource` type = 'gradient')
        """

        ...

    def currentPattern(self) -> Resource:
        """
        return the current selected pattern

        :returns: the current pattern (`Resource` type = 'pattern')
        """

        ...

    def disablePressure(self) -> bool:
        """
        return current disabled pressure status

        :returns: True if is pressure is disabled, otherwise False
        """

        ...

    def document(self) -> Document:
        """
        :returns: the document this view is showing.
        """

        ...

    def eraserMode(self) -> bool:
        """
        return current eraser mode status (active/inactive)

        :returns: True if eraser mode is active, otherwise False
        """

        ...

    def flakeToCanvasTransform(self) -> QTransform:
        """
        flakeToCanvasTransform The transformation of the canvas relative to the view without rotation and mirroring

        :returns: QTransform
        """

        ...

    def flakeToDocumentTransform(self) -> QTransform:
        """
        flakeToDocumentTransform The transformation of the document relative to the view without rotation and mirroring

        :returns: QTransform
        """

        ...

    def flakeToImageTransform(self) -> QTransform:
        """
        flakeToImageTransform The transformation of the image relative to the view without rotation and mirroring

        :returns: QTransform
        """

        ...

    def foregroundColor(self) -> ManagedColor:
        """
        foregroundColor allows access to the currently active foreground color.
           This is nominally per canvas/view, but in practice per mainwindow.

           @code
         color = Application.activeWindow().activeView().`foregroundColor()` components = color.components() components[0] = 1.0 components[1] = 0.6 components[2] = 0.7 color.setComponents(components) Application.activeWindow().activeView().setForeGroundColor(color)


        :returns: The current foreground color
        """

        ...

    def globalAlphaLock(self) -> bool:
        """
        return current global alpha lock mode (active/inactive)

        :returns: True if is active, otherwise False
        """

        ...

    def paintingFlow(self) -> float:
        """
        return the current flow for brush

        :returns: the brush flow value
        """

        ...

    def paintingOpacity(self) -> float:
        """
        return the current opacity for brush

        :returns: the brush opacity value (0.00=fully transparent - 1.00=fully opaque)
        """

        ...

    def patternSize(self) -> float:
        """
        return the current pattern size for brush

        :returns: the brush pattern size value
        """

        ...

    def selectedNodes(self) -> list[Node]:
        """
        selectedNodes returns a list of Nodes that are selected in this view.


        ```
        from krita import *
        w = Krita.instance().activeWindow()
        v = w.activeView()
        selected_nodes = v.selectedNodes()
        print(selected_nodes)
        ```


        :returns: a list of `Node` objects which may be empty.
        """

        ...

    def setBackGroundColor(self, color: ManagedColor) -> None:
        ...

    def setBrushRotation(self, brushRotation: float) -> None:
        """
        set the current rotation for brush tip

        :param brushRotation: the brush tip rotation (in degrees)
        """

        ...

    def setBrushSize(self, brushSize: float) -> None:
        """
        set the current size for brush

        :param brushSize: the brush size (in pixels)
        """

        ...

    def setCurrentBlendingMode(self, blendingMode: str) -> None:
        """
        set the current blending mode for brush

        :param blendingMode: the current belding mode identifier
        """

        ...

    def setCurrentBrushPreset(self, resource: Resource) -> None:
        """
        set the current selected preset

        :param resource: the current preset to set (`Resource` type = 'preset')
        """

        ...

    def setCurrentGradient(self, resource: Resource) -> None:
        """
        set the current selected gradient

        :param resource: the current gradient to set (`Resource` type = 'gradient')
        """

        ...

    def setCurrentPattern(self, resource: Resource) -> None:
        """
        set the current selected pattern

        :param resource: the current pattern to set (`Resource` type = 'pattern')
        """

        ...

    def setDisablePressure(self, value: bool) -> None:
        """
        set current disabled pressure status

        :param value: Set to True to disable pressure, False to enabled pressure
        """

        ...

    def setDocument(self, document: Document) -> None:
        """
        Reset the view to show `document`.
        """

        ...

    def setEraserMode(self, value: bool) -> None:
        """
        set current eraser active/inactive

        :param value: Set to True to activate eraser mode, False to deactivate
        """

        ...

    def setForeGroundColor(self, color: ManagedColor) -> None:
        ...

    def setGlobalAlphaLock(self, value: bool) -> None:
        """
        set current global alpha lock mode active/inactive

        :param value: Set to True to lock global alpha mode, False to unlock
        """

        ...

    def setHDRExposure(self, exposure: float) -> None:
        """
        set the current HDR Exposure value

        :param exposure: the HDR Exposure to set
        """

        ...

    def setHDRGamma(self, gamma: float) -> None:
        """
        set the current HDR Gamma value

        :param exposure: the HDR Gamma to set
        """

        ...

    def setPaintingFlow(self, flow: float) -> None:
        """
        set the current flow value for brush

        :param flow: the brush flow
        """

        ...

    def setPaintingOpacity(self, opacity: float) -> None:
        """
        set the current opacity for brush

        :param opacity: the opacity value (0.00=fully transparent - 1.00=fully opaque)
        """

        ...

    def setPatternSize(self, size: float) -> None:
        """
        set the current pattern size value for brush

        :param flow: the brush pattern size
        """

        ...

    def setVisible(self) -> None:
        """
        Make the current view visible.
        """

        ...

    def showFloatingMessage(self, message: str, icon: QIcon, timeout: int, priority: int) -> None:
        """
        showFloatingMessage displays a floating message box on the top-left corner of the canvas

        :param message: Message to be displayed inside the floating message box
        :param icon: Icon to be displayed inside the message box next to the message string
        :param timeout: Milliseconds until the message box disappears
        :param priority: 0 = High, 1 = Medium, 2 = Low. Higher priority messages will be displayed in place of lower priority messages
        """

        ...

    def visible(self) -> bool:
        """
        :returns: True if the current view is visible, False if not.
        """

        ...

    def window(self) -> Window:
        """
        :returns: the window this view is shown in.
        """

        ...