# Generated by build.py — DO NOT EDIT

from typing import ClassVar
from PyQt5.QtCore import QObject, pyqtSignal
from PyQt5.QtWidgets import QAction, QDockWidget, QMainWindow
from krita._types._opaque import KisMainWindow
from krita._types.document import Document
from krita._types.view import View


class Window:
    """
    `Window` represents one `Krita` mainwindow. A window can have any number of views open on any number of documents.
    """

    def __init__(self, window: KisMainWindow, parent: QObject = None) -> None:
        ...

    def activate(self) -> None:
        """
        activate activates this `Window`.
        """

        ...

    def activeView(self) -> View:
        """
        :returns: the currently active view or 0 if no view is active
        """

        ...

    def addView(self, document: Document) -> View:
        """
        Open a new view on the given document in this window
        """

        ...

    def close(self) -> None:
        """
        close the active window and all its Views. If there are no Views left for a given `Document`, that `Document` will also be closed.
        """

        ...

    def createAction(self, id: str, text: str = "", menuLocation: str = 'tools/scripts') -> QAction:
        """
        createAction creates a QAction object and adds it to the action manager for this `Window`.

        :returns: the new action.

        :param id: The unique id for the action. This will be used to propertize the action if any .action file is present
        :param text: The user-visible text of the action. If empty, the text from the .action file is used.
        :param menuLocation: a /-separated string that describes which menu the action should be places in. Default is "tools/scripts"
        """

        ...

    def dockers(self) -> list[QDockWidget]:
        """
        dockers

        :returns: a list of all the dockers belonging to this window
        """

        ...

    def qwindow(self) -> QMainWindow:
        """
        Return a handle to the QMainWindow widget. This is useful to e.g. parent dialog boxes and message box.
        """

        ...

    def showView(self, v: View) -> None:
        """
        Make the given view active in this window. If the view does not belong to this window, nothing happens.
        """

        ...

    def views(self) -> list[View]:
        """
        :returns: a list of open views in this window
        """

        ...

    activeViewChanged: ClassVar[pyqtSignal]  # Emitted when the active view changes.

    themeChanged: ClassVar[pyqtSignal]  # Emitted when we change the color theme.

    windowClosed: ClassVar[pyqtSignal]  # Emitted when the window is closed.